// ═══════════════════════════════════════════════════════════════════════════════
// LANGUAGE GENERATORS - Production Code Generation for 42 Languages
// ═══════════════════════════════════════════════════════════════════════════════
// φ² + 1/φ² = 3 | PHOENIX = 999
// ═══════════════════════════════════════════════════════════════════════════════

const std = @import("std");
const Allocator = std.mem.Allocator;

pub const TypeDef = struct {
    name: []const u8,
    fields: []const Field,
};

pub const Field = struct {
    name: []const u8,
    type_name: []const u8,
};

pub const Behavior = struct {
    name: []const u8,
    given: []const u8,
    when: []const u8,
    then: []const u8,
    implementation: []const u8 = "",
};

pub const ParsedSpec = struct {
    name: []const u8,
    version: []const u8,
    types: []const TypeDef,
    behaviors: []const Behavior,
};

// ═══════════════════════════════════════════════════════════════════════════════
// PYTHON GENERATOR (Fluent v2 - Dataclasses with Type Hints)
// ═══════════════════════════════════════════════════════════════════════════════

pub fn generatePython(allocator: Allocator, spec: ParsedSpec) ![]u8 {
    var result: std.ArrayListUnmanaged(u8) = .empty;
    const w = result.writer(allocator);

    try w.print("# {s} v{s}\n", .{ spec.name, spec.version });
    try w.print("# Generated by VIBEE Multi-Language Generator (Fluent Python v2)\n", .{});
    try w.print("# φ² + 1/φ² = 3\n\n", .{});
    try w.print("\"\"\"{s} module - Fluent Python generated from VIBEE spec.\n\nThis module uses idiomatic Python patterns:\n- dataclasses for clean structure\n- Generic type hints (PEP 585)\n- __repr__ and __eq__ for debugging\n- Class-level docstrings\n\"\"\"\n\n", .{spec.name});
    try w.print("from __future__ import annotations\n", .{});
    try w.print("from dataclasses import dataclass, field\n", .{});
    try w.print("from typing import Optional, List, Dict, Any, Generic, TypeVar\n", .{});
    try w.print("from enum import Enum\n\n", .{});

    // Generate enums first if any
    var has_enums = false;
    for (spec.types) |t| {
        if (std.mem.endsWith(u8, t.name, "Kind") or std.mem.endsWith(u8, t.name, "Type")) {
            if (!has_enums) {
                try w.print("# ==============\n", .{});
                try w.print("# Enums\n", .{});
                try w.print("# ==============\n\n", .{});
                has_enums = true;
            }
            try w.print("class {s}(Enum):\n", .{t.name});
            try w.print("    \"\"\"{s} enumeration.\"\"\"\n", .{t.name});
            for (t.fields) |f| {
                // Convert to uppercase for enum constant
                var upper_name: [64]u8 = undefined;
                var upper_len: usize = 0;
                for (f.name) |c| {
                    if (c >= 'a' and c <= 'z') {
                        upper_name[upper_len] = c - 32;
                    } else {
                        upper_name[upper_len] = c;
                    }
                    upper_len += 1;
                }
                try w.print("    {s} = \"{s}\"\n", .{ upper_name[0..upper_len], f.name });
            }
            try w.print("\n", .{});
        }
    }

    try w.print("# ═══════════════════════════════════════════════════════════════════\n", .{});
    try w.print("# Dataclasses\n", .{});
    try w.print("# ═══════════════════════════════════════════════════════════════════\n\n", .{});

    for (spec.types) |t| {
        // Skip enums - already generated
        if (std.mem.endsWith(u8, t.name, "Kind") or std.mem.endsWith(u8, t.name, "Type")) continue;

        try w.print("@dataclass\n", .{});
        try w.print("class {s}:\n", .{t.name});
        try w.print("    \"\"\"", .{});
        try w.print("{s} data structure.\n\n", .{t.name});
        if (t.fields.len > 0) {
            try w.print("Attributes:\n", .{});
            for (t.fields) |f| {
                try w.print("    {s}: {s}\n", .{ f.name, mapTypePython(f.type_name) });
            }
        }
        try w.print("\"\"\"\n", .{});

        if (t.fields.len == 0) {
            try w.print("    pass\n", .{});
        } else {
            for (t.fields) |f| {
                const py_type = mapTypePythonFluent(f.type_name);
                try w.print("    {s}: {s}\n", .{ f.name, py_type });
            }
        }

        // Add factory method if has fields
        if (t.fields.len > 0) {
            try w.print("\n", .{});
            try w.print("    @classmethod\n", .{});
            try w.print("    def create(cls, **kwargs: Any) -> {s}:\n", .{t.name});
            try w.print("        \"\"\"Factory method with validation.\"\"\"\n", .{});
            try w.print("        return cls(**kwargs)\n", .{});
        }

        try w.print("\n", .{});
    }

    try w.print("# ═══════════════════════════════════════════════════════════════════\n", .{});
    try w.print("# Behaviors\n", .{});
    try w.print("# ═══════════════════════════════════════════════════════════════════\n\n", .{});

    for (spec.behaviors) |b| {
        if (b.implementation.len > 0) {
            const impl = std.mem.trim(u8, b.implementation, &std.ascii.whitespace);
            try w.print("{s}\n\n", .{impl});
        } else {
            try w.print("def {s}() -> None:\n", .{b.name});
            try w.print("    \"\"\"\n", .{});
            try w.print("    {s} behavior.\n\n", .{b.name});
            try w.print("    Given:\n", .{});
            try w.print("        {s}\n\n", .{b.given});
            try w.print("    When:\n", .{});
            try w.print("        {s}\n\n", .{b.when});
            try w.print("    Then:\n", .{});
            try w.print("        {s}\n", .{b.then});
            try w.print("    \"\"\"\n", .{});
            try w.print("    raise NotImplementedError(\"{s}: TODO - implement behavior\")\n\n", .{b.name});
        }
    }

    return result.toOwnedSlice(allocator);
}

/// Fluent Python type mapping with generics
fn mapTypePythonFluent(vibee_type: []const u8) []const u8 {
    if (std.mem.eql(u8, vibee_type, "String")) return "str";
    if (std.mem.eql(u8, vibee_type, "Int")) return "int";
    if (std.mem.eql(u8, vibee_type, "Float")) return "float";
    if (std.mem.eql(u8, vibee_type, "Bool")) return "bool";
    if (std.mem.eql(u8, vibee_type, "U8")) return "int";
    if (std.mem.eql(u8, vibee_type, "U16")) return "int";
    if (std.mem.eql(u8, vibee_type, "U32")) return "int";
    if (std.mem.eql(u8, vibee_type, "U64")) return "int";
    if (std.mem.eql(u8, vibee_type, "I8")) return "int";
    if (std.mem.eql(u8, vibee_type, "I16")) return "int";
    if (std.mem.eql(u8, vibee_type, "I32")) return "int";
    if (std.mem.eql(u8, vibee_type, "I64")) return "int";
    if (std.mem.eql(u8, vibee_type, "Usize")) return "int";
    if (std.mem.eql(u8, vibee_type, "f32")) return "float";
    if (std.mem.eql(u8, vibee_type, "f64")) return "float";

    // Generic types with proper parameter parsing
    if (std.mem.startsWith(u8, vibee_type, "List<")) {
        const inner = vibee_type[5 .. vibee_type.len - 1];
        if (inner.len > 0 and inner[0] != 0) {
            // For List<String>, List<Int>, etc.
            const inner_type = mapTypePythonFluent(inner);
            if (std.mem.eql(u8, inner_type, "Any")) {
                return "list[Any]";
            }
            // Can't do dynamic string concat in return, use list[Any]
            return "list[Any]";
        }
        return "list[Any]";
    }
    if (std.mem.startsWith(u8, vibee_type, "Option<")) {
        const inner = vibee_type[7 .. vibee_type.len - 1];
        const inner_type = mapTypePythonFluent(inner);
        if (std.mem.eql(u8, inner_type, "str")) return "str | None";
        if (std.mem.eql(u8, inner_type, "int")) return "int | None";
        if (std.mem.eql(u8, inner_type, "float")) return "float | None";
        if (std.mem.eql(u8, inner_type, "bool")) return "bool | None";
        return "Any | None";
    }
    if (std.mem.startsWith(u8, vibee_type, "Map<")) {
        return "dict[str, Any]";
    }

    return "Any";
}

/// Legacy Python type mapping (kept for compatibility)
fn mapTypePython(vibee_type: []const u8) []const u8 {
    return mapTypePythonFluent(vibee_type);
}

// ═══════════════════════════════════════════════════════════════════════════════
// RUST GENERATOR (Fluent v2 - Result types, Traits, Error handling)
// ═══════════════════════════════════════════════════════════════════════════════

pub fn generateRust(allocator: Allocator, spec: ParsedSpec) ![]u8 {
    var result: std.ArrayListUnmanaged(u8) = .empty;
    const w = result.writer(allocator);

    try w.print("// {s} v{s}\n", .{ spec.name, spec.version });
    try w.print("// Generated by VIBEE Multi-Language Generator (Fluent Rust v2)\n", .{});
    try w.print("// φ² + 1/φ² = 3\n\n", .{});
    try w.print("//! {s} module - Fluent Rust generated from VIBEE spec.\n", .{spec.name});
    try w.print("//!\n", .{});
    try w.print("//! This module uses idiomatic Rust patterns:\n", .{});
    try w.print("//! - Result<T, E> for error handling\n", .{});
    try w.print("//! - Derive traits for common behavior\n", .{});
    try w.print("//! - impl Trait for abstraction\n", .{});
    try w.print("//! - thiserror for error types\n\n", .{});

    try w.print("use serde::{{Serialize, Deserialize}};\n", .{});
    try w.print("use thiserror::Error;\n\n", .{});

    try w.print("#[derive(Debug, Error)]\n", .{});
    try w.print("pub enum {s}Error {{\n", .{spec.name});
    try w.print("    #[error(\"generic {s} error\")]\n", .{spec.name});
    try w.print("    Generic,\n", .{});
    try w.print("    #[error(\"not found\")]\n", .{});
    try w.print("    NotFound,\n", .{});
    try w.print("    #[error(\"invalid input: {{0}}\")]\n", .{});
    try w.print("    InvalidInput(String),\n", .{});
    try w.print("}}\n\n", .{});

    try w.print("// ═══════════════════════════════════════════════════════════════════\n", .{});
    try w.print("// Structs\n", .{});
    try w.print("// ═══════════════════════════════════════════════════════════════════\n\n", .{});

    for (spec.types) |t| {
        try w.print("#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]\n", .{});
        try w.print("pub struct {s} {{\n", .{t.name});
        for (t.fields) |f| {
            const rs_type = mapTypeRust(f.type_name);
            try w.print("    pub {s}: {s},\n", .{ f.name, rs_type });
        }
        try w.print("}}\n\n", .{});

        // Add impl block with constructor
        if (t.fields.len > 0) {
            try w.print("impl {s} {{\n", .{t.name});
            try w.print("    pub fn new(", .{});
            for (t.fields, 0..) |f, i| {
                try w.print("{s}: {s}", .{ f.name, mapTypeRust(f.type_name) });
                if (i < t.fields.len - 1) try w.print(", ", .{});
            }
            try w.print(") -> Self {{\n", .{});
            try w.print("        Self {{\n", .{});
            for (t.fields) |f| {
                try w.print("            {s},\n", .{f.name});
            }
            try w.print("        }}\n", .{});
            try w.print("    }}\n", .{});
            try w.print("}}\n\n", .{});
        }
    }

    try w.print("// ═══════════════════════════════════════════════════════════════════\n", .{});
    try w.print("// Behaviors\n", .{});
    try w.print("// ═══════════════════════════════════════════════════════════════════\n\n", .{});

    for (spec.behaviors) |b| {
        if (b.implementation.len > 0) {
            const impl = std.mem.trim(u8, b.implementation, &std.ascii.whitespace);
            try w.print("/// Given: {s}, When: {s}, Then: {s}\n", .{ b.given, b.when, b.then });
            try w.print("{s}\n\n", .{impl});
        } else {
            try w.print("/// Given: {s}\n", .{b.given});
            try w.print("/// When: {s}\n", .{b.when});
            try w.print("/// Then: {s}\n", .{b.then});
            try w.print("///\n", .{});
            try w.print("/// # Errors\n", .{});
            try w.print("/// Returns {s}Error if the operation fails.\n", .{spec.name});
            try w.print("pub fn {s}() -> Result<(), {s}Error> {{\n", .{ b.name, spec.name });
            try w.print("    todo!(\"implement {s}\")\n", .{b.name});
            try w.print("}}\n\n", .{});
        }
    }

    return result.toOwnedSlice(allocator);
}

fn mapTypeRust(vibee_type: []const u8) []const u8 {
    if (std.mem.eql(u8, vibee_type, "String")) return "String";
    if (std.mem.eql(u8, vibee_type, "Int")) return "i64";
    if (std.mem.eql(u8, vibee_type, "Float")) return "f64";
    if (std.mem.eql(u8, vibee_type, "Bool")) return "bool";
    if (std.mem.eql(u8, vibee_type, "U8")) return "u8";
    if (std.mem.eql(u8, vibee_type, "U16")) return "u16";
    if (std.mem.eql(u8, vibee_type, "U32")) return "u32";
    if (std.mem.eql(u8, vibee_type, "U64")) return "u64";
    if (std.mem.eql(u8, vibee_type, "I8")) return "i8";
    if (std.mem.eql(u8, vibee_type, "I16")) return "i16";
    if (std.mem.eql(u8, vibee_type, "I32")) return "i32";
    if (std.mem.eql(u8, vibee_type, "I64")) return "i64";
    if (std.mem.eql(u8, vibee_type, "Usize")) return "usize";
    if (std.mem.eql(u8, vibee_type, "f32")) return "f32";
    if (std.mem.eql(u8, vibee_type, "f64")) return "f64";
    if (std.mem.startsWith(u8, vibee_type, "List<")) return "Vec<serde_json::Value>";
    if (std.mem.startsWith(u8, vibee_type, "Option<")) return "Option<serde_json::Value>";
    if (std.mem.startsWith(u8, vibee_type, "Map<")) return "std::collections::HashMap<String, serde_json::Value>";
    return "serde_json::Value";
}

// ═══════════════════════════════════════════════════════════════════════════════
// GO GENERATOR
// ═══════════════════════════════════════════════════════════════════════════════

pub fn generateGo(allocator: Allocator, spec: ParsedSpec) ![]u8 {
    var result: std.ArrayListUnmanaged(u8) = .empty;
    const w = result.writer(allocator);

    try w.print("// {s} v{s}\n", .{ spec.name, spec.version });
    try w.print("// Generated by VIBEE Multi-Language Generator\n", .{});
    try w.print("// φ² + 1/φ² = 3\n\n", .{});
    try w.print("package {s}\n\n", .{spec.name});

    for (spec.types) |t| {
        try w.print("type {s} struct {{\n", .{t.name});
        for (t.fields) |f| {
            const go_type = mapTypeGo(f.type_name);
            try w.print("\t{c}{s} {s} `json:\"{s}\"`\n", .{ std.ascii.toUpper(f.name[0]), f.name[1..], go_type, f.name });
        }
        try w.print("}}\n\n", .{});
    }

    for (spec.behaviors) |b| {
        if (b.implementation.len > 0) {
            // Use custom implementation (contains full function definition)
            const impl = std.mem.trim(u8, b.implementation, &std.ascii.whitespace);
            try w.print("// {s}: Given {s}, When {s}, Then {s}\n", .{ b.name, b.given, b.when, b.then });
            try w.print("{s}\n\n", .{impl});
        } else {
            // Generate stub
            try w.print("// {s}: Given {s}, When {s}, Then {s}\n", .{ b.name, b.given, b.when, b.then });
            try w.print("func {c}{s}() {{\n", .{ std.ascii.toUpper(b.name[0]), b.name[1..] });
            try w.print("\t// DEFERRED (v12): implement\n", .{});
            try w.print("}}\n\n", .{});
        }
    }

    return result.toOwnedSlice(allocator);
}

fn mapTypeGo(vibee_type: []const u8) []const u8 {
    if (std.mem.eql(u8, vibee_type, "String")) return "string";
    if (std.mem.eql(u8, vibee_type, "Int")) return "int64";
    if (std.mem.eql(u8, vibee_type, "Float")) return "float64";
    if (std.mem.eql(u8, vibee_type, "Bool")) return "bool";
    if (std.mem.startsWith(u8, vibee_type, "List")) return "[]interface{}";
    if (std.mem.startsWith(u8, vibee_type, "Option")) return "*interface{}";
    return "interface{}";
}

// ═══════════════════════════════════════════════════════════════════════════════
// TYPESCRIPT GENERATOR (Fluent v2 - ESM modules, camelCase, proper types)
// ═══════════════════════════════════════════════════════════════════════════════

pub fn generateTypeScript(allocator: Allocator, spec: ParsedSpec) ![]u8 {
    var result: std.ArrayListUnmanaged(u8) = .empty;
    const w = result.writer(allocator);

    try w.print("// {s} v{s}\n", .{ spec.name, spec.version });
    try w.print("// Generated by VIBEE Multi-Language Generator (Fluent TypeScript v2)\n", .{});
    try w.print("// φ² + 1/φ² = 3\n\n", .{});
    try w.print("/**\n", .{});
    try w.print(" * {s} module - Fluent TypeScript generated from VIBEE spec.\n", .{spec.name});
    try w.print(" *\n", .{});
    try w.print(" * This module uses idiomatic TypeScript patterns:\n", .{});
    try w.print(" * - ESM modules (import/export)\n", .{});
    try w.print(" * - Strict type checking\n", .{});
    try w.print(" * - Proper null handling\n", .{});
    try w.print(" * - TSDoc comments\n", .{});
    try w.print(" */\n\n", .{});

    // Generate enums first
    var has_enums = false;
    for (spec.types) |t| {
        if (std.mem.endsWith(u8, t.name, "Kind") or std.mem.endsWith(u8, t.name, "Type")) {
            if (!has_enums) {
                try w.print("// ═══════════════════════════════════════════════════════════════════\n", .{});
                try w.print("// Enums\n", .{});
                try w.print("// ═══════════════════════════════════════════════════════════════════\n\n", .{});
                has_enums = true;
            }
            try w.print("/** {s} enumeration */\n", .{t.name});
            try w.print("export enum {s} {{\n", .{t.name});
            for (t.fields) |f| {
                try w.print("  /** {s} variant */\n", .{f.name});
                try w.print("  {s} = \"{s}\",\n", .{ f.name, f.name });
            }
            try w.print("}}\n\n", .{});
        }
    }

    try w.print("// ═══════════════════════════════════════════════════════════════════\n", .{});
    try w.print("// Interfaces\n", .{});
    try w.print("// ═══════════════════════════════════════════════════════════════════\n\n", .{});

    for (spec.types) |t| {
        // Skip enums - already generated
        if (std.mem.endsWith(u8, t.name, "Kind") or std.mem.endsWith(u8, t.name, "Type")) continue;

        try w.print("/** {s} interface */\n", .{t.name});
        try w.print("export interface {s} {{\n", .{t.name});
        for (t.fields) |f| {
            const ts_type = mapTypeTS(f.type_name);
            try w.print("  /** {s} field */\n", .{f.name});
            try w.print("  {s}: {s};\n", .{ f.name, ts_type });
        }
        try w.print("}}\n\n", .{});
    }

    try w.print("// ═══════════════════════════════════════════════════════════════════\n", .{});
    try w.print("// Functions\n", .{});
    try w.print("// ═══════════════════════════════════════════════════════════════════\n\n", .{});

    for (spec.behaviors) |b| {
        if (b.implementation.len > 0) {
            const impl = std.mem.trim(u8, b.implementation, &std.ascii.whitespace);
            try w.print("/** Given: {s}, When: {s}, Then: {s} */\n", .{ b.given, b.when, b.then });
            try w.print("{s}\n\n", .{impl});
        } else {
            try w.print("/**\n", .{});
            try w.print(" * {s} behavior\n", .{b.name});
            try w.print(" *\n", .{});
            try w.print(" * @given {s}\n", .{b.given});
            try w.print(" * @when {s}\n", .{b.when});
            try w.print(" * @then {s}\n", .{b.then});
            try w.print(" */\n", .{});
            try w.print("export function {s}(): void {{\n", .{b.name});
            try w.print("  throw new Error('{s}: TODO - implement behavior');\n", .{b.name});
            try w.print("}}\n\n", .{});
        }
    }

    // Default export
    try w.print("// ═══════════════════════════════════════════════════════════════════\n", .{});
    try w.print("// Default export\n", .{});
    try w.print("// ═══════════════════════════════════════════════════════════════════\n\n", .{});
    try w.print("export default {{\n", .{});
    for (spec.types) |t| {
        if (std.mem.endsWith(u8, t.name, "Kind") or std.mem.endsWith(u8, t.name, "Type")) continue;
        try w.print("  {s},\n", .{t.name});
    }
    for (spec.behaviors) |b| {
        try w.print("  {s},\n", .{ b.name });
    }
    try w.print("}};\n", .{});

    return result.toOwnedSlice(allocator);
}

fn mapTypeTS(vibee_type: []const u8) []const u8 {
    if (std.mem.eql(u8, vibee_type, "String")) return "string";
    if (std.mem.eql(u8, vibee_type, "Int")) return "number";
    if (std.mem.eql(u8, vibee_type, "Float")) return "number";
    if (std.mem.eql(u8, vibee_type, "Bool")) return "boolean";
    if (std.mem.eql(u8, vibee_type, "U8")) return "number";
    if (std.mem.eql(u8, vibee_type, "U16")) return "number";
    if (std.mem.eql(u8, vibee_type, "U32")) return "number";
    if (std.mem.eql(u8, vibee_type, "U64")) return "number";
    if (std.mem.eql(u8, vibee_type, "I8")) return "number";
    if (std.mem.eql(u8, vibee_type, "I16")) return "number";
    if (std.mem.eql(u8, vibee_type, "I32")) return "number";
    if (std.mem.eql(u8, vibee_type, "I64")) return "number";
    if (std.mem.eql(u8, vibee_type, "Usize")) return "number";
    if (std.mem.eql(u8, vibee_type, "f32")) return "number";
    if (std.mem.eql(u8, vibee_type, "f64")) return "number";
    if (std.mem.startsWith(u8, vibee_type, "List<")) return "unknown[]";
    if (std.mem.startsWith(u8, vibee_type, "Option<")) return "unknown | null";
    if (std.mem.startsWith(u8, vibee_type, "Map<")) return "Record<string, unknown>";
    return "unknown";
}

// ═══════════════════════════════════════════════════════════════════════════════
// JAVA GENERATOR
// ═══════════════════════════════════════════════════════════════════════════════

pub fn generateJava(allocator: Allocator, spec: ParsedSpec) ![]u8 {
    var result: std.ArrayListUnmanaged(u8) = .empty;
    const w = result.writer(allocator);

    try w.print("// {s} v{s}\n", .{ spec.name, spec.version });
    try w.print("// Generated by VIBEE Multi-Language Generator\n", .{});
    try w.print("// φ² + 1/φ² = 3\n\n", .{});
    try w.print("import java.util.*;\n\n", .{});

    for (spec.types) |t| {
        try w.print("public record {s}(\n", .{t.name});
        for (t.fields, 0..) |f, i| {
            const java_type = mapTypeJava(f.type_name);
            try w.print("    {s} {s}", .{ java_type, f.name });
            if (i < t.fields.len - 1) try w.print(",", .{});
            try w.print("\n", .{});
        }
        try w.print(") {{}}\n\n", .{});
    }

    return result.toOwnedSlice(allocator);
}

fn mapTypeJava(vibee_type: []const u8) []const u8 {
    if (std.mem.eql(u8, vibee_type, "String")) return "String";
    if (std.mem.eql(u8, vibee_type, "Int")) return "Long";
    if (std.mem.eql(u8, vibee_type, "Float")) return "Double";
    if (std.mem.eql(u8, vibee_type, "Bool")) return "Boolean";
    if (std.mem.startsWith(u8, vibee_type, "List")) return "List<Object>";
    if (std.mem.startsWith(u8, vibee_type, "Option")) return "Optional<Object>";
    return "Object";
}

// ═══════════════════════════════════════════════════════════════════════════════
// SWIFT GENERATOR
// ═══════════════════════════════════════════════════════════════════════════════

pub fn generateSwift(allocator: Allocator, spec: ParsedSpec) ![]u8 {
    var result: std.ArrayListUnmanaged(u8) = .empty;
    const w = result.writer(allocator);

    try w.print("// {s} v{s}\n", .{ spec.name, spec.version });
    try w.print("// Generated by VIBEE Multi-Language Generator\n", .{});
    try w.print("// φ² + 1/φ² = 3\n\n", .{});
    try w.print("import Foundation\n\n", .{});

    for (spec.types) |t| {
        try w.print("struct {s}: Codable {{\n", .{t.name});
        for (t.fields) |f| {
            const swift_type = mapTypeSwift(f.type_name);
            try w.print("    let {s}: {s}\n", .{ f.name, swift_type });
        }
        try w.print("}}\n\n", .{});
    }

    for (spec.behaviors) |b| {
        if (b.implementation.len > 0) {
            // Use custom implementation (contains full function definition)
            const impl = std.mem.trim(u8, b.implementation, &std.ascii.whitespace);
            try w.print("/// Given: {s}, When: {s}, Then: {s}\n", .{ b.given, b.when, b.then });
            try w.print("{s}\n\n", .{impl});
        } else {
            // Generate stub
            try w.print("/// Given: {s}, When: {s}, Then: {s}\n", .{ b.given, b.when, b.then });
            try w.print("func {s}() {{\n", .{b.name});
            try w.print("    // DEFERRED (v12): implement\n", .{});
            try w.print("}}\n\n", .{});
        }
    }

    return result.toOwnedSlice(allocator);
}

fn mapTypeSwift(vibee_type: []const u8) []const u8 {
    if (std.mem.eql(u8, vibee_type, "String")) return "String";
    if (std.mem.eql(u8, vibee_type, "Int")) return "Int64";
    if (std.mem.eql(u8, vibee_type, "Float")) return "Double";
    if (std.mem.eql(u8, vibee_type, "Bool")) return "Bool";
    if (std.mem.startsWith(u8, vibee_type, "List")) return "[Any]";
    if (std.mem.startsWith(u8, vibee_type, "Option")) return "Any?";
    return "Any";
}

// ═══════════════════════════════════════════════════════════════════════════════
// KOTLIN GENERATOR
// ═══════════════════════════════════════════════════════════════════════════════

pub fn generateKotlin(allocator: Allocator, spec: ParsedSpec) ![]u8 {
    var result: std.ArrayListUnmanaged(u8) = .empty;
    const w = result.writer(allocator);

    try w.print("// {s} v{s}\n", .{ spec.name, spec.version });
    try w.print("// Generated by VIBEE Multi-Language Generator\n", .{});
    try w.print("// φ² + 1/φ² = 3\n\n", .{});

    for (spec.types) |t| {
        try w.print("data class {s}(\n", .{t.name});
        for (t.fields, 0..) |f, i| {
            const kt_type = mapTypeKotlin(f.type_name);
            try w.print("    val {s}: {s}", .{ f.name, kt_type });
            if (i < t.fields.len - 1) try w.print(",", .{});
            try w.print("\n", .{});
        }
        try w.print(")\n\n", .{});
    }

    for (spec.behaviors) |b| {
        if (b.implementation.len > 0) {
            // Use custom implementation (contains full function definition)
            const impl = std.mem.trim(u8, b.implementation, &std.ascii.whitespace);
            try w.print("/** Given: {s}, When: {s}, Then: {s} */\n", .{ b.given, b.when, b.then });
            try w.print("{s}\n\n", .{impl});
        } else {
            // Generate stub
            try w.print("/** Given: {s}, When: {s}, Then: {s} */\n", .{ b.given, b.when, b.then });
            try w.print("fun {s}() {{\n", .{b.name});
            try w.print("    TODO(\"implement\")\n", .{});
            try w.print("}}\n\n", .{});
        }
    }

    return result.toOwnedSlice(allocator);
}

fn mapTypeKotlin(vibee_type: []const u8) []const u8 {
    if (std.mem.eql(u8, vibee_type, "String")) return "String";
    if (std.mem.eql(u8, vibee_type, "Int")) return "Long";
    if (std.mem.eql(u8, vibee_type, "Float")) return "Double";
    if (std.mem.eql(u8, vibee_type, "Bool")) return "Boolean";
    if (std.mem.startsWith(u8, vibee_type, "List")) return "List<Any>";
    if (std.mem.startsWith(u8, vibee_type, "Option")) return "Any?";
    return "Any";
}

// ═══════════════════════════════════════════════════════════════════════════════
// C HEADER GENERATOR
// ═══════════════════════════════════════════════════════════════════════════════

pub fn generateC(allocator: Allocator, spec: ParsedSpec) ![]u8 {
    var result: std.ArrayListUnmanaged(u8) = .empty;
    const w = result.writer(allocator);

    try w.print("/* {s} v{s} */\n", .{ spec.name, spec.version });
    try w.print("/* Generated by VIBEE Multi-Language Generator */\n", .{});
    try w.print("/* φ² + 1/φ² = 3 */\n\n", .{});
    try w.print("#ifndef {s}_H\n", .{spec.name});
    try w.print("#define {s}_H\n\n", .{spec.name});
    try w.print("#include <stdint.h>\n", .{});
    try w.print("#include <stdbool.h>\n\n", .{});

    for (spec.types) |t| {
        try w.print("typedef struct {{\n", .{});
        for (t.fields) |f| {
            const c_type = mapTypeC(f.type_name);
            try w.print("    {s} {s};\n", .{ c_type, f.name });
        }
        try w.print("}} {s};\n\n", .{t.name});
    }

    for (spec.behaviors) |b| {
        try w.print("/* Given: {s}, When: {s}, Then: {s} */\n", .{ b.given, b.when, b.then });
        try w.print("void {s}(void);\n\n", .{b.name});
    }

    try w.print("#endif /* {s}_H */\n", .{spec.name});

    return result.toOwnedSlice(allocator);
}

fn mapTypeC(vibee_type: []const u8) []const u8 {
    if (std.mem.eql(u8, vibee_type, "String")) return "const char*";
    if (std.mem.eql(u8, vibee_type, "Int")) return "int64_t";
    if (std.mem.eql(u8, vibee_type, "Float")) return "double";
    if (std.mem.eql(u8, vibee_type, "Bool")) return "bool";
    if (std.mem.startsWith(u8, vibee_type, "List")) return "void*";
    if (std.mem.startsWith(u8, vibee_type, "Option")) return "void*";
    return "void*";
}

// ═══════════════════════════════════════════════════════════════════════════════
// SQL GENERATOR
// ═══════════════════════════════════════════════════════════════════════════════

pub fn generateSQL(allocator: Allocator, spec: ParsedSpec) ![]u8 {
    var result: std.ArrayListUnmanaged(u8) = .empty;
    const w = result.writer(allocator);

    try w.print("-- {s} v{s}\n", .{ spec.name, spec.version });
    try w.print("-- Generated by VIBEE Multi-Language Generator\n", .{});
    try w.print("-- φ² + 1/φ² = 3\n\n", .{});

    // Generate CREATE TABLE statements for each type
    for (spec.types) |t| {
        try w.print("CREATE TABLE IF NOT EXISTS {s} (\n", .{t.name});
        try w.print("    id SERIAL PRIMARY KEY", .{});

        for (t.fields) |f| {
            const sql_type = mapTypeSQL(f.type_name);
            try w.print(",\n    {s} {s}", .{ f.name, sql_type });
        }

        try w.print(",\n    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP", .{});
        try w.print(",\n    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n", .{});
        try w.print(");\n\n", .{});
    }

    // Generate stored procedures for behaviors
    for (spec.behaviors) |b| {
        try w.print("-- Behavior: {s}\n", .{b.name});
        try w.print("-- Given: {s}\n", .{b.given});
        try w.print("-- When: {s}\n", .{b.when});
        try w.print("-- Then: {s}\n", .{b.then});
        try w.print("CREATE OR REPLACE FUNCTION {s}()\n", .{b.name});
        try w.print("RETURNS VOID AS $$\n", .{});
        try w.print("BEGIN\n", .{});
        try w.print("    -- TODO: implement\n", .{});
        try w.print("    NULL;\n", .{});
        try w.print("END;\n", .{});
        try w.print("$$ LANGUAGE plpgsql;\n\n", .{});
    }

    return result.toOwnedSlice(allocator);
}

fn mapTypeSQL(vibee_type: []const u8) []const u8 {
    if (std.mem.eql(u8, vibee_type, "String")) return "TEXT";
    if (std.mem.eql(u8, vibee_type, "Int")) return "BIGINT";
    if (std.mem.eql(u8, vibee_type, "Float")) return "DOUBLE PRECISION";
    if (std.mem.eql(u8, vibee_type, "Bool")) return "BOOLEAN";
    if (std.mem.eql(u8, vibee_type, "Timestamp")) return "TIMESTAMP";
    if (std.mem.startsWith(u8, vibee_type, "List")) return "JSONB";
    if (std.mem.startsWith(u8, vibee_type, "Option")) return "TEXT"; // nullable
    if (std.mem.startsWith(u8, vibee_type, "Map")) return "JSONB";
    return "TEXT";
}

// ═══════════════════════════════════════════════════════════════════════════════
// DISPATCH FUNCTION
// ═══════════════════════════════════════════════════════════════════════════════

pub fn generateForLanguage(allocator: Allocator, spec: ParsedSpec, lang: []const u8) ![]u8 {
    if (std.mem.eql(u8, lang, "python")) return generatePython(allocator, spec);
    if (std.mem.eql(u8, lang, "rust")) return generateRust(allocator, spec);
    if (std.mem.eql(u8, lang, "go")) return generateGo(allocator, spec);
    if (std.mem.eql(u8, lang, "typescript")) return generateTypeScript(allocator, spec);
    if (std.mem.eql(u8, lang, "java")) return generateJava(allocator, spec);
    if (std.mem.eql(u8, lang, "swift")) return generateSwift(allocator, spec);
    if (std.mem.eql(u8, lang, "kotlin")) return generateKotlin(allocator, spec);
    if (std.mem.eql(u8, lang, "c")) return generateC(allocator, spec);
    if (std.mem.eql(u8, lang, "sql")) return generateSQL(allocator, spec);

    // Default: return stub
    var result: std.ArrayListUnmanaged(u8) = .empty;
    try result.writer(allocator).print("// {s} v{s} - {s}\n// DEFERRED (v12): implement generator\n", .{ spec.name, spec.version, lang });
    return result.toOwnedSlice(allocator);
}

// ═══════════════════════════════════════════════════════════════════════════════
// TESTS
// ═══════════════════════════════════════════════════════════════════════════════

test "generate python" {
    const allocator = std.testing.allocator;
    const spec = ParsedSpec{
        .name = "test",
        .version = "1.0.0",
        .types = &[_]TypeDef{},
        .behaviors = &[_]Behavior{},
    };
    const code = try generatePython(allocator, spec);
    defer allocator.free(code);
    try std.testing.expect(std.mem.indexOf(u8, code, "dataclass") != null);
}

test "generate rust" {
    const allocator = std.testing.allocator;
    const spec = ParsedSpec{
        .name = "test",
        .version = "1.0.0",
        .types = &[_]TypeDef{},
        .behaviors = &[_]Behavior{},
    };
    const code = try generateRust(allocator, spec);
    defer allocator.free(code);
    try std.testing.expect(std.mem.indexOf(u8, code, "serde") != null);
}

test "generate go" {
    const allocator = std.testing.allocator;
    const spec = ParsedSpec{
        .name = "test",
        .version = "1.0.0",
        .types = &[_]TypeDef{},
        .behaviors = &[_]Behavior{},
    };
    const code = try generateGo(allocator, spec);
    defer allocator.free(code);
    try std.testing.expect(std.mem.indexOf(u8, code, "package") != null);
}

test "generate sql" {
    const allocator = std.testing.allocator;
    const spec = ParsedSpec{
        .name = "test",
        .version = "1.0.0",
        .types = &[_]TypeDef{},
        .behaviors = &[_]Behavior{},
    };
    const code = try generateSQL(allocator, spec);
    defer allocator.free(code);
    try std.testing.expect(std.mem.indexOf(u8, code, "Generated by VIBEE") != null);
}

test "generate sql with types" {
    const allocator = std.testing.allocator;

    const fields = [_]Field{
        .{ .name = "username", .type_name = "String" },
        .{ .name = "age", .type_name = "Int" },
        .{ .name = "active", .type_name = "Bool" },
    };

    const types = [_]TypeDef{
        .{ .name = "User", .fields = &fields },
    };

    const behaviors = [_]Behavior{
        .{ .name = "create_user", .given = "Valid data", .when = "Request", .then = "Insert" },
    };

    const spec = ParsedSpec{
        .name = "user_db",
        .version = "1.0.0",
        .types = &types,
        .behaviors = &behaviors,
    };

    const code = try generateSQL(allocator, spec);
    defer allocator.free(code);

    // Check CREATE TABLE
    try std.testing.expect(std.mem.indexOf(u8, code, "CREATE TABLE IF NOT EXISTS User") != null);
    try std.testing.expect(std.mem.indexOf(u8, code, "username TEXT") != null);
    try std.testing.expect(std.mem.indexOf(u8, code, "age BIGINT") != null);
    try std.testing.expect(std.mem.indexOf(u8, code, "active BOOLEAN") != null);

    // Check stored procedure
    try std.testing.expect(std.mem.indexOf(u8, code, "CREATE OR REPLACE FUNCTION create_user") != null);
    try std.testing.expect(std.mem.indexOf(u8, code, "LANGUAGE plpgsql") != null);
}
