// demo_ts v1.0.0
// Generated by VIBEE Multi-Language Generator
// φ² + 1/φ² = 3

export interface Vector {
  x: any;
  y: any;
}

/** Given: two vectors, When: adding them, Then: return sum */
export function add(a: Vector, b: Vector): Vector {
            return { x: a.x + b.x, y: a.y + b.y };
        }

/** Given: a vector, When: computing length, Then: return scalar magnitude */
export function magnitude(v: Vector): number {
            return Math.sqrt(v.x ** 2 + v.y ** 2);
        }

