import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Overview',
      items: [
        'overview/introduction',
        'overview/roadmap',
        'overview/tech-tree',
      ],
    },
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/quickstart',
        'getting-started/tutorial',
        'getting-started/installation',
        'getting-started/development-setup',
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        'concepts/index',
        'concepts/balanced-ternary',
        'concepts/trinity-identity',
        'concepts/glossary',
      ],
    },
    {
      type: 'category',
      label: 'BitNet Integration',
      items: [
        'bitnet/index',
        'bitnet/inference',
        'bitnet/model-format',
      ],
    },
    {
      type: 'category',
      label: 'HDC Applications',
      items: [
        'hdc/index',
        'hdc/applications',
        'hdc/igla-glove-comparison',
      ],
    },
    {
      type: 'category',
      label: 'VIBEE Language',
      items: [
        'vibee/index',
        'vibee/specification',
        'vibee/examples',
        'vibee/theorems',
      ],
    },
    {
      type: 'category',
      label: 'Benchmarks',
      items: [
        'benchmarks/index',
        'benchmarks/gpu-inference',
        'benchmarks/jit-performance',
        'benchmarks/memory-efficiency',
        'benchmarks/competitor-comparison',
        'benchmarks/compression-comparison',
      ],
    },
    {
      type: 'category',
      label: 'Deployment',
      items: [
        'deployment/index',
        'deployment/runpod',
        'deployment/local',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        'api/index',
        'api/vsa',
        'api/vm',
        'api/hybrid',
        'api/firebird',
        'api/vibee',
        'api/plugin',
        'api/sequence-hdc',
        'api/jit',
        'api/sparse',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        'architecture/overview',
      ],
    },
    {
      type: 'category',
      label: 'Mathematical Foundations',
      items: [
        'math-foundations/index',
        'math-foundations/formulas',
        'math-foundations/proofs',
      ],
    },
    {
      type: 'category',
      label: 'Research',
      items: [
        'research/index',
        // Golden Chain Cycles (IGLA)
        'research/cycle26-multimodal-unified-report',
        'research/cycle27-tool-use-report',
        'research/cycle27-import-integration-report',
        'research/cycle28-vision-understanding-report',
        'research/cycle28-real-vsa-calls-report',
        'research/cycle29-voice-io-multimodal-report',
        'research/cycle29-text-encoding-report',
        'research/cycle30-unified-multimodal-agent-report',
        'research/cycle30-semantic-similarity-report',
        'research/cycle31-autonomous-agent-report',
        'research/cycle31-persistent-corpus-report',
        'research/cycle32-multi-agent-orchestration-report',
        'research/cycle32-compressed-corpus-report',
        'research/cycle33-mm-multiagent-orchestration-report',
        'research/cycle33-adaptive-rle-report',
        'research/cycle34-agent-memory-learning-report',
        'research/cycle34-dictionary-compression-report',
        'research/cycle35-persistent-memory-report',
        'research/cycle35-huffman-compression-report',
        'research/cycle36-dynamic-agent-spawning-report',
        'research/cycle36-arithmetic-compression-report',
        'research/cycle37-distributed-multi-node-report',
        'research/cycle37-corpus-sharding-report',
        'research/cycle38-streaming-multimodal-report',
        'research/cycle38-parallel-loading-report',
        'research/cycle39-adaptive-workstealing-report',
        'research/cycle39-thread-pool-report',
        'research/cycle40-plugin-extension-report',
        'research/cycle40-work-stealing-report',
        'research/cycle41-agent-communication-report',
        'research/cycle41-chase-lev-report',
        'research/cycle42-observability-tracing-report',
        'research/cycle42-memory-ordering-report',
        'research/cycle43-consensus-coordination-report',
        'research/cycle43-finetune-engine-report',
        'research/cycle43-adaptive-workstealing-report',
        'research/cycle44-speculative-execution-report',
        'research/cycle44-batched-stealing-report',
        'research/cycle45-adaptive-resource-governor-report',
        'research/cycle45-priority-queue-report',
        'research/cycle46-federated-learning-report',
        'research/cycle46-deadline-scheduling-report',
        'research/cycle47-event-sourcing-cqrs-report',
        'research/cycle47-dag-execution-report',
        'research/cycle48-capability-security-report',
        'research/cycle48-multimodal-agent-report',
        'research/cycle49-distributed-transactions-report',
        'research/cycle49-agent-memory-report',
        'research/cycle50-adaptive-caching-report',
        'research/cycle50-memory-persistence-report',
        'research/cycle51-contract-negotiation-report',
        'research/cycle51-tool-execution-report',
        'research/cycle52-temporal-workflow-report',
        'research/cycle52-multi-agent-orchestration-report',
        'research/cycle53-multi-modal-tool-use-report',
        'research/cycle54-autonomous-agent-report',
        'research/cycle55-self-reflection-improvement-report',
        'research/cycle56-unified-autonomous-system-report',
        // Chat Reports
        'research/trinity-chat-v2-report',
        'research/trinity-chat-v2.3-report',
        'research/trinity-chat-v2.4-report',
        'research/trinity-hybrid-v2.0-report',
        'research/trinity-hybrid-v2.1-report',
        // Fix & Infrastructure Reports
        'research/cycle-f16-fix-report',
        'research/gguf_logit_fix_report',
        'research/gguf_full_fix_report',
        'research/vps_fixed_deploy_report',
        // Photon & Canvas Reports
        'research/photon-trinity-mvp-report',
        'research/photon-trinity-v0.2-report',
        'research/photon-trinity-v0.3-report',
        'research/photon-trinity-v0.4-report',
        'research/photon-terminal-v1-report',
        'research/trinity_canvas_v1.5_report',
        'research/trinity_canvas_v1.6_report',
        'research/trinity_canvas_v1.9_report',
        'research/trinity_canvas_v2.0_report',
        'research/trinity_canvas_v2.1_report',
        'research/trinity_canvas_v2.2_report',
        'research/trinity_canvas_v2.3_report',
        'research/trinity_canvas_v2.4_report',
        'research/trinity_canvas_v2.5_report',
        'research/trinity_canvas_v2.6_report',
        'research/trinity_os_finder_v1_report',
        // Node & Release Reports
        'research/trinity-node-ffi',
        'research/trinity-node-mvp-report',
        'research/trinity-v2-release-report',
        'research/v2-announce-report',
        'research/v2-announce-templates',
        // Reference
        'research/bitnet-report',
        'research/status',
        'research/bibliography',
        'research/references',
        'research/trinity-storage-network-mvp-report',
        'research/trinity-storage-network-v1.1-report',
        'research/trinity-storage-network-v1.2-report',
        'research/trinity-storage-network-v1.3-report',
        'research/trinity-storage-network-v1.4-report',
        'research/trinity-storage-network-v1.5-report',
        'research/trinity-storage-network-v1.6-report',
        'research/trinity-storage-network-v1.7-report',
        'research/trinity-storage-network-v1.8-report',
        'research/trinity-storage-network-v1.9-report',
        'research/trinity-storage-network-v2.0-report',
        'research/trinity-storage-network-v2.1-report',
        'research/trinity-storage-network-v2.2-report',
        'research/trinity-storage-network-v2.3-report',
        'research/trinity-storage-network-v2.4-report',
        'research/trinity-storage-network-v2.5-report',
        'research/trinity-storage-network-v2.6-report',
        // Golden Chain Reports
        'research/golden-chain-v1-1-truth-provenance-report',
        'research/golden-chain-v1-2-quark-gluon-report',
        'research/golden-chain-v1-3-vsa-onchain-report',
        'research/golden-chain-v1-4-phi-report',
        'research/golden-chain-v1-5-report',
        'research/golden-chain-v2-0-immortal-report',
        'research/golden-chain-v2-1-public-report',
        'research/trinity-agent-os-v1-0-report',
        'research/trinity-mainnet-genesis-report',
        'research/trinity-mainnet-v1-0-report',
        'research/trinity-golden-chain-v2-5-u7-report',
        'research/trinity-golden-chain-v2-6-swarm-report',
        'research/trinity-golden-chain-v2-7-community-report',
        'research/trinity-golden-chain-v2-8-dao-report',
        'research/trinity-golden-chain-v2-9-bridge-report',
        'research/trinity-golden-chain-v2-10-dao-report',
        'research/trinity-golden-chain-v2-11-swarm-report',
        'research/trinity-golden-chain-v2-12-zk-report',
        'research/trinity-golden-chain-v2-13-u8-l2-report',
        'research/trinity-golden-chain-v2-14-shard-report',
        'research/trinity-golden-chain-v2-15-swarm-report',
        'research/trinity-golden-chain-v2-16-zk-rollup-report',
        'research/trinity-golden-chain-v2-17-cross-shard-report',
        'research/trinity-golden-chain-v2-18-neuro-symbolic-report',
        'research/trinity-golden-chain-v2-19-transformer-block-report',
      ],
    },
    'faq',
    'troubleshooting',
    'contributing',
  ],
};

export default sidebars;
