import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Overview',
      items: [
        'overview/introduction',
        'overview/roadmap',
        'overview/tech-tree',
      ],
    },
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/quickstart',
        'getting-started/tutorial',
        'getting-started/installation',
        'getting-started/development-setup',
      ],
    },
    {
      type: 'category',
      label: 'TRI CLI Reference',
      items: [
        'cli/index',
        'cli/core',
        'cli/devtools',
        'cli/analysis',
        'cli/pipeline',
        'cli/math',
        'cli/git',
        'cli/vibee-tools',
        'cli/swarm',
        'cli/demos',
        'cli/autonomous',
        'cli/audit',
        'cli/repl',
        'cli/tvc',
        'cli/constants',
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        'concepts/index',
        'concepts/balanced-ternary',
        'concepts/trinity-identity',
        'concepts/glossary',
      ],
    },
    {
      type: 'category',
      label: 'BitNet Integration',
      items: [
        'bitnet/index',
        'bitnet/inference',
        'bitnet/model-format',
      ],
    },
    {
      type: 'category',
      label: 'HDC Applications',
      items: [
        'hdc/index',
        'hdc/applications',
        'hdc/igla-glove-comparison',
      ],
    },
    {
      type: 'category',
      label: 'VIBEE Language',
      items: [
        'vibee/index',
        'vibee/specification',
        'vibee/examples',
        'vibee/theorems',
      ],
    },
    {
      type: 'category',
      label: 'DePIN Network',
      items: [
        'depin/index',
        'depin/quickstart',
        'depin/rewards',
        'depin/tokenomics',
        'depin/api',
        'depin/architecture',
      ],
    },
    {
      type: 'category',
      label: 'Benchmarks',
      items: [
        'benchmarks/index',
        'benchmarks/tri-math-v36-performance',
        'benchmarks/gpu-inference',
        'benchmarks/jit-performance',
        'benchmarks/memory-efficiency',
        'benchmarks/competitor-comparison',
        'benchmarks/compression-comparison',
      ],
    },
    {
      type: 'category',
      label: 'Deployment',
      items: [
        'deployment/index',
        'deployment/runpod',
        'deployment/local',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        'api/index',
        'api/vsa',
        'api/vm',
        'api/hybrid',
        'api/firebird',
        'api/vibee',
        'api/plugin',
        'api/sequence-hdc',
        'api/jit',
        'api/sparse',
        'api/c-api',
        'api/python-sdk',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        'architecture/overview',
      ],
    },
    {
      type: 'category',
      label: 'Mathematical Foundations',
      items: [
        'math-foundations/index',
        'math-foundations/formulas',
        'math-foundations/sacred-formulas',
        'math-foundations/proofs',
      ],
    },
    {
      type: 'category',
      label: 'Research',
      items: [
        'research/index',
        // Golden Chain Cycles (IGLA)
        'research/cycle26-multimodal-unified-report',
        'research/cycle27-tool-use-report',
        'research/cycle27-import-integration-report',
        'research/cycle28-vision-understanding-report',
        'research/cycle28-real-vsa-calls-report',
        'research/cycle29-voice-io-multimodal-report',
        'research/cycle29-text-encoding-report',
        'research/cycle30-unified-multimodal-agent-report',
        'research/cycle30-semantic-similarity-report',
        'research/cycle31-autonomous-agent-report',
        'research/cycle31-persistent-corpus-report',
        'research/cycle32-multi-agent-orchestration-report',
        'research/cycle32-compressed-corpus-report',
        'research/cycle33-mm-multiagent-orchestration-report',
        'research/cycle33-adaptive-rle-report',
        'research/cycle34-agent-memory-learning-report',
        'research/cycle34-dictionary-compression-report',
        'research/cycle35-persistent-memory-report',
        'research/cycle35-huffman-compression-report',
        'research/cycle36-dynamic-agent-spawning-report',
        'research/cycle36-arithmetic-compression-report',
        'research/cycle37-distributed-multi-node-report',
        'research/cycle37-corpus-sharding-report',
        'research/cycle38-streaming-multimodal-report',
        'research/cycle38-parallel-loading-report',
        'research/cycle39-adaptive-workstealing-report',
        'research/cycle39-thread-pool-report',
        'research/cycle40-plugin-extension-report',
        'research/cycle40-work-stealing-report',
        'research/cycle41-agent-communication-report',
        'research/cycle41-chase-lev-report',
        'research/cycle42-observability-tracing-report',
        'research/cycle42-memory-ordering-report',
        'research/cycle43-consensus-coordination-report',
        'research/cycle43-finetune-engine-report',
        'research/cycle43-adaptive-workstealing-report',
        'research/cycle44-speculative-execution-report',
        'research/cycle44-batched-stealing-report',
        'research/cycle45-adaptive-resource-governor-report',
        'research/cycle45-priority-queue-report',
        'research/cycle46-federated-learning-report',
        'research/cycle46-deadline-scheduling-report',
        'research/cycle47-event-sourcing-cqrs-report',
        'research/cycle47-dag-execution-report',
        'research/cycle48-capability-security-report',
        'research/cycle48-multimodal-agent-report',
        'research/cycle49-distributed-transactions-report',
        'research/cycle49-agent-memory-report',
        'research/cycle50-adaptive-caching-report',
        'research/cycle50-memory-persistence-report',
        'research/cycle51-contract-negotiation-report',
        'research/cycle51-tool-execution-report',
        'research/cycle52-temporal-workflow-report',
        'research/cycle52-multi-agent-orchestration-report',
        'research/cycle53-multi-modal-tool-use-report',
        'research/cycle54-autonomous-agent-report',
        'research/cycle55-self-reflection-improvement-report',
        'research/cycle56-unified-autonomous-system-report',
        // Chat Reports
        'research/trinity-chat-v2-report',
        'research/trinity-chat-v2.3-report',
        'research/trinity-chat-v2.4-report',
        'research/trinity-hybrid-v2.0-report',
        'research/trinity-hybrid-v2.1-report',
        // Fix & Infrastructure Reports
        'research/cycle-f16-fix-report',
        'research/gguf_logit_fix_report',
        'research/gguf_full_fix_report',
        'research/vps_fixed_deploy_report',
        // Photon & Canvas Reports
        'research/photon-trinity-mvp-report',
        'research/photon-trinity-v0.2-report',
        'research/photon-trinity-v0.3-report',
        'research/photon-trinity-v0.4-report',
        'research/photon-terminal-v1-report',
        'research/trinity_canvas_v1.5_report',
        'research/trinity_canvas_v1.6_report',
        'research/trinity_canvas_v1.9_report',
        'research/trinity_canvas_v2.0_report',
        'research/trinity_canvas_v2.1_report',
        'research/trinity_canvas_v2.2_report',
        'research/trinity_canvas_v2.3_report',
        'research/trinity_canvas_v2.4_report',
        'research/trinity_canvas_v2.5_report',
        'research/trinity_canvas_v2.6_report',
        'research/trinity_os_finder_v1_report',
        // Node & Release Reports
        'research/trinity-node-ffi',
        'research/trinity-node-mvp-report',
        'research/trinity-v2-release-report',
        'research/v2-announce-report',
        'research/v2-announce-templates',
        // Reference
        'research/bitnet-report',
        'research/status',
        'research/bibliography',
        'research/references',
        'research/trinity-storage-network-mvp-report',
        'research/trinity-storage-network-v1.1-report',
        'research/trinity-storage-network-v1.2-report',
        'research/trinity-storage-network-v1.3-report',
        'research/trinity-storage-network-v1.4-report',
        'research/trinity-storage-network-v1.5-report',
        'research/trinity-storage-network-v1.6-report',
        'research/trinity-storage-network-v1.7-report',
        'research/trinity-storage-network-v1.8-report',
        'research/trinity-storage-network-v1.9-report',
        'research/trinity-storage-network-v2.0-report',
        'research/trinity-storage-network-v2.1-report',
        'research/trinity-storage-network-v2.2-report',
        'research/trinity-storage-network-v2.3-report',
        'research/trinity-storage-network-v2.4-report',
        'research/trinity-storage-network-v2.5-report',
        'research/trinity-storage-network-v2.6-report',
        // Golden Chain Reports
        'research/golden-chain-v1-1-truth-provenance-report',
        'research/golden-chain-v1-2-quark-gluon-report',
        'research/golden-chain-v1-3-vsa-onchain-report',
        'research/golden-chain-v1-4-phi-report',
        'research/golden-chain-v1-5-report',
        'research/golden-chain-v2-0-immortal-report',
        'research/golden-chain-v2-1-public-report',
        'research/trinity-agent-os-v1-0-report',
        'research/trinity-mainnet-genesis-report',
        'research/trinity-mainnet-v1-0-report',
        'research/trinity-golden-chain-v2-5-u7-report',
        'research/trinity-golden-chain-v2-6-swarm-report',
        'research/trinity-golden-chain-v2-7-community-report',
        'research/trinity-golden-chain-v2-8-dao-report',
        'research/trinity-golden-chain-v2-9-bridge-report',
        'research/trinity-golden-chain-v2-10-dao-report',
        'research/trinity-golden-chain-v2-11-swarm-report',
        'research/trinity-golden-chain-v2-12-zk-report',
        'research/trinity-golden-chain-v2-13-u8-l2-report',
        'research/trinity-golden-chain-v2-14-shard-report',
        'research/trinity-golden-chain-v2-15-swarm-report',
        'research/trinity-golden-chain-v2-16-zk-rollup-report',
        'research/trinity-golden-chain-v2-17-cross-shard-report',
        'research/trinity-golden-chain-v2-18-recovery-report',
        'research/trinity-golden-chain-v2-19-transformer-block-report',
        'research/trinity-golden-chain-v2-19-swarm-report',
        'research/trinity-golden-chain-v2-20-forward-engine-report',
        'research/trinity-golden-chain-v2-20-rollup-report',
        'research/trinity-golden-chain-v2-21-cross-shard-report',
        'research/trinity-golden-chain-v2-21-streaming-swarm-report',
        'research/trinity-golden-chain-v2-22-real-execution-report',
        'research/trinity-golden-chain-v2-22-formal-report',
        'research/trinity-golden-chain-v2-23-e2e-live-report',
        'research/trinity-golden-chain-v2-24-execution-apocalypse-report',
        'research/trinity-golden-chain-v2-25-singularity-report',
        'research/trinity-golden-chain-v2-26-empirical-validation-report',
        'research/trinity-golden-chain-v2-27-wiring-report',
        'research/trinity-golden-chain-v2-28-minimal-demo-report',
        'research/trinity-golden-chain-v2-29-first-forward-report',
        'research/trinity-golden-chain-v2-30-multihead-autoreg-report',
        'research/trinity-golden-chain-v2-31-corpus-training-report',
        'research/trinity-golden-chain-v2-32-scaled-honest-report',
        'research/trinity-golden-chain-v2-33-resonator-report',
        'research/trinity-golden-chain-v2-34-direct-role-report',
        'research/trinity-golden-chain-v2-35-hebbian-hybrid-report',
        'research/trinity-golden-chain-v2-36-sampling-report',
        'research/trinity-golden-chain-v2-37-multi-role-report',
        'research/trinity-golden-chain-v2-38-dim1024-report',
        'research/trinity-golden-chain-v2-39-trigram-report',
        'research/trinity-golden-chain-v2-40-large-corpus-report',
        'research/trinity-golden-chain-v2-41-offsets-report',
        'research/trinity-golden-chain-v2-42-weighted-hybrid-report',
        'research/trinity-golden-chain-v2-43-pure-trigram-report',
        'research/trinity-golden-chain-v2-44-raw-freq-report',
        'research/trinity-golden-chain-v2-45-word-level-report',
        'research/trinity-golden-chain-v2-46-word-trigram-report',
        'research/trinity-golden-chain-v2-47-large-corpus-report',
        'research/trinity-golden-chain-v2-48-interpolated-report',
        'research/trinity-golden-chain-v2-49-penalty-report',
        'research/trinity-golden-chain-v2-50-kneser-ney-report',
        'research/trinity-golden-chain-v2-51-4gram-report',
        'research/trinity-golden-chain-v2-52-held-out-report',
        // Level 11: Symbolic Reasoning
        'research/trinity-level11-symbolic-reasoning-report',
        'research/trinity-level11-bipolar-upgrade-report',
        'research/trinity-level11-rdf-multi-hop-report',
        'research/trinity-level11-few-shot-classifier-report',
        'research/trinity-level11-hard-few-shot-report',
        'research/trinity-level11-tree-bundling-report',
        'research/trinity-level11-shared-relation-analogies-report',
        'research/trinity-level11-hybrid-bipolar-ternary-report',
        'research/trinity-level11-large-kg-report',
        'research/trinity-level11-planning-kg-report',
        'research/trinity-level11-intermediate-indexing-report',
        'research/trinity-level11-path-discovery-report',
        'research/trinity-level11-arbitrary-graph-report',
        'research/trinity-level11-massive-kg-report',
        'research/trinity-level11-weighted-edges-report',
        'research/trinity-level11-massive-weighted-report',
        'research/trinity-level11-sota-benchmarks-report',
        'research/trinity-level11-neuro-symbolic-bench-report',
        'research/trinity-level11-full-planning-report',
        'research/trinity-level11-real-world-demo-report',
        'research/trinity-level11-full-engine-fusion-report',
        'research/trinity-level11-deployment-prototype-report',
        'research/trinity-level11-user-testing-report',
        'research/trinity-level11-massive-kg-cli-report',
        'research/trinity-level11-interactive-cli-report',
        'research/trinity-level11-repl-mode-report',
        'research/trinity-level11-pure-agi-report',
        'research/trinity-level11-analogies-benchmark-report',
        'research/trinity-level11-hybrid-bipolar-ternary-report',
        'research/trinity-level11-large-scale-kg-report',
        'research/trinity-level11-planning-sota-report',
        'research/trinity-level11-release-prep-report',
        'research/trinity-level11-agi-deployment-report',
        'research/trinity-level11-community-evolution-report',
        'research/trinity-level11-igla-canvas-maturity-report',
        'research/trinity-level11-real-world-hybrid-report',
        'research/trinity-level11-community-release-report',
        'research/trinity-level11-feedback-evolution-report',
        'research/trinity-level11-final-deployment-report',
        'research/trinity-e2e-kg-pipeline-report',
        'research/trinity-level11-debug-toggle-report',
        'research/trinity-golden-chain-v2-23-swarm-report',
        'research/trinity-golden-chain-v2-24-dominance-report',
        'research/trinity-golden-chain-v2-25-eternal-report',
        'research/trinity-golden-chain-v2-26-tri10-report',
        'research/trinity-golden-chain-v2-27-tri100-report',
        'research/trinity-golden-chain-v2-28-swarm-10m-report',
        'research/trinity-golden-chain-v2-29-u16-swarm-1b-report',
        'research/trinity-golden-chain-v2-30-nn-report',
        'research/trinity-golden-chain-v2-31-tri1000-report',
        'research/trinity-golden-chain-v2-32-beyond-report',
        'research/trinity-golden-chain-v3-0-absolute-report',
        'research/trinity-golden-chain-mainnet-ready-report',
        // SDK Reports
        'research/libtrinity-vsa-v0.2.0-report',
        // Math Framework (Level 11.39)
        'research/trinity-vsa-benchmark-suite-report',
        'research/trinity-multilingual-math-codegen-report',
        // PAS v8.21 Production Validation
        'research/pas-v8.21-production-validation-report',
        // PAS v8.22 Production Final
        'research/pas-v8.22-production-final-report',
        // PAS v8.23 Final Production
        'research/pas-v8.23-final-production-report',
        // PAS v8.24 KOSCHEI MODE
        'research/trinity-golden-chain-v2-32-koschei-mode-report',
        // Cycle 95: Sacred Intelligence Core
        'research/cycle-95-sacred-intelligence-core',
        // Cycle 97: Full Autonomous Sacred Evolution
        'research/cycle-97-full-autonomous-sacred-evolution',
        // Production Releases
        'research/tri-production-dashboard-release',
      ],
    },
    'faq',
    'troubleshooting',
    'contributing',
  ],
};

export default sidebars;
