// ═══════════════════════════════════════════════════════════════════════════════
// fsm_simple v1.0.0 - FPGA Verilog from .vibee specification
// ═══════════════════════════════════════════════════════════════════════════════
//
// Golden Identity: φ² + 1/φ² = 3
//
// DO NOT EDIT - This file is auto-generated by VIBEE
//
// Target:   xilinx (50 MHz)
// ═══════════════════════════════════════════════════════════════════════════════

`timescale 1ns / 1ps

module fsm_simple (
input  wire clk,
output  wire led
);

          // State transition logic
      always @(posedge clk) begin
          if (tick) begin
              case (state)
                  RED:    next_state = GREEN;
                  GREEN:  next_state = YELLOW;
                  YELLOW: next_state = RED;
                  default: next_state = RED;
              endcase
          end
          state <= next_state;
      end



          // Timer for state transitions (~1 second per state)
      reg [25:0] timer = 26'h0;
      wire tick = (timer == 26'h0);

      always @(posedge clk) begin
          timer <= timer + 1'b1;
      end



          // LED output (active-low)
      // RED    = LED OFF (1)
      // GREEN  = LED blinks (~0.5 Hz)
      // YELLOW = LED ON (0)
      reg [23:0] blink_counter = 24'h0;

      always @(posedge clk) begin
          blink_counter <= blink_counter + 1'b1;
      end

      assign led = (state == RED)    ? 1'b1 :           // OFF
                   (state == YELLOW) ? 1'b0 :           // ON
                   (state == GREEN)  ? blink_counter[23] : // BLINK
                   1'b1;                               // default OFF



endmodule
