// ═══════════════════════════════════════════════════════════════════════════════
// uart_top v1.0.0 - FPGA Verilog from .vibee specification
// ═══════════════════════════════════════════════════════════════════════════════
//
// Golden Identity: φ² + 1/φ² = 3
//
// DO NOT EDIT - This file is auto-generated by VIBEE
//
// Target:   xilinx (50 MHz)
// ═══════════════════════════════════════════════════════════════════════════════

`timescale 1ns / 1ps

module uart_top (
input  wire clk,
input  wire rst,
input  wire uart_rx,
output  wire uart_tx,
output  wire led,
output  wire [3:0] debug_state
);

          // Clock divider: 50MHz / (16 * 115200) = 27.13 ≈ 27
      localparam CLK_DIV = 50_000_000 / (16 * 115200);

      // TX state machine
      localparam TX_IDLE  = 2'b00;
      localparam TX_START = 2'b01;
      localparam TX_DATA  = 2'b10;
      localparam TX_STOP  = 2'b11;

      reg [1:0] tx_state;
      reg [15:0] clk_div_counter;
      reg [3:0] bit_counter;
      reg [7:0] tx_shift_reg;
      reg tx_busy;
      reg tx_start;
      reg [7:0] tx_data;
      reg uart_tx_reg;

      wire tx_ready = !tx_busy;

      // TX state machine
      always @(posedge clk) begin
          if (rst) begin
              tx_state <= TX_IDLE;
              tx_busy <= 1'b0;
              uart_tx_reg <= 1'b1;
              bit_counter <= 4'b0;
              clk_div_counter <= 16'b0;
          end else begin
              case (tx_state)
                  TX_IDLE: begin
                      uart_tx_reg <= 1'b1;
                      if (tx_start) begin
                          tx_state <= TX_START;
                          tx_busy <= 1'b1;
                          tx_shift_reg <= tx_data;
                          bit_counter <= 4'b0;
                          clk_div_counter <= 16'b0;
                          tx_start <= 1'b0;
                      end
                  end

                  TX_START: begin
                      uart_tx_reg <= 1'b0;  // Start bit
                      if (clk_div_counter == CLK_DIV - 1) begin
                          clk_div_counter <= 16'b0;
                          tx_state <= TX_DATA;
                      end else begin
                          clk_div_counter <= clk_div_counter + 1'b1;
                      end
                  end

                  TX_DATA: begin
                      uart_tx_reg <= tx_shift_reg[0];
                      if (clk_div_counter == CLK_DIV - 1) begin
                          clk_div_counter <= 16'b0;
                          tx_shift_reg <= {1'b0, tx_shift_reg[7:1]};
                          if (bit_counter == 4'd7) begin
                              tx_state <= TX_STOP;
                          end else begin
                              bit_counter <= bit_counter + 1'b1;
                          end
                      end else begin
                          clk_div_counter <= clk_div_counter + 1'b1;
                      end
                  end

                  TX_STOP: begin
                      uart_tx_reg <= 1'b1;  // Stop bit
                      if (clk_div_counter == CLK_DIV - 1) begin
                          tx_state <= TX_IDLE;
                          tx_busy <= 1'b0;
                      end else begin
                          clk_div_counter <= clk_div_counter + 1'b1;
                      end
                  end
              endcase
          end
      end

      assign uart_tx = uart_tx_reg;



          // RX state machine
      localparam RX_IDLE  = 2'b00;
      localparam RX_START = 2'b01;
      localparam RX_DATA  = 2'b10;
      localparam RX_STOP  = 2'b11;

      reg [1:0] rx_state;
      reg [15:0] rx_clk_div;
      reg [3:0] rx_bit_counter;
      reg [7:0] rx_shift_reg;
      reg [3:0] rx_oversample;
      reg rx_busy;
      reg [7:0] rx_data;

      // RX state machine
      always @(posedge clk) begin
          if (rst) begin
              rx_state <= RX_IDLE;
              rx_busy <= 1'b0;
              rx_data <= 8'b0;
              rx_oversample <= 4'b0;
          end else begin
              case (rx_state)
                  RX_IDLE: begin
                      rx_busy <= 1'b0;
                      if (!uart_rx) begin  // Start bit detected
                          rx_state <= RX_START;
                          rx_busy <= 1'b1;
                          rx_clk_div <= 16'b0;
                          rx_oversample <= 4'b0;
                      end
                  end

                  RX_START: begin
                      if (rx_clk_div == CLK_DIV - 1) begin
                          rx_clk_div <= 16'b0;
                          if (rx_oversample == 4'd7) begin  // Sample at middle
                              if (!uart_rx) begin  // Validate start bit
                                  rx_state <= RX_DATA;
                                  rx_bit_counter <= 4'b0;
                              end else begin
                                  rx_state <= RX_IDLE;  // False start bit
                              end
                          end else begin
                              rx_oversample <= rx_oversample + 1'b1;
                          end
                      end else begin
                          rx_clk_div <= rx_clk_div + 1'b1;
                      end
                  end

                  RX_DATA: begin
                      if (rx_clk_div == CLK_DIV - 1) begin
                          rx_clk_div <= 16'b0;
                          if (rx_oversample == 4'd15) begin
                              rx_shift_reg <= {uart_rx, rx_shift_reg[7:1]};
                              if (rx_bit_counter == 4'd7) begin
                                  rx_state <= RX_STOP;
                              end else begin
                                  rx_bit_counter <= rx_bit_counter + 1'b1;
                              end
                              rx_oversample <= 4'b0;
                          end else begin
                              rx_oversample <= rx_oversample + 1'b1;
                          end
                      end else begin
                          rx_clk_div <= rx_clk_div + 1'b1;
                      end
                  end

                  RX_STOP: begin
                      if (rx_clk_div == CLK_DIV - 1) begin
                          rx_data <= rx_shift_reg;
                          rx_state <= RX_IDLE;
                      end else begin
                          rx_clk_div <= rx_clk_div + 1'b1;
                      end
                  end
              endcase
          end
      end



          // Frame parsing state machine
      localparam F_SYNC = 0;
      localparam F_CMD  = 1;
      localparam F_LEN  = 2;
      localparam F_DATA = 3;
      localparam F_CRC  = 4;

      reg [2:0] frame_state;
      reg [7:0] rx_cmd;
      reg [7:0] rx_len;
      reg [255:0] rx_data;
      reg [7:0] data_idx;
      reg [15:0] rx_crc_calc;
      reg [15:0] rx_crc_recv;

      // CRC-16/CCITT (from SSOT: protocol.crc16Ccitt)
      // Polynomial: 0x1021, Init: 0xFFFF
      function [15:0] crc16_ccitt;
          input [7:0] data;
          input [15:0] crc;
          reg [15:0] new_crc;
          integer i;
          begin
              new_crc = crc ^ {8'h00, data};
              for (i = 0; i < 8; i = i + 1) begin
                  if (new_crc[15]) begin
                      new_crc = (new_crc << 1) ^ 16'h1021;
                  end else begin
                      new_crc = new_crc << 1;
                  end
              end
              crc16_ccitt = new_crc;
          end
      endfunction

      always @(posedge clk) begin
          if (rst) begin
              frame_state <= F_SYNC;
          end else begin
              if (!rx_busy && tx_ready) begin
                  case (frame_state)
                      F_SYNC: begin
                          if (rx_data == SYNC_BYTE) begin
                              frame_state <= F_CMD;
                              rx_crc_calc <= 16'hFFFF;
                          end
                      end

                      F_CMD: begin
                          rx_cmd <= rx_data;
                          rx_crc_calc <= crc16_ccitt(rx_data, rx_crc_calc);
                          frame_state <= F_LEN;
                      end

                      F_LEN: begin
                          rx_len <= rx_data;
                          rx_crc_calc <= crc16_ccitt(rx_data, rx_crc_calc);
                          data_idx <= 8'b0;
                          if (rx_data == 8'b0) begin
                              frame_state <= F_CRC;
                          end else begin
                              frame_state <= F_DATA;
                          end
                      end

                      F_DATA: begin
                          rx_data[data_idx * 8 +: 8] <= rx_data;
                          rx_crc_calc <= crc16_ccitt(rx_data, rx_crc_calc);
                          data_idx <= data_idx + 1'b1;
                          if (data_idx == rx_len - 1) begin
                              frame_state <= F_CRC;
                          end
                      end

                      F_CRC: begin
                          // Validate CRC and execute command
                          rx_crc_recv <= {rx_data, rx_crc_recv[7:0]};
                          if (rx_crc_calc == rx_crc_recv) begin
                              // CRC valid - execute command
                              case (rx_cmd)
                                  MODE:      exec_mode(rx_data[0]);
                                  BIND:      exec_bind(rx_data[31:0]);
                                  BUNDLE:    exec_bundle(rx_data[31:0]);
                                  SIMILARITY: exec_similarity(rx_data[31:0]);
                                  PING:      exec_ping();
                                  default:   send_response(8'hFF); // Error
                              endcase
                          end
                          frame_state <= F_SYNC;
                      end
                  endcase
              end
          end
      end



          localparam RESP_PONG = 8'hAA;

      always @(posedge clk) begin
          if (exec_ping && tx_ready) begin
              tx_data <= RESP_PONG;
              tx_start <= 1'b1;
              exec_ping <= 1'b0;
          end
      end



          // LED modes (from SSOT: LedMode)
      localparam MODE_SEPARABLE  = 8'h00;  // |S| = 0
      localparam MODE_VIOLATION  = 8'h01;  // |S| = 2.4277 > 2.0
      localparam MODE_ZERO       = 8'h02;  // Zero vector
      localparam MODE_NEGATIVE   = 8'h03;  // Negative vector

      reg [1:0] led_mode;
      reg [23:0] blink_counter;
      wire blink_tick = (blink_counter == 24'd0);

      always @(posedge clk) begin
          if (rst) begin
              led_mode <= MODE_VIOLATION;
              blink_counter <= 24'd0;
          end else begin
              // Decrement blink counter
              if (blink_tick) begin
                  blink_counter <= 24'd16_777_215; // ~335ms at 50MHz
              end else begin
                  blink_counter <= blink_counter - 1'b1;
              end

              // Execute mode command
              if (exec_mode && tx_ready) begin
                  led_mode <= rx_data[1:0];
                  tx_data <= 8'h00; // OK
                  tx_start <= 1'b1;
                  exec_mode <= 1'b0;
              end
          end
      end

      // LED behavior based on mode
      assign led = (led_mode == MODE_SEPARABLE)  ? 1'b1 :  // OFF (|S| = 0)
                  (led_mode == MODE_VIOLATION)  ? blink_tick :  // Fast blink
                  (led_mode == MODE_ZERO)       ? 1'b0 :  // ON
                  (led_mode == MODE_NEGATIVE)   ? ~blink_tick :  // Slow blink
                  1'b0;  // Default ON



          // Trit multiplication table
      function [1:0] trit_multiply;
          input [1:0] a;
          input [1:0] b;
          begin
              if (a == 2'b00 || b == 2'b00)  // ZERO
                  trit_multiply = 2'b00;
              else if (a == b)                // POS × POS or NEG × NEG
                  trit_multiply = 2'b01;      // POSITIVE
              else                            // POS × NEG or NEG × POS
                  trit_multiply = 2'b10;      // NEGATIVE
          end
      endfunction

      reg [31:0] bind_result;
      integer i;

      always @(posedge clk) begin
          if (exec_bind && tx_ready) begin
              // Bind two 16-trit vectors (32 bits)
              for (i = 0; i < 16; i = i + 1) begin
                  bind_result[i*2 +: 2] = trit_multiply(
                      rx_data[i*2 +: 2],
                      rx_data[32 + i*2 +: 2]
                  );
              end

              // Send response (4 bytes)
              tx_data <= bind_result[7:0];
              tx_start <= 1'b1;
              exec_bind <= 1'b0;
          end
      end



          // Trit majority function (2 inputs)
      function [1:0] trit_majority2;
          input [1:0] a;
          input [1:0] b;
          begin
              if (a == 2'b10 && b == 2'b10)       // NEG, NEG
                  trit_majority2 = 2'b10;        // NEGATIVE
              else if (a == 2'b01 && b == 2'b01)  // POS, POS
                  trit_majority2 = 2'b01;        // POSITIVE
              else if (a == 2'b00)               // ZERO, x
                  trit_majority2 = b;            // Take non-zero
              else if (b == 2'b00)               // x, ZERO
                  trit_majority2 = a;            // Take non-zero
              else                               // POS, NEG
                  trit_majority2 = 2'b00;        // ZERO
          end
      endfunction

      reg [31:0] bundle_result;
      integer i;

      always @(posedge clk) begin
          if (exec_bundle && tx_ready) begin
              // Bundle two 16-trit vectors (32 bits)
              for (i = 0; i < 16; i = i + 1) begin
                  bundle_result[i*2 +: 2] = trit_majority2(
                      rx_data[i*2 +: 2],
                      rx_data[32 + i*2 +: 2]
                  );
              end

              // Send response (4 bytes)
              tx_data <= bundle_result[7:0];
              tx_start <= 1'b1;
              exec_bundle <= 1'b0;
          end
      end



          // Trit to signed value
      function signed [1:0] trit_value;
          input [1:0] t;
          begin
              case (t)
                  2'b10: trit_value = -2'sd1;  // NEGATIVE
                  2'b00: trit_value =  2'sd0;  // ZERO
                  2'b01: trit_value =  2'sd1;  // POSITIVE
              endcase
          end
      endfunction

      reg [7:0] similarity_score;
      signed [15:0] dot_product;
      signed [15:0] norm_a;
      signed [15:0] norm_b;
      signed [1:0] trit_a, trit_b;
      integer i;

      always @(posedge clk) begin
          if (exec_similarity && tx_ready) begin
              // Compute dot product and norms
              dot_product = 16'sd0;
              norm_a = 16'sd0;
              norm_b = 16'sd0;

              for (i = 0; i < 16; i = i + 1) begin
                  trit_a = trit_value(rx_data[i*2 +: 2]);
                  trit_b = trit_value(rx_data[32 + i*2 +: 2]);

                  dot_product = dot_product + (trit_a * trit_b);
                  norm_a = norm_a + (trit_a * trit_a);
                  norm_b = norm_b + (trit_b * trit_b);
              end

              // Calculate similarity score (0-255)
              if (norm_a == 0 || norm_b == 0) begin
                  similarity_score = 8'h00;
              end else begin
                  // similarity = |dot| / (norm_a + norm_b) × 255
                  similarity_score = (abs(dot_product) * 8'd255) / (norm_a + norm_b);
              end

              // Send response (1 byte)
              tx_data <= similarity_score;
              tx_start <= 1'b1;
              exec_similarity <= 1'b0;
          end
      end

      function signed [15:0] abs;
          input signed [15:0] val;
          begin
              abs = (val < 0) ? -val : val;
          end
      endfunction



          localparam RESP_OK = 8'h00;

      reg [7:0] response_data;
      reg send_response;

      always @(posedge clk) begin
          if (rst) begin
              send_response <= 1'b0;
          end else begin
              if (send_response && tx_ready) begin
                  // Build and send response frame
                  // For simplicity, just send data byte (no framing in this stub)
                  tx_data <= response_data;
                  tx_start <= 1'b1;
                  send_response <= 1'b0;
              end
          end
      end



          assign debug_state = {tx_busy, rx_busy, tx_state[1:0]};



endmodule
