FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:jonathonf/zig && \
    apt-get update && \
    apt-get install -y zig && \
    zig version

WORKDIR /src
CMD ["zig", "build", "tri"]
