# fly.toml app configuration file generated for trinity-api on 2026-03-06T20:01:12+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'trinity-api'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile.flyio'

[env]
  GRPC_PORT = '9335'
  LOG_LEVEL = 'info'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '5s'
    method = 'GET'
    path = '/api/health'

[[vm]]
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 2048
