// @origin manual

// ═══════════════════════════════════════════════════════════════════════════════
// EXPORT — Export to Kaggle-compatible formats
// ═══════════════════════════════════════════════════════════════════════════════
//
// Exports Zig evaluation results to Python-compatible format for Kaggle submission.
// One-way bridge: Zig does the work, Python is just a wrapper.
//
// φ² + 1/φ² = 3 = TRINITY
// ═══════════════════════════════════════════════════════════════════════════════

const std = @import("std");
const Allocator = std.mem.Allocator;

pub const ExportFormat = enum {
    Csv, // Standard CSV for Kaggle
    Json, // JSON for Python integration
    Python, // Python dict literal
};

pub const SubmissionRow = struct {
    id: []const u8,
    answer: []const u8,
};

pub const Exporter = struct {
    allocator: Allocator,

    pub fn init(allocator: Allocator) Exporter {
        return .{ .allocator = allocator };
    }

    /// Export submission to CSV format (Kaggle standard)
    pub fn exportCsv(self: *const Exporter, rows: []const SubmissionRow, output_path: []const u8) !void {
        _ = self;
        const file = try std.fs.cwd().createFile(output_path, .{});
        defer file.close();

        // Write header
        try file.writeAll("id,answer\n");

        // Write rows
        for (rows) |row| {
            // Escape if necessary
            const needs_escape = std.mem.indexOf(u8, row.answer, ",") != null or
                std.mem.indexOf(u8, row.answer, "\"") != null;

            if (needs_escape) {
                try file.writeAll(row.id);
                try file.writeAll(",\"");
                for (row.answer) |c| {
                    if (c == '"') {
                        try file.writeAll("\"\"");
                    } else {
                        try file.writer().writeByte(c);
                    }
                }
                try file.writeAll("\"\n");
            } else {
                try file.writer().print("{s},{s}\n", .{ row.id, row.answer });
            }
        }

        std.debug.print("Exported {d} rows to {s}\n", .{ rows.len, output_path });
    }

    /// Export to JSON for Python integration
    pub fn exportJson(self: *const Exporter, rows: []const SubmissionRow, output_path: []const u8) !void {
        _ = self;
        const file = try std.fs.cwd().createFile(output_path, .{});
        defer file.close();

        try file.writeAll("{\n");

        for (rows, 0..) |row, i| {
            try file.writer().print("  \"{s}\": \"{s}\"", .{ row.id, row.answer });
            if (i < rows.len - 1) {
                try file.writeAll(",\n");
            } else {
                try file.writeAll("\n");
            }
        }

        try file.writeAll("}\n");

        std.debug.print("Exported {d} rows to {s}\n", .{ rows.len, output_path });
    }

    /// Export to Python dict literal (for paste into notebook)
    pub fn exportPython(self: *const Exporter, rows: []const SubmissionRow, output_path: []const u8) !void {
        _ = self;
        const file = try std.fs.cwd().createFile(output_path, .{});
        defer file.close();

        try file.writeAll("# Trinity Kaggle Submission\n");
        try file.writeAll("# Generated by tri kaggle export\n");
        try file.writeAll("# Paste into submission notebook\n\n");
        try file.writeAll("submission = {\n");

        for (rows, 0..) |row, i| {
            try file.writer().print("    \"{s}\": \"{s}\"", .{ row.id, row.answer });
            if (i < rows.len - 1) {
                try file.writeAll(",\n");
            } else {
                try file.writeAll("\n");
            }
        }

        try file.writeAll("}\n");

        std.debug.print("Exported {d} rows to {s}\n", .{ rows.len, output_path });
    }

    /// Create Kaggle submission template
    pub fn createSubmissionTemplate(self: *Exporter, track: []const u8, output_path: []const u8) !void {
        _ = self;
        const file = try std.fs.cwd().createFile(output_path, .{});
        defer file.close();

        try file.writer().print(
            \\# Trinity Submission for {s} Track
            \\# Generated by tri kaggle export
            \\#
            \\# Usage:
            \\# 1. Run 'tri kaggle eval --track {s}' to generate results
            \\# 2. Copy the submission dict below
            \\# 3. Paste into your Kaggle notebook
            \\# 4. Submit!
            \\
            \\import pandas as pd
            \\import numpy as np
            \\from pathlib import Path
            \\
            \\# Load your evaluation results here
            \\# submission = {{}}
            \\
            \\# Create submission DataFrame
            \\df = pd.DataFrame([{
            \\    'id': k,
            \\    'answer': v
            \\}} for k, v in submission.items()])
            \\
            \\# Validate format
            \\assert 'id' in df.columns, "Missing 'id' column"
            \\assert 'answer' in df.columns, "Missing 'answer' column"
            \\assert len(df) > 0, "Empty submission"
            \\
            \\print(f"Submission ready: {{len(df)}} items")
            \\print(df.head())
            \\
            \\# Save for Kaggle upload
            \\df.to_csv('submission.csv', index=False)
            \\print("Saved to submission.csv")
        , .{ track, track });
    }
};

// ═══════════════════════════════════════════════════════════════════════════════
// BATCH EXPORTER — Export all tracks
// ═══════════════════════════════════════════════════════════════════════════════

pub const BatchExporter = struct {
    allocator: Allocator,
    output_dir: []const u8 = "kaggle/submissions",

    pub fn init(allocator: Allocator) BatchExporter {
        return .{
            .allocator = allocator,
        };
    }

    pub fn exportAll(self: *const BatchExporter, results: std.StringHashMap([]const SubmissionRow)) !void {
        // Create output directory
        std.fs.cwd().makePath(self.output_dir) catch {};

        var iter = results.iterator();
        while (iter.next()) |entry| {
            const track = entry.key_ptr.*;
            const rows = entry.value_ptr.*;

            const output_path = try std.fmt.allocPrint(self.allocator, "{s}/{s}_submission.csv", .{ self.output_dir, track });
            defer self.allocator.free(output_path);

            const exporter = Exporter.init(self.allocator);
            try exporter.exportCsv(rows, output_path);
        }
    }
};

// ═══════════════════════════════════════════════════════════════════════════════
// TESTS
// ═══════════════════════════════════════════════════════════════════════════════

test "export CSV" {
    const allocator = std.testing.allocator;
    const exporter = Exporter.init(allocator);

    const rows = [_]SubmissionRow{
        .{ .id = "test_001", .answer = "A" },
        .{ .id = "test_002", .answer = "B" },
    };

    const tmp_path = "test_export_temp.csv";
    {
        try exporter.exportCsv(&rows, tmp_path);
    }
    defer std.fs.cwd().deleteFile(tmp_path) catch {};

    // Verify output
    const content = try std.fs.cwd().readFileAlloc(allocator, tmp_path, 1024);
    defer allocator.free(content);

    try std.testing.expect(std.mem.indexOf(u8, content, "id,answer") != null);
    try std.testing.expect(std.mem.indexOf(u8, content, "test_001") != null);
}

test "export Python" {
    const allocator = std.testing.allocator;
    const exporter = Exporter.init(allocator);

    const rows = [_]SubmissionRow{
        .{ .id = "test_001", .answer = "Tashkent" },
    };

    const tmp_path = "test_python_export.py";
    {
        try exporter.exportPython(&rows, tmp_path);
    }
    defer std.fs.cwd().deleteFile(tmp_path) catch {};

    // Verify output
    const content = try std.fs.cwd().readFileAlloc(allocator, tmp_path, 1024);
    defer allocator.free(content);

    try std.testing.expect(std.mem.indexOf(u8, content, "submission = {") != null);
    try std.testing.expect(std.mem.indexOf(u8, content, "test_001") != null);
}
