//! COMPTIME SELF-MODIFICATION v8.18
//!
//! AGENT MU modifies its own pattern table at comptime.
//! High-confidence patterns (0.9+) become comptime constants.
//!
//! SAFETY: Only modifies if confidence > 0.9 AND sample_count > 10.
//! Generated code is written to a separate file for review before integration.

const std = @import("std");
const diagnostic = @import("diagnostic.zig");
const FixType = diagnostic.FixType;
const comptime_embeddings = @import("comptime_embeddings.zig");

const Allocator = std.mem.Allocator;
const ArrayListManaged = std.array_list.AlignedManaged;

/// Pending pattern awaiting self-modification
pub const PendingPattern = struct {
    template: []const u8,
    fix_type: FixType,
    confidence: f64,
    sample_count: usize,
    created_at: i64,
    embedding: [384]f64,

    /// Check if pattern meets safety threshold for self-modification
    pub fn meetsThreshold(self: *const PendingPattern, confidence_threshold: f64, min_samples: usize) bool {
        return self.confidence >= confidence_threshold and self.sample_count >= min_samples;
    }
};

/// Self-modification manager
pub const SelfModification = struct {
    pending_patterns: ArrayListManaged(PendingPattern, null),
    confidence_threshold: f64,
    min_sample_count: usize,
    output_path: []const u8,
    allocator: Allocator,
    modification_count: usize,

    /// Initialize self-modification manager
    pub fn init(allocator: Allocator, output_path: []const u8) !SelfModification {
        return SelfModification{
            .pending_patterns = ArrayListManaged(PendingPattern, null).init(allocator),
            .confidence_threshold = 0.9,
            .min_sample_count = 10,
            .output_path = try allocator.dupe(u8, output_path),
            .allocator = allocator,
            .modification_count = 0,
        };
    }

    /// Free allocated memory
    pub fn deinit(self: *SelfModification) void {
        for (self.pending_patterns.items) |*p| {
            self.allocator.free(p.template);
        }
        self.pending_patterns.deinit();
        self.allocator.free(self.output_path);
        self.* = undefined;
    }

    /// Propose new pattern for self-modification
    pub fn proposePattern(
        self: *SelfModification,
        template: []const u8,
        fix_type: FixType,
        confidence: f64,
        sample_count: usize,
    ) !bool {
        // Generate embedding at comptime for this pattern
        const embedding = comptime_embeddings.comptimeEmbedding(template);

        const pattern = PendingPattern{
            .template = try self.allocator.dupe(u8, template),
            .fix_type = fix_type,
            .confidence = confidence,
            .sample_count = sample_count,
            .created_at = std.time.timestamp(),
            .embedding = embedding,
        };

        try self.pending_patterns.append(pattern);

        // Return true if pattern meets threshold
        return pattern.meetsThreshold(self.confidence_threshold, self.min_sample_count);
    }

    /// Generate self-modification code (insert into comptime table)
    pub fn generateModCode(self: *const SelfModification) ![]const u8 {
        var buffer = ArrayListManaged(u8, null).init(self.allocator);
        defer buffer.deinit();

        try buffer.appendSlice(
            \\//! AUTO-GENERATED PATTERNS - AGENT MU SELF-MODIFICATION
            \\//! This file is generated by AGENT MU based on learned patterns
            \\//! Review before integrating into comptime_embeddings.zig
            \\
            \\const std = @import("std");
            \\const diagnostic = @import("diagnostic.zig");
            \\const FixType = diagnostic.FixType;
            \\
        );

        try buffer.appendSlice("// Self-generated patterns learned from runtime\n");
        try buffer.appendSlice("// Generated at: ");
        try buffer.print("{d}", .{std.time.timestamp()});
        try buffer.appendSlice("\n\n");

        try buffer.appendSlice("pub const SELF_GENERATED_PATTERNS = [_]comptime_embeddings.ErrorPattern{\n");

        for (self.pending_patterns.items) |pattern| {
            if (pattern.meetsThreshold(self.confidence_threshold, self.min_sample_count)) {
                try buffer.appendSlice("    .{\n");
                try buffer.appendSlice("        .template = \"");

                // Escape template string
                for (pattern.template) |c| {
                    switch (c) {
                        '\\' => try buffer.appendSlice("\\\\"),
                        '"' => try buffer.appendSlice("\\\""),
                        '\n' => try buffer.appendSlice("\\n"),
                        '\r' => try buffer.appendSlice("\\r"),
                        '\t' => try buffer.appendSlice("\\t"),
                        else => try buffer.append(c),
                    }
                }

                try buffer.print("\",\n        .fix_type = .{s},\n", .{@tagName(pattern.fix_type)});
                try buffer.print("        .embedding = comptime comptime_embeddings.comptimeEmbedding(\"{s}\"),\n", .{pattern.template});
                try buffer.print("        .confidence = {d:.2},\n", .{pattern.confidence});
                try buffer.print("        .sample_count = {d},\n", .{pattern.sample_count});
                try buffer.appendSlice("    },\n");
            }
        }

        try buffer.appendSlice("};\n");

        return self.allocator.dupe(u8, buffer.items);
    }

    /// Apply modification (write to output file)
    pub fn applyModification(self: *const SelfModification) !bool {
        const code = try self.generateModCode();
        defer self.allocator.free(code);

        // Write to output file
        const file = try std.fs.createFileAbsolute(self.output_path, .{ .read = true });
        defer file.close();

        try file.writeAll(code);

        return true;
    }

    /// Get count of patterns ready for self-modification
    pub fn readyCount(self: *const SelfModification) usize {
        var count: usize = 0;
        for (self.pending_patterns.items) |pattern| {
            if (pattern.meetsThreshold(self.confidence_threshold, self.min_sample_count)) {
                count += 1;
            }
        }
        return count;
    }

    /// Get summary of pending patterns
    pub fn getSummary(self: *const SelfModification, allocator: Allocator) ![][]const u8 {
        var lines = ArrayListManaged([]const u8).init(allocator);

        try lines.append(try allocator.dupe(u8,
            \\# SELF-MODIFICATION SUMMARY
            \\| Template | FixType | Confidence | Samples | Ready |
            \\|----------|---------|------------|--------|-------|
        ));

        for (self.pending_patterns.items) |pattern| {
            const ready = pattern.meetsThreshold(self.confidence_threshold, self.min_sample_count);
            const ready_str = if (ready) "YES" else "no";

            const line = try std.fmt.allocPrint(allocator,
                "| \"{s}\" | {s} | {d:.2} | {d} | {s} |\n",
                .{
                    pattern.template[0..@min(50, pattern.template.len)],
                    @tagName(pattern.fix_type),
                    pattern.confidence,
                    pattern.sample_count,
                    ready_str,
                },
            );
            try lines.append(line);
        }

        return lines.toOwnedSlice();
    }

    /// Prune old low-confidence patterns
    pub fn pruneLowConfidence(self: *SelfModification, max_age_seconds: i64) !usize {
        const now = std.time.timestamp();
        var pruned: usize = 0;

        var i: usize = 0;
        while (i < self.pending_patterns.items.len) {
            const pattern = &self.pending_patterns.items[i];
            const age = now - pattern.created_at;

            // Prune if old and below threshold
            if (age > max_age_seconds and !pattern.meetsThreshold(self.confidence_threshold, self.min_sample_count)) {
                self.allocator.free(pattern.template);
                _ = self.pending_patterns.orderedRemove(i);
                pruned += 1;
            } else {
                i += 1;
            }
        }

        return pruned;
    }

    /// Merge pattern with existing (increase confidence/sample count)
    pub fn mergePattern(
        self: *SelfModification,
        template: []const u8,
        fix_type: FixType,
        additional_confidence: f64,
        additional_samples: usize,
    ) !bool {
        // Look for existing pattern with same template
        for (self.pending_patterns.items) |*pattern| {
            if (std.mem.eql(u8, pattern.template, template) and pattern.fix_type == fix_type) {
                // Weighted average of confidences based on sample count
                const total_samples = pattern.sample_count + additional_samples;
                pattern.confidence = (pattern.confidence * @as(f64, @floatFromInt(pattern.sample_count)) +
                    additional_confidence * @as(f64, @floatFromInt(additional_samples))) /
                    @as(f64, @floatFromInt(total_samples));
                pattern.sample_count = total_samples;
                return pattern.meetsThreshold(self.confidence_threshold, self.min_sample_count);
            }
        }

        // Not found, add as new
        return self.proposePattern(template, fix_type, additional_confidence, additional_samples);
    }

    /// Export patterns for manual review
    pub fn exportForReview(self: *const SelfModification, path: []const u8) !void {
        const file = try std.fs.createFileAbsolute(path, .{ .read = true });
        defer file.close();

        const writer = file.writer();

        try writer.writeAll(
            \\# AGENT MU Self-Modification Patterns
            \\# Review these patterns before integration
            \\# Format: template | fix_type | confidence | samples | ready
            \\
        );

        for (self.pending_patterns.items) |pattern| {
            const ready = pattern.meetsThreshold(self.confidence_threshold, self.min_sample_count);
            try writer.print(
                "{s} | {s} | {d:.4} | {d} | {}\n",
                .{ pattern.template, @tagName(pattern.fix_type), pattern.confidence, pattern.sample_count, ready },
            );
        }
    }
};

/// Test pattern generation
pub const TestPattern = struct {
    template: []const u8,
    fix_type: FixType,
    expected_embedding_dim: usize = 384,
};

/// Generate test patterns for self-modification testing
pub fn generateTestPatterns(allocator: Allocator) ![]const TestPattern {
    const patterns = [_]TestPattern{
        .{ .template = "expected '<expr>' before", .fix_type = .SYNTAX_FIX },
        .{ .template = "no member named 'allocator' in struct", .fix_type = .ALLOCATOR_FIX },
        .{ .template = "use of undeclared identifier 'std'", .fix_type = .IMPORT_FIX },
        .{ .template = "type mismatch: expected 'T', found '?'", .fix_type = .TYPE_FIX },
        .{ .template = "@Type invalid field 'is_comptime'", .fix_type = .TYPEFUNCTION_FIX },
    };

    var result = try allocator.alloc(TestPattern, patterns.len);
    for (patterns, 0..) |p, i| {
        result[i] = .{
            .template = try allocator.dupe(u8, p.template),
            .fix_type = p.fix_type,
            .expected_embedding_dim = p.expected_embedding_dim,
        };
    }

    return result;
}

/// Global self-modification instance
var global_self_mod: ?SelfModification = null;
var global_self_mod_init = false;

/// Get or create global self-modification manager
pub fn getGlobalSelfMod() !*SelfModification {
    if (!global_self_mod_init) {
        global_self_mod = try SelfModification.init(
            std.heap.page_allocator,
            "/tmp/agent_mu_self_generated.zig",
        );
        global_self_mod_init = true;
    }
    return &global_self_mod.?;
}

// ═══════════════════════════════════════════════════════════════════════════════
// Tests
// ═══════════════════════════════════════════════════════════════════════════════

test "PendingPattern: meets threshold" {
    const pattern = PendingPattern{
        .template = "test pattern",
        .fix_type = .SYNTAX_FIX,
        .confidence = 0.95,
        .sample_count = 15,
        .created_at = 0,
        .embedding = undefined,
    };

    try std.testing.expect(pattern.meetsThreshold(0.9, 10));
}

test "PendingPattern: below threshold" {
    const pattern = PendingPattern{
        .template = "test pattern",
        .fix_type = .SYNTAX_FIX,
        .confidence = 0.5,
        .sample_count = 5,
        .created_at = 0,
        .embedding = undefined,
    };

    try std.testing.expect(!pattern.meetsThreshold(0.9, 10));
}

test "SelfModification: initialization" {
    const allocator = std.testing.allocator;
    var sm = try SelfModification.init(allocator, "/tmp/test.zig");
    defer sm.deinit();

    try std.testing.expectEqual(@as(f64, 0.9), sm.confidence_threshold);
    try std.testing.expectEqual(@as(usize, 10), sm.min_sample_count);
}

test "SelfModification: propose pattern below threshold" {
    const allocator = std.testing.allocator;
    var sm = try SelfModification.init(allocator, "/tmp/test.zig");
    defer sm.deinit();

    const ready = try sm.proposePattern("test pattern", .SYNTAX_FIX, 0.5, 5);

    try std.testing.expect(!ready); // Below threshold
    try std.testing.expectEqual(@as(usize, 1), sm.pending_patterns.items.len);
}

test "SelfModification: propose pattern above threshold" {
    const allocator = std.testing.allocator;
    var sm = try SelfModification.init(allocator, "/tmp/test.zig");
    defer sm.deinit();

    const ready = try sm.proposePattern("high conf pattern", .TYPE_FIX, 0.95, 15);

    try std.testing.expect(ready); // Above threshold
    try std.testing.expectEqual(@as(usize, 1), sm.pending_patterns.items.len);
}

test "SelfModification: ready count" {
    const allocator = std.testing.allocator;
    var sm = try SelfModification.init(allocator, "/tmp/test.zig");
    defer sm.deinit();

    _ = try sm.proposePattern("low conf", .SYNTAX_FIX, 0.5, 5);
    _ = try sm.proposePattern("high conf", .TYPE_FIX, 0.95, 15);

    try std.testing.expectEqual(@as(usize, 1), sm.readyCount());
}

test "SelfModification: merge pattern" {
    const allocator = std.testing.allocator;
    var sm = try SelfModification.init(allocator, "/tmp/test.zig");
    defer sm.deinit();

    // Add initial pattern
    _ = try sm.proposePattern("merge test", .TYPE_FIX, 0.8, 10);

    // Merge with additional samples
    _ = try sm.mergePattern("merge test", .TYPE_FIX, 0.9, 10);

    // Should have 20 total samples, blended confidence
    try std.testing.expectEqual(@as(usize, 1), sm.pending_patterns.items.len);
    try std.testing.expectEqual(@as(usize, 20), sm.pending_patterns.items[0].sample_count);
}

test "SelfModification: generate mod code" {
    const allocator = std.testing.allocator;
    var sm = try SelfModification.init(allocator, "/tmp/test.zig");
    defer sm.deinit();

    _ = try sm.proposePattern("expected ';'", .SYNTAX_FIX, 0.95, 15);

    const code = try sm.generateModCode();
    defer allocator.free(code);

    try std.testing.expect(std.mem.indexOf(u8, code, "AUTO-GENERATED PATTERNS") != null);
    try std.testing.expect(std.mem.indexOf(u8, code, "expected ';'") != null);
}

test "generateTestPatterns" {
    const allocator = std.testing.allocator;
    const patterns = try generateTestPatterns(allocator);
    defer {
        for (patterns) |p| allocator.free(p.template);
        allocator.free(patterns);
    }

    try std.testing.expectEqual(@as(usize, 5), patterns.len);
}
