// ═══════════════════════════════════════════════════════════════════════════════
// STRUCT EMITTERS — Infrastructure struct code generation
// ═══════════════════════════════════════════════════════════════════════════════
//
// φ² + 1/φ² = 3
//
// ═══════════════════════════════════════════════════════════════════════════════

const builder_mod = @import("builder.zig");
const CodeBuilder = builder_mod.CodeBuilder;

/// Emit ShardNetwork struct (TCP Transfer Protocol)
pub fn emitShardNetwork(builder: *CodeBuilder) !void {
    try builder.writeLine("");
    try builder.writeLine("// ═══════════════════════════════════════════════════════════════════");
    try builder.writeLine("// SHARD NETWORK — TCP Transfer Protocol (generated from .vibee)");
    try builder.writeLine("// Wire protocol: [64 bytes hex hash][4 bytes data len LE u32][data]");
    try builder.writeLine("// ═══════════════════════════════════════════════════════════════════");
    try builder.writeLine("");
    try builder.writeLine("pub const ShardNetwork = struct {");
    try builder.writeLine("    root_buf: [256]u8,");
    try builder.writeLine("    root_len: usize,");
    try builder.writeLine("    port: u16,");
    try builder.writeLine("");
    try builder.writeLine("    const hex_chars = \"0123456789abcdef\";");
    try builder.writeLine("");
    try builder.writeLine("    /// Create network node with storage directories");
    try builder.writeLine("    pub fn init(root: []const u8, port: u16) !ShardNetwork {");
    try builder.writeLine("        var node = ShardNetwork{");
    try builder.writeLine("            .root_buf = undefined,");
    try builder.writeLine("            .root_len = root.len,");
    try builder.writeLine("            .port = port,");
    try builder.writeLine("        };");
    try builder.writeLine("        @memcpy(node.root_buf[0..root.len], root);");
    try builder.writeLine("        std.fs.makeDirAbsolute(root) catch |e| switch (e) {");
    try builder.writeLine("            error.PathAlreadyExists => {},");
    try builder.writeLine("            else => return e,");
    try builder.writeLine("        };");
    try builder.writeLine("        var sbuf: [280]u8 = undefined;");
    try builder.writeLine("        const sdir = std.fmt.bufPrint(&sbuf, \"{s}/shards\", .{root}) catch unreachable;");
    try builder.writeLine("        std.fs.makeDirAbsolute(sdir) catch |e| switch (e) {");
    try builder.writeLine("            error.PathAlreadyExists => {},");
    try builder.writeLine("            else => return e,");
    try builder.writeLine("        };");
    try builder.writeLine("        return node;");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    fn rootPath(self: *const ShardNetwork) []const u8 {");
    try builder.writeLine("        return self.root_buf[0..self.root_len];");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    fn hashToHex(hash: [32]u8) [64]u8 {");
    try builder.writeLine("        var result: [64]u8 = undefined;");
    try builder.writeLine("        for (hash, 0..) |byte, i| {");
    try builder.writeLine("            result[i * 2] = hex_chars[byte >> 4];");
    try builder.writeLine("            result[i * 2 + 1] = hex_chars[byte & 0x0F];");
    try builder.writeLine("        }");
    try builder.writeLine("        return result;");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    /// Bind TCP listener on port (use port 0 for OS-assigned)");
    try builder.writeLine("    pub fn listen(self: *const ShardNetwork) !std.net.Server {");
    try builder.writeLine("        const addr = std.net.Address.initIp4([4]u8{ 127, 0, 0, 1 }, self.port);");
    try builder.writeLine("        return addr.listen(.{ .reuse_address = true });");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    /// Accept one connection, read protocol, store shard to disk");
    try builder.writeLine("    pub fn receiveOne(self: *const ShardNetwork, server: *std.net.Server) !void {");
    try builder.writeLine("        const conn = try server.accept();");
    try builder.writeLine("        defer conn.stream.close();");
    try builder.writeLine("        var hash_buf: [64]u8 = undefined;");
    try builder.writeLine("        const hn = try conn.stream.readAtLeast(&hash_buf, 64);");
    try builder.writeLine("        if (hn != 64) return error.ProtocolError;");
    try builder.writeLine("        var len_buf: [4]u8 = undefined;");
    try builder.writeLine("        const ln = try conn.stream.readAtLeast(&len_buf, 4);");
    try builder.writeLine("        if (ln != 4) return error.ProtocolError;");
    try builder.writeLine("        const data_len = std.mem.readInt(u32, &len_buf, .little);");
    try builder.writeLine("        var data_buf: [8192]u8 = undefined;");
    try builder.writeLine("        const dn = try conn.stream.readAtLeast(data_buf[0..data_len], data_len);");
    try builder.writeLine("        if (dn != data_len) return error.ProtocolError;");
    try builder.writeLine("        var pbuf: [350]u8 = undefined;");
    try builder.writeLine("        const spath = std.fmt.bufPrint(&pbuf, \"{s}/shards/{s}.shard\", .{ self.rootPath(), hash_buf }) catch unreachable;");
    try builder.writeLine("        const file = try std.fs.createFileAbsolute(spath, .{});");
    try builder.writeLine("        defer file.close();");
    try builder.writeLine("        try file.writeAll(data_buf[0..dn]);");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    /// Connect to peer and send shard via TCP wire protocol");
    try builder.writeLine("    pub fn sendShard(_: *const ShardNetwork, peer_port: u16, hex: *const [64]u8, data: []const u8) !void {");
    try builder.writeLine("        const addr = std.net.Address.initIp4([4]u8{ 127, 0, 0, 1 }, peer_port);");
    try builder.writeLine("        const stream = try std.net.tcpConnectToAddress(addr);");
    try builder.writeLine("        defer stream.close();");
    try builder.writeLine("        stream.writeAll(hex) catch return error.SendFailed;");
    try builder.writeLine("        var len_buf: [4]u8 = undefined;");
    try builder.writeLine("        std.mem.writeInt(u32, &len_buf, @intCast(data.len), .little);");
    try builder.writeLine("        stream.writeAll(&len_buf) catch return error.SendFailed;");
    try builder.writeLine("        stream.writeAll(data) catch return error.SendFailed;");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    /// Remove all storage (for testing)");
    try builder.writeLine("    pub fn cleanup(self: *const ShardNetwork) void {");
    try builder.writeLine("        std.fs.deleteTreeAbsolute(self.rootPath()) catch {};");
    try builder.writeLine("    }");
    try builder.writeLine("};");
    try builder.writeLine("");
}

/// Emit ReedSolomon struct (GF(2^8) Erasure Coding)
pub fn emitReedSolomon(builder: *CodeBuilder) !void {
    try builder.writeLine("");
    try builder.writeLine("// ═══════════════════════════════════════════════════════════════════");
    try builder.writeLine("// REED-SOLOMON ERASURE CODING — GF(2^8) Fault Tolerance");
    try builder.writeLine("// Primitive polynomial: x^8 + x^4 + x^3 + x^2 + 1 (0x11D)");
    try builder.writeLine("// Vandermonde matrix encoding, Gaussian elimination decoding.");
    try builder.writeLine("// ═══════════════════════════════════════════════════════════════════");
    try builder.writeLine("");
    try builder.writeLine("pub const ReedSolomon = struct {");
    try builder.writeLine("    data_shards: u8,");
    try builder.writeLine("    total_shards: u8,");
    try builder.writeLine("");
    try builder.writeLine("    pub fn init(k: u8, m: u8) ReedSolomon {");
    try builder.writeLine("        return .{ .data_shards = k, .total_shards = k + m };");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    /// GF(2^8) multiply via Russian peasant algorithm");
    try builder.writeLine("    pub fn gfMul(a_in: u8, b_in: u8) u8 {");
    try builder.writeLine("        if (a_in == 0 or b_in == 0) return 0;");
    try builder.writeLine("        var a: u16 = a_in;");
    try builder.writeLine("        var b: u8 = b_in;");
    try builder.writeLine("        var p: u8 = 0;");
    try builder.writeLine("        var i: u8 = 0;");
    try builder.writeLine("        while (i < 8) : (i += 1) {");
    try builder.writeLine("            if (b & 1 != 0) p ^= @intCast(a & 0xFF);");
    try builder.writeLine("            a <<= 1;");
    try builder.writeLine("            if (a & 0x100 != 0) a ^= 0x11D;");
    try builder.writeLine("            b >>= 1;");
    try builder.writeLine("        }");
    try builder.writeLine("        return p;");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    /// GF(2^8) exponentiation via repeated squaring");
    try builder.writeLine("    pub fn gfPow(base: u8, exp: u8) u8 {");
    try builder.writeLine("        if (exp == 0) return 1;");
    try builder.writeLine("        if (base == 0) return 0;");
    try builder.writeLine("        var result: u8 = 1;");
    try builder.writeLine("        var b: u8 = base;");
    try builder.writeLine("        var e: u8 = exp;");
    try builder.writeLine("        while (e > 0) {");
    try builder.writeLine("            if (e & 1 != 0) result = gfMul(result, b);");
    try builder.writeLine("            b = gfMul(b, b);");
    try builder.writeLine("            e >>= 1;");
    try builder.writeLine("        }");
    try builder.writeLine("        return result;");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    /// GF(2^8) inverse: a^(-1) = a^254 (Fermat's little theorem)");
    try builder.writeLine("    pub fn gfInv(a: u8) u8 {");
    try builder.writeLine("        if (a == 0) return 0;");
    try builder.writeLine("        return gfPow(a, 254);");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    /// Encode one byte position: k input bytes → n coded bytes (Vandermonde)");
    try builder.writeLine("    pub fn encodeByte(self: *const ReedSolomon, input: []const u8, output: []u8) void {");
    try builder.writeLine("        var i: u8 = 0;");
    try builder.writeLine("        while (i < self.total_shards) : (i += 1) {");
    try builder.writeLine("            var val: u8 = 0;");
    try builder.writeLine("            var j: u8 = 0;");
    try builder.writeLine("            while (j < self.data_shards) : (j += 1) {");
    try builder.writeLine("                const coeff = gfPow(i + 1, j);");
    try builder.writeLine("                val ^= gfMul(coeff, input[j]);");
    try builder.writeLine("            }");
    try builder.writeLine("            output[i] = val;");
    try builder.writeLine("        }");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    /// Decode one byte position: any k of n coded bytes → k original bytes");
    try builder.writeLine("    /// avail = k available bytes, indices = their shard indices (0-based)");
    try builder.writeLine("    pub fn decodeByte(self: *const ReedSolomon, avail: []const u8, indices: []const u8, output: []u8) !void {");
    try builder.writeLine("        const k = self.data_shards;");
    try builder.writeLine("        var mat: [8][8]u8 = undefined;");
    try builder.writeLine("        var aug: [8][8]u8 = undefined;");
    try builder.writeLine("        var r: usize = 0;");
    try builder.writeLine("        while (r < k) : (r += 1) {");
    try builder.writeLine("            var c: usize = 0;");
    try builder.writeLine("            while (c < k) : (c += 1) {");
    try builder.writeLine("                mat[r][c] = gfPow(indices[r] + 1, @intCast(c));");
    try builder.writeLine("                aug[r][c] = if (r == c) 1 else 0;");
    try builder.writeLine("            }");
    try builder.writeLine("        }");
    try builder.writeLine("        var col: usize = 0;");
    try builder.writeLine("        while (col < k) : (col += 1) {");
    try builder.writeLine("            if (mat[col][col] == 0) {");
    try builder.writeLine("                var sr: usize = col + 1;");
    try builder.writeLine("                while (sr < k) : (sr += 1) {");
    try builder.writeLine("                    if (mat[sr][col] != 0) {");
    try builder.writeLine("                        var sc: usize = 0;");
    try builder.writeLine("                        while (sc < k) : (sc += 1) {");
    try builder.writeLine("                            const tmp1 = mat[col][sc]; mat[col][sc] = mat[sr][sc]; mat[sr][sc] = tmp1;");
    try builder.writeLine("                            const tmp2 = aug[col][sc]; aug[col][sc] = aug[sr][sc]; aug[sr][sc] = tmp2;");
    try builder.writeLine("                        }");
    try builder.writeLine("                        break;");
    try builder.writeLine("                    }");
    try builder.writeLine("                }");
    try builder.writeLine("            }");
    try builder.writeLine("            const piv_inv = gfInv(mat[col][col]);");
    try builder.writeLine("            var sc2: usize = 0;");
    try builder.writeLine("            while (sc2 < k) : (sc2 += 1) {");
    try builder.writeLine("                mat[col][sc2] = gfMul(mat[col][sc2], piv_inv);");
    try builder.writeLine("                aug[col][sc2] = gfMul(aug[col][sc2], piv_inv);");
    try builder.writeLine("            }");
    try builder.writeLine("            var er: usize = 0;");
    try builder.writeLine("            while (er < k) : (er += 1) {");
    try builder.writeLine("                if (er == col) { er += 0; } else {");
    try builder.writeLine("                    const factor = mat[er][col];");
    try builder.writeLine("                    if (factor != 0) {");
    try builder.writeLine("                        var ec: usize = 0;");
    try builder.writeLine("                        while (ec < k) : (ec += 1) {");
    try builder.writeLine("                            mat[er][ec] ^= gfMul(factor, mat[col][ec]);");
    try builder.writeLine("                            aug[er][ec] ^= gfMul(factor, aug[col][ec]);");
    try builder.writeLine("                        }");
    try builder.writeLine("                    }");
    try builder.writeLine("                }");
    try builder.writeLine("            }");
    try builder.writeLine("        }");
    try builder.writeLine("        var oi: usize = 0;");
    try builder.writeLine("        while (oi < k) : (oi += 1) {");
    try builder.writeLine("            var val: u8 = 0;");
    try builder.writeLine("            var oj: usize = 0;");
    try builder.writeLine("            while (oj < k) : (oj += 1) {");
    try builder.writeLine("                val ^= gfMul(aug[oi][oj], avail[oj]);");
    try builder.writeLine("            }");
    try builder.writeLine("            output[oi] = val;");
    try builder.writeLine("        }");
    try builder.writeLine("    }");
    try builder.writeLine("};");
    try builder.writeLine("");
}

/// Emit PeerRegistry + ShardManifest structs
pub fn emitDiscovery(builder: *CodeBuilder) !void {
    try builder.writeLine("");
    try builder.writeLine("// ═══════════════════════════════════════════════════════════════════");
    try builder.writeLine("// PEER DISCOVERY + SELF-HEALING — Dynamic Swarm Recovery");
    try builder.writeLine("// PeerRegistry: in-memory peer table with alive/dead status.");
    try builder.writeLine("// ShardManifest: maps data groups → (shard_index, peer_id) pairs.");
    try builder.writeLine("// ═══════════════════════════════════════════════════════════════════");
    try builder.writeLine("");
    try builder.writeLine("pub const PeerRegistry = struct {");
    try builder.writeLine("    const MAX_PEERS = 8;");
    try builder.writeLine("");
    try builder.writeLine("    ports: [MAX_PEERS]u16,");
    try builder.writeLine("    alive: [MAX_PEERS]bool,");
    try builder.writeLine("    shard_counts: [MAX_PEERS]u16,");
    try builder.writeLine("    count: u8,");
    try builder.writeLine("");
    try builder.writeLine("    pub fn init() PeerRegistry {");
    try builder.writeLine("        return .{");
    try builder.writeLine("            .ports = [_]u16{0} ** MAX_PEERS,");
    try builder.writeLine("            .alive = [_]bool{false} ** MAX_PEERS,");
    try builder.writeLine("            .shard_counts = [_]u16{0} ** MAX_PEERS,");
    try builder.writeLine("            .count = 0,");
    try builder.writeLine("        };");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    /// Register a new peer, returns peer_id (index)");
    try builder.writeLine("    pub fn registerPeer(self: *PeerRegistry, port: u16) !u8 {");
    try builder.writeLine("        if (self.count >= MAX_PEERS) return error.RegistryFull;");
    try builder.writeLine("        const id = self.count;");
    try builder.writeLine("        self.ports[id] = port;");
    try builder.writeLine("        self.alive[id] = true;");
    try builder.writeLine("        self.shard_counts[id] = 0;");
    try builder.writeLine("        self.count += 1;");
    try builder.writeLine("        return id;");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    /// Mark a peer as dead (failed)");
    try builder.writeLine("    pub fn markDead(self: *PeerRegistry, peer_id: u8) void {");
    try builder.writeLine("        if (peer_id < self.count) self.alive[peer_id] = false;");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    /// Check if peer is alive");
    try builder.writeLine("    pub fn isAlive(self: *const PeerRegistry, peer_id: u8) bool {");
    try builder.writeLine("        if (peer_id >= self.count) return false;");
    try builder.writeLine("        return self.alive[peer_id];");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    /// Count alive peers");
    try builder.writeLine("    pub fn alivePeers(self: *const PeerRegistry) u8 {");
    try builder.writeLine("        var c: u8 = 0;");
    try builder.writeLine("        var i: u8 = 0;");
    try builder.writeLine("        while (i < self.count) : (i += 1) {");
    try builder.writeLine("            if (self.alive[i]) c += 1;");
    try builder.writeLine("        }");
    try builder.writeLine("        return c;");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    /// Get port for a peer");
    try builder.writeLine("    pub fn getPort(self: *const PeerRegistry, peer_id: u8) u16 {");
    try builder.writeLine("        return self.ports[peer_id];");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    /// Increment shard count for a peer");
    try builder.writeLine("    pub fn incShards(self: *PeerRegistry, peer_id: u8) void {");
    try builder.writeLine("        if (peer_id < self.count) self.shard_counts[peer_id] += 1;");
    try builder.writeLine("    }");
    try builder.writeLine("};");
    try builder.writeLine("");
    try builder.writeLine("pub const ShardManifest = struct {");
    try builder.writeLine("    const MAX_GROUPS = 16;");
    try builder.writeLine("    const MAX_ENTRIES = 8;");
    try builder.writeLine("");
    try builder.writeLine("    /// Each entry: (shard_index, peer_id)");
    try builder.writeLine("    shard_idx: [MAX_GROUPS][MAX_ENTRIES]u8,");
    try builder.writeLine("    peer_ids: [MAX_GROUPS][MAX_ENTRIES]u8,");
    try builder.writeLine("    entry_counts: [MAX_GROUPS]u8,");
    try builder.writeLine("    group_count: u8,");
    try builder.writeLine("");
    try builder.writeLine("    pub fn init() ShardManifest {");
    try builder.writeLine("        return .{");
    try builder.writeLine("            .shard_idx = [_][MAX_ENTRIES]u8{[_]u8{0} ** MAX_ENTRIES} ** MAX_GROUPS,");
    try builder.writeLine("            .peer_ids = [_][MAX_ENTRIES]u8{[_]u8{0} ** MAX_ENTRIES} ** MAX_GROUPS,");
    try builder.writeLine("            .entry_counts = [_]u8{0} ** MAX_GROUPS,");
    try builder.writeLine("            .group_count = 0,");
    try builder.writeLine("        };");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    /// Record that shard_index of data group is held by peer_id");
    try builder.writeLine("    pub fn recordShard(self: *ShardManifest, group: u8, shard_index: u8, peer_id: u8) void {");
    try builder.writeLine("        if (group >= MAX_GROUPS) return;");
    try builder.writeLine("        const ec = self.entry_counts[group];");
    try builder.writeLine("        if (ec >= MAX_ENTRIES) return;");
    try builder.writeLine("        self.shard_idx[group][ec] = shard_index;");
    try builder.writeLine("        self.peer_ids[group][ec] = peer_id;");
    try builder.writeLine("        self.entry_counts[group] = ec + 1;");
    try builder.writeLine("        if (group >= self.group_count) self.group_count = group + 1;");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    /// Query surviving shards for a group: returns count of alive entries");
    try builder.writeLine("    /// Writes surviving shard indices to out_shard_idx and peer ids to out_peer_ids");
    try builder.writeLine("    pub fn survivorsForGroup(self: *const ShardManifest, group: u8, registry: *const PeerRegistry, out_shard_idx: []u8, out_peer_ids: []u8) u8 {");
    try builder.writeLine("        if (group >= MAX_GROUPS) return 0;");
    try builder.writeLine("        var sc: u8 = 0;");
    try builder.writeLine("        var i: u8 = 0;");
    try builder.writeLine("        while (i < self.entry_counts[group]) : (i += 1) {");
    try builder.writeLine("            if (registry.isAlive(self.peer_ids[group][i])) {");
    try builder.writeLine("                if (sc < out_shard_idx.len) {");
    try builder.writeLine("                    out_shard_idx[sc] = self.shard_idx[group][i];");
    try builder.writeLine("                    out_peer_ids[sc] = self.peer_ids[group][i];");
    try builder.writeLine("                    sc += 1;");
    try builder.writeLine("                }");
    try builder.writeLine("            }");
    try builder.writeLine("        }");
    try builder.writeLine("        return sc;");
    try builder.writeLine("    }");
    try builder.writeLine("};");
    try builder.writeLine("");
}

/// Emit ProofOfStorageEngine struct
pub fn emitProofOfStorage(builder: *CodeBuilder) !void {
    try builder.writeLine("");
    try builder.writeLine("// ═══════════════════════════════════════════════════════════════════");
    try builder.writeLine("// PROOF OF STORAGE — Cryptographic Challenge-Response Verification");
    try builder.writeLine("// Challenger picks random byte range, node proves possession via SHA-256.");
    try builder.writeLine("// Failures tracked per-node; exceeding max_failures → deactivation.");
    try builder.writeLine("// ═══════════════════════════════════════════════════════════════════");
    try builder.writeLine("");
    try builder.writeLine("pub const PosChallenge = struct {");
    try builder.writeLine("    challenge_id: [32]u8,");
    try builder.writeLine("    shard_hash: [32]u8,");
    try builder.writeLine("    byte_offset: u32,");
    try builder.writeLine("    byte_length: u32,");
    try builder.writeLine("};");
    try builder.writeLine("");
    try builder.writeLine("pub const PosProof = struct {");
    try builder.writeLine("    challenge_id: [32]u8,");
    try builder.writeLine("    proof_hash: [32]u8,");
    try builder.writeLine("};");
    try builder.writeLine("");
    try builder.writeLine("pub const ProofOfStorageEngine = struct {");
    try builder.writeLine("    const MAX_NODES = 16;");
    try builder.writeLine("");
    try builder.writeLine("    failure_counts: [MAX_NODES]u8,");
    try builder.writeLine("    max_failures: u8,");
    try builder.writeLine("    deactivated: [MAX_NODES]bool,");
    try builder.writeLine("    challenges_issued: u32,");
    try builder.writeLine("    challenges_passed: u32,");
    try builder.writeLine("    challenges_failed: u32,");
    try builder.writeLine("");
    try builder.writeLine("    pub fn init(max_failures: u8) ProofOfStorageEngine {");
    try builder.writeLine("        return .{");
    try builder.writeLine("            .failure_counts = [_]u8{0} ** MAX_NODES,");
    try builder.writeLine("            .max_failures = max_failures,");
    try builder.writeLine("            .deactivated = [_]bool{false} ** MAX_NODES,");
    try builder.writeLine("            .challenges_issued = 0,");
    try builder.writeLine("            .challenges_passed = 0,");
    try builder.writeLine("            .challenges_failed = 0,");
    try builder.writeLine("        };");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    /// Create a challenge for a shard: pick byte range [offset..offset+length]");
    try builder.writeLine("    pub fn createChallenge(self: *ProofOfStorageEngine, shard_data: []const u8, offset: u32, length: u32) !PosChallenge {");
    try builder.writeLine("        if (offset + length > shard_data.len) return error.ByteRangeOutOfBounds;");
    try builder.writeLine("        self.challenges_issued += 1;");
    try builder.writeLine("        const Sha256 = std.crypto.hash.sha2.Sha256;");
    try builder.writeLine("        var cid: [32]u8 = undefined;");
    try builder.writeLine("        Sha256.hash(shard_data, &cid, .{});");
    try builder.writeLine("        var shash: [32]u8 = undefined;");
    try builder.writeLine("        Sha256.hash(shard_data, &shash, .{});");
    try builder.writeLine("        return PosChallenge{");
    try builder.writeLine("            .challenge_id = cid,");
    try builder.writeLine("            .shard_hash = shash,");
    try builder.writeLine("            .byte_offset = offset,");
    try builder.writeLine("            .byte_length = length,");
    try builder.writeLine("        };");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    /// Respond to a challenge: compute SHA-256 of shard[offset..offset+length]");
    try builder.writeLine("    pub fn respond(shard_data: []const u8, challenge: PosChallenge) PosProof {");
    try builder.writeLine("        const Sha256 = std.crypto.hash.sha2.Sha256;");
    try builder.writeLine("        const slice = shard_data[challenge.byte_offset..challenge.byte_offset + challenge.byte_length];");
    try builder.writeLine("        var h: [32]u8 = undefined;");
    try builder.writeLine("        Sha256.hash(slice, &h, .{});");
    try builder.writeLine("        return PosProof{ .challenge_id = challenge.challenge_id, .proof_hash = h };");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    /// Verify a proof: recompute hash of byte range, compare to proof_hash");
    try builder.writeLine("    pub fn verify(self: *ProofOfStorageEngine, shard_data: []const u8, challenge: PosChallenge, proof: PosProof, node_id: u8) bool {");
    try builder.writeLine("        const Sha256 = std.crypto.hash.sha2.Sha256;");
    try builder.writeLine("        const slice = shard_data[challenge.byte_offset..challenge.byte_offset + challenge.byte_length];");
    try builder.writeLine("        var expected: [32]u8 = undefined;");
    try builder.writeLine("        Sha256.hash(slice, &expected, .{});");
    try builder.writeLine("        const ok = std.mem.eql(u8, &expected, &proof.proof_hash);");
    try builder.writeLine("        if (ok) {");
    try builder.writeLine("            self.challenges_passed += 1;");
    try builder.writeLine("        } else {");
    try builder.writeLine("            self.challenges_failed += 1;");
    try builder.writeLine("            if (node_id < MAX_NODES) {");
    try builder.writeLine("                self.failure_counts[node_id] += 1;");
    try builder.writeLine("                if (self.failure_counts[node_id] >= self.max_failures) {");
    try builder.writeLine("                    self.deactivated[node_id] = true;");
    try builder.writeLine("                }");
    try builder.writeLine("            }");
    try builder.writeLine("        }");
    try builder.writeLine("        return ok;");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    pub fn isDeactivated(self: *const ProofOfStorageEngine, node_id: u8) bool {");
    try builder.writeLine("        if (node_id >= MAX_NODES) return true;");
    try builder.writeLine("        return self.deactivated[node_id];");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    pub fn getFailureCount(self: *const ProofOfStorageEngine, node_id: u8) u8 {");
    try builder.writeLine("        if (node_id >= MAX_NODES) return 0;");
    try builder.writeLine("        return self.failure_counts[node_id];");
    try builder.writeLine("    }");
    try builder.writeLine("};");
    try builder.writeLine("");
}

/// Emit Kademlia DHT struct
pub fn emitDht(builder: *CodeBuilder) !void {
    try builder.writeLine("");
    try builder.writeLine("// ═══════════════════════════════════════════════════════════════════");
    try builder.writeLine("// KADEMLIA DHT — XOR Distance Routing + Global Manifest Store/Find");
    try builder.writeLine("// 256-bit node IDs, k-buckets by leading-zero-count of XOR distance.");
    try builder.writeLine("// Store shard manifests at k-closest nodes, iterative lookup.");
    try builder.writeLine("// ═══════════════════════════════════════════════════════════════════");
    try builder.writeLine("");
    try builder.writeLine("pub const DhtNodeId = [32]u8;");
    try builder.writeLine("");
    try builder.writeLine("pub const DhtPeer = struct {");
    try builder.writeLine("    id: DhtNodeId,");
    try builder.writeLine("    port: u16,");
    try builder.writeLine("    alive: bool,");
    try builder.writeLine("};");
    try builder.writeLine("");
    try builder.writeLine("pub const DhtStoreEntry = struct {");
    try builder.writeLine("    key: DhtNodeId,");
    try builder.writeLine("    value_buf: [256]u8,");
    try builder.writeLine("    value_len: u16,");
    try builder.writeLine("    stored: bool,");
    try builder.writeLine("};");
    try builder.writeLine("");
    try builder.writeLine("/// XOR distance between two 256-bit node IDs");
    try builder.writeLine("pub fn xorDistance(a: DhtNodeId, b: DhtNodeId) DhtNodeId {");
    try builder.writeLine("    var result: DhtNodeId = undefined;");
    try builder.writeLine("    for (0..32) |i| {");
    try builder.writeLine("        result[i] = a[i] ^ b[i];");
    try builder.writeLine("    }");
    try builder.writeLine("    return result;");
    try builder.writeLine("}");
    try builder.writeLine("");
    try builder.writeLine("/// Count leading zero bits in XOR distance (determines bucket index)");
    try builder.writeLine("pub fn leadingZeroBits(dist: DhtNodeId) u16 {");
    try builder.writeLine("    var count: u16 = 0;");
    try builder.writeLine("    for (0..32) |i| {");
    try builder.writeLine("        if (dist[i] == 0) {");
    try builder.writeLine("            count += 8;");
    try builder.writeLine("        } else {");
    try builder.writeLine("            count += @intCast(@clz(dist[i]));");
    try builder.writeLine("            break;");
    try builder.writeLine("        }");
    try builder.writeLine("    }");
    try builder.writeLine("    return count;");
    try builder.writeLine("}");
    try builder.writeLine("");
    try builder.writeLine("/// Compare two DhtNodeIds for ordering (used in closest-peer sort)");
    try builder.writeLine("fn distLessThan(target: DhtNodeId, a: DhtPeer, b: DhtPeer) bool {");
    try builder.writeLine("    const da = xorDistance(target, a.id);");
    try builder.writeLine("    const db = xorDistance(target, b.id);");
    try builder.writeLine("    for (0..32) |i| {");
    try builder.writeLine("        if (da[i] < db[i]) return true;");
    try builder.writeLine("        if (da[i] > db[i]) return false;");
    try builder.writeLine("    }");
    try builder.writeLine("    return false;");
    try builder.writeLine("}");
    try builder.writeLine("");
    try builder.writeLine("pub const KBucket = struct {");
    try builder.writeLine("    const K = 8; // max peers per bucket");
    try builder.writeLine("    peers: [K]DhtPeer,");
    try builder.writeLine("    count: u8,");
    try builder.writeLine("");
    try builder.writeLine("    pub fn init() KBucket {");
    try builder.writeLine("        return .{");
    try builder.writeLine("            .peers = undefined,");
    try builder.writeLine("            .count = 0,");
    try builder.writeLine("        };");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    pub fn addPeer(self: *KBucket, peer: DhtPeer) bool {");
    try builder.writeLine("        if (self.count >= K) return false;");
    try builder.writeLine("        self.peers[self.count] = peer;");
    try builder.writeLine("        self.count += 1;");
    try builder.writeLine("        return true;");
    try builder.writeLine("    }");
    try builder.writeLine("};");
    try builder.writeLine("");
    try builder.writeLine("pub const DhtEngine = struct {");
    try builder.writeLine("    const NUM_BUCKETS = 256;");
    try builder.writeLine("    const MAX_ENTRIES = 64;");
    try builder.writeLine("");
    try builder.writeLine("    self_id: DhtNodeId,");
    try builder.writeLine("    buckets: [NUM_BUCKETS]KBucket,");
    try builder.writeLine("    entries: [MAX_ENTRIES]DhtStoreEntry,");
    try builder.writeLine("    entry_count: u16,");
    try builder.writeLine("    peer_count: u16,");
    try builder.writeLine("");
    try builder.writeLine("    pub fn init(self_id: DhtNodeId) DhtEngine {");
    try builder.writeLine("        var engine: DhtEngine = undefined;");
    try builder.writeLine("        engine.self_id = self_id;");
    try builder.writeLine("        for (0..NUM_BUCKETS) |i| {");
    try builder.writeLine("            engine.buckets[i] = KBucket.init();");
    try builder.writeLine("        }");
    try builder.writeLine("        engine.entry_count = 0;");
    try builder.writeLine("        engine.peer_count = 0;");
    try builder.writeLine("        return engine;");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    /// Add a peer to the routing table in the correct k-bucket");
    try builder.writeLine("    pub fn addPeer(self: *DhtEngine, peer: DhtPeer) bool {");
    try builder.writeLine("        const dist = xorDistance(self.self_id, peer.id);");
    try builder.writeLine("        const lz = leadingZeroBits(dist);");
    try builder.writeLine("        const bucket_idx = if (lz >= NUM_BUCKETS) NUM_BUCKETS - 1 else lz;");
    try builder.writeLine("        const ok = self.buckets[bucket_idx].addPeer(peer);");
    try builder.writeLine("        if (ok) self.peer_count += 1;");
    try builder.writeLine("        return ok;");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    /// Get bucket index for a peer (by XOR distance leading zeros)");
    try builder.writeLine("    pub fn bucketFor(self: *const DhtEngine, peer_id: DhtNodeId) u16 {");
    try builder.writeLine("        const dist = xorDistance(self.self_id, peer_id);");
    try builder.writeLine("        const lz = leadingZeroBits(dist);");
    try builder.writeLine("        return if (lz >= NUM_BUCKETS) NUM_BUCKETS - 1 else lz;");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    /// Store a key-value entry");
    try builder.writeLine("    pub fn store(self: *DhtEngine, key: DhtNodeId, value: []const u8) bool {");
    try builder.writeLine("        if (self.entry_count >= MAX_ENTRIES) return false;");
    try builder.writeLine("        if (value.len > 256) return false;");
    try builder.writeLine("        var entry: DhtStoreEntry = undefined;");
    try builder.writeLine("        entry.key = key;");
    try builder.writeLine("        @memcpy(entry.value_buf[0..value.len], value);");
    try builder.writeLine("        entry.value_len = @intCast(value.len);");
    try builder.writeLine("        entry.stored = true;");
    try builder.writeLine("        self.entries[self.entry_count] = entry;");
    try builder.writeLine("        self.entry_count += 1;");
    try builder.writeLine("        return true;");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    /// Find a value by key (exact match)");
    try builder.writeLine("    pub fn find(self: *const DhtEngine, key: DhtNodeId) ?[]const u8 {");
    try builder.writeLine("        for (0..self.entry_count) |i| {");
    try builder.writeLine("            if (std.mem.eql(u8, &self.entries[i].key, &key) and self.entries[i].stored) {");
    try builder.writeLine("                return self.entries[i].value_buf[0..self.entries[i].value_len];");
    try builder.writeLine("            }");
    try builder.writeLine("        }");
    try builder.writeLine("        return null;");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    pub const ClosestResult = struct { peers: [8]DhtPeer, count: u8 };");
    try builder.writeLine("");
    try builder.writeLine("    /// Find k-closest peers to a target key");
    try builder.writeLine("    pub fn closestPeers(self: *const DhtEngine, target: DhtNodeId, k: u8) ClosestResult {");
    try builder.writeLine("        var all_peers: [256]DhtPeer = undefined;");
    try builder.writeLine("        var total: u16 = 0;");
    try builder.writeLine("        for (0..NUM_BUCKETS) |bi| {");
    try builder.writeLine("            for (0..self.buckets[bi].count) |pi| {");
    try builder.writeLine("                if (total < 256) {");
    try builder.writeLine("                    all_peers[total] = self.buckets[bi].peers[pi];");
    try builder.writeLine("                    total += 1;");
    try builder.writeLine("                }");
    try builder.writeLine("            }");
    try builder.writeLine("        }");
    try builder.writeLine("        // Sort by XOR distance to target");
    try builder.writeLine("        const slice = all_peers[0..total];");
    try builder.writeLine("        std.mem.sortUnstable(DhtPeer, slice, target, distLessThan);");
    try builder.writeLine("        var result: ClosestResult = undefined;");
    try builder.writeLine("        const n = if (k < total) k else @as(u8, @intCast(total));");
    try builder.writeLine("        for (0..n) |i| {");
    try builder.writeLine("            result.peers[i] = slice[i];");
    try builder.writeLine("        }");
    try builder.writeLine("        result.count = n;");
    try builder.writeLine("        return result;");
    try builder.writeLine("    }");
    try builder.writeLine("};");
    try builder.writeLine("");
}

/// Emit Live Swarm struct
pub fn emitSwarm(builder: *CodeBuilder) !void {
    try builder.writeLine("");
    try builder.writeLine("// ═══════════════════════════════════════════════════════════════════");
    try builder.writeLine("// LIVE SWARM — Multi-Host Bootstrap + Node Lifecycle + Ping/Pong");
    try builder.writeLine("// Seed peers → DHT join → announce capacity → heartbeat → serve.");
    try builder.writeLine("// ═══════════════════════════════════════════════════════════════════");
    try builder.writeLine("");
    try builder.writeLine("pub const NodeState = enum(u8) {");
    try builder.writeLine("    joining = 0,");
    try builder.writeLine("    active = 1,");
    try builder.writeLine("    leaving = 2,");
    try builder.writeLine("    dead = 3,");
    try builder.writeLine("};");
    try builder.writeLine("");
    try builder.writeLine("pub const SeedPeer = struct {");
    try builder.writeLine("    addr_buf: [64]u8,");
    try builder.writeLine("    addr_len: u8,");
    try builder.writeLine("    port: u16,");
    try builder.writeLine("    alive: bool,");
    try builder.writeLine("};");
    try builder.writeLine("");
    try builder.writeLine("pub const SwarmNodeInfo = struct {");
    try builder.writeLine("    node_id: [32]u8,");
    try builder.writeLine("    port: u16,");
    try builder.writeLine("    state: NodeState,");
    try builder.writeLine("    shards_stored: u32,");
    try builder.writeLine("    capacity_mb: u32,");
    try builder.writeLine("    last_ping: i64,");
    try builder.writeLine("    latency_ms: u16,");
    try builder.writeLine("};");
    try builder.writeLine("");
    try builder.writeLine("pub const SwarmEngine = struct {");
    try builder.writeLine("    const MAX_NODES = 64;");
    try builder.writeLine("    const PING_INTERVAL_MS: i64 = 5000;");
    try builder.writeLine("    const PEER_TIMEOUT_MS: i64 = 30000;");
    try builder.writeLine("");
    try builder.writeLine("    self_id: [32]u8,");
    try builder.writeLine("    self_port: u16,");
    try builder.writeLine("    self_state: NodeState,");
    try builder.writeLine("    nodes: [MAX_NODES]SwarmNodeInfo,");
    try builder.writeLine("    node_count: u16,");
    try builder.writeLine("    total_shards: u32,");
    try builder.writeLine("    total_capacity_mb: u32,");
    try builder.writeLine("");
    try builder.writeLine("    pub fn init(self_id: [32]u8, port: u16) SwarmEngine {");
    try builder.writeLine("        var engine: SwarmEngine = undefined;");
    try builder.writeLine("        engine.self_id = self_id;");
    try builder.writeLine("        engine.self_port = port;");
    try builder.writeLine("        engine.self_state = .joining;");
    try builder.writeLine("        engine.node_count = 0;");
    try builder.writeLine("        engine.total_shards = 0;");
    try builder.writeLine("        engine.total_capacity_mb = 0;");
    try builder.writeLine("        return engine;");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    /// Bootstrap: contact seed peers, add them to node list");
    try builder.writeLine("    pub fn bootstrap(self: *SwarmEngine, seeds: []const SeedPeer) u16 {");
    try builder.writeLine("        var added: u16 = 0;");
    try builder.writeLine("        for (seeds) |seed| {");
    try builder.writeLine("            if (!seed.alive) continue;");
    try builder.writeLine("            if (self.node_count >= MAX_NODES) break;");
    try builder.writeLine("            var info: SwarmNodeInfo = undefined;");
    try builder.writeLine("            // Derive node_id from seed addr (in real impl, exchanged via handshake)");
    try builder.writeLine("            const Sha256 = std.crypto.hash.sha2.Sha256;");
    try builder.writeLine("            Sha256.hash(seed.addr_buf[0..seed.addr_len], &info.node_id, .{});");
    try builder.writeLine("            info.port = seed.port;");
    try builder.writeLine("            info.state = .active;");
    try builder.writeLine("            info.shards_stored = 0;");
    try builder.writeLine("            info.capacity_mb = 0;");
    try builder.writeLine("            info.last_ping = 0;");
    try builder.writeLine("            info.latency_ms = 0;");
    try builder.writeLine("            self.nodes[self.node_count] = info;");
    try builder.writeLine("            self.node_count += 1;");
    try builder.writeLine("            added += 1;");
    try builder.writeLine("        }");
    try builder.writeLine("        if (added > 0) self.self_state = .active;");
    try builder.writeLine("        return added;");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    /// Process ping from a node (update last_ping timestamp)");
    try builder.writeLine("    pub fn receivePing(self: *SwarmEngine, node_id: [32]u8, timestamp: i64, latency: u16) bool {");
    try builder.writeLine("        for (0..self.node_count) |i| {");
    try builder.writeLine("            if (std.mem.eql(u8, &self.nodes[i].node_id, &node_id)) {");
    try builder.writeLine("                self.nodes[i].last_ping = timestamp;");
    try builder.writeLine("                self.nodes[i].latency_ms = latency;");
    try builder.writeLine("                if (self.nodes[i].state == .dead) self.nodes[i].state = .active;");
    try builder.writeLine("                return true;");
    try builder.writeLine("            }");
    try builder.writeLine("        }");
    try builder.writeLine("        return false;");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    /// Check for timed-out nodes and mark them dead");
    try builder.writeLine("    pub fn checkTimeouts(self: *SwarmEngine, now: i64) u16 {");
    try builder.writeLine("        var dead_count: u16 = 0;");
    try builder.writeLine("        for (0..self.node_count) |i| {");
    try builder.writeLine("            if (self.nodes[i].state == .active and");
    try builder.writeLine("                self.nodes[i].last_ping > 0 and");
    try builder.writeLine("                (now - self.nodes[i].last_ping) > PEER_TIMEOUT_MS)");
    try builder.writeLine("            {");
    try builder.writeLine("                self.nodes[i].state = .dead;");
    try builder.writeLine("                dead_count += 1;");
    try builder.writeLine("            }");
    try builder.writeLine("        }");
    try builder.writeLine("        return dead_count;");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    /// Initiate graceful leave");
    try builder.writeLine("    pub fn initiateLeave(self: *SwarmEngine) void {");
    try builder.writeLine("        self.self_state = .leaving;");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    /// Count nodes by state");
    try builder.writeLine("    pub fn countByState(self: *const SwarmEngine, state: NodeState) u16 {");
    try builder.writeLine("        var count: u16 = 0;");
    try builder.writeLine("        for (0..self.node_count) |i| {");
    try builder.writeLine("            if (self.nodes[i].state == state) count += 1;");
    try builder.writeLine("        }");
    try builder.writeLine("        return count;");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    /// Aggregate health report");
    try builder.writeLine("    pub const HealthReport = struct {");
    try builder.writeLine("        total_nodes: u16,");
    try builder.writeLine("        nodes_active: u16,");
    try builder.writeLine("        nodes_joining: u16,");
    try builder.writeLine("        nodes_leaving: u16,");
    try builder.writeLine("        nodes_dead: u16,");
    try builder.writeLine("        total_shards: u32,");
    try builder.writeLine("        total_capacity_mb: u32,");
    try builder.writeLine("        avg_latency_ms: u16,");
    try builder.writeLine("    };");
    try builder.writeLine("");
    try builder.writeLine("    pub fn healthReport(self: *const SwarmEngine) HealthReport {");
    try builder.writeLine("        var report: HealthReport = .{");
    try builder.writeLine("            .total_nodes = self.node_count,");
    try builder.writeLine("            .nodes_active = 0, .nodes_joining = 0,");
    try builder.writeLine("            .nodes_leaving = 0, .nodes_dead = 0,");
    try builder.writeLine("            .total_shards = 0, .total_capacity_mb = 0,");
    try builder.writeLine("            .avg_latency_ms = 0,");
    try builder.writeLine("        };");
    try builder.writeLine("        var lat_sum: u32 = 0;");
    try builder.writeLine("        var lat_count: u16 = 0;");
    try builder.writeLine("        for (0..self.node_count) |i| {");
    try builder.writeLine("            switch (self.nodes[i].state) {");
    try builder.writeLine("                .active => report.nodes_active += 1,");
    try builder.writeLine("                .joining => report.nodes_joining += 1,");
    try builder.writeLine("                .leaving => report.nodes_leaving += 1,");
    try builder.writeLine("                .dead => report.nodes_dead += 1,");
    try builder.writeLine("            }");
    try builder.writeLine("            report.total_shards += self.nodes[i].shards_stored;");
    try builder.writeLine("            report.total_capacity_mb += self.nodes[i].capacity_mb;");
    try builder.writeLine("            if (self.nodes[i].latency_ms > 0) {");
    try builder.writeLine("                lat_sum += self.nodes[i].latency_ms;");
    try builder.writeLine("                lat_count += 1;");
    try builder.writeLine("            }");
    try builder.writeLine("        }");
    try builder.writeLine("        if (lat_count > 0) report.avg_latency_ms = @intCast(lat_sum / lat_count);");
    try builder.writeLine("        return report;");
    try builder.writeLine("    }");
    try builder.writeLine("};");
    try builder.writeLine("");
}

/// Emit RewardEngine struct ($TRI mint/slash)
pub fn emitRewards(builder: *CodeBuilder) !void {
    try builder.writeLine("");
    try builder.writeLine("// ═══════════════════════════════════════════════════════════════════");
    try builder.writeLine("// LIVE REWARDS — $TRI Token Mint/Slash on PoS Challenge Results");
    try builder.writeLine("// Pass challenge → mint reward. Fail challenge → slash stake.");
    try builder.writeLine("// Min stake required to participate. Epoch summary aggregation.");
    try builder.writeLine("// ═══════════════════════════════════════════════════════════════════");
    try builder.writeLine("");
    try builder.writeLine("pub const TRI_DECIMALS: u8 = 18;");
    try builder.writeLine("pub const TRI_SYMBOL = \"$TRI\";");
    try builder.writeLine("");
    try builder.writeLine("pub const RewardConfig = struct {");
    try builder.writeLine("    base_reward_wei: u64,       // reward per challenge pass (1e15 = 0.001 TRI)");
    try builder.writeLine("    slash_rate_pct: u8,         // slash % per failure (1 = 1%)");
    try builder.writeLine("    corruption_slash_pct: u8,   // slash % for corruption (5 = 5%)");
    try builder.writeLine("    min_stake_wei: u64,         // min stake to participate (100 TRI)");
    try builder.writeLine("};");
    try builder.writeLine("");
    try builder.writeLine("pub const DEFAULT_REWARD_CONFIG = RewardConfig{");
    try builder.writeLine("    .base_reward_wei = 1_000_000_000_000_000, // 0.001 TRI");
    try builder.writeLine("    .slash_rate_pct = 1,");
    try builder.writeLine("    .corruption_slash_pct = 5,");
    try builder.writeLine("    .min_stake_wei = 100_000_000_000_000_000_000, // 100 TRI");
    try builder.writeLine("};");
    try builder.writeLine("");
    try builder.writeLine("pub const NodeRewardBalance = struct {");
    try builder.writeLine("    balance_wei: u64,");
    try builder.writeLine("    total_earned_wei: u64,");
    try builder.writeLine("    total_slashed_wei: u64,");
    try builder.writeLine("    challenges_passed: u32,");
    try builder.writeLine("    challenges_failed: u32,");
    try builder.writeLine("    is_active: bool,");
    try builder.writeLine("};");
    try builder.writeLine("");
    try builder.writeLine("pub const EpochSummary = struct {");
    try builder.writeLine("    total_minted_wei: u64,");
    try builder.writeLine("    total_slashed_wei: u64,");
    try builder.writeLine("    active_earners: u16,");
    try builder.writeLine("    epoch_challenges: u32,");
    try builder.writeLine("};");
    try builder.writeLine("");
    try builder.writeLine("pub const RewardEngine = struct {");
    try builder.writeLine("    const MAX_NODES = 64;");
    try builder.writeLine("");
    try builder.writeLine("    config: RewardConfig,");
    try builder.writeLine("    balances: [MAX_NODES]NodeRewardBalance,");
    try builder.writeLine("    node_count: u16,");
    try builder.writeLine("    total_minted: u64,");
    try builder.writeLine("    total_slashed: u64,");
    try builder.writeLine("    total_challenges: u32,");
    try builder.writeLine("");
    try builder.writeLine("    pub fn init(config: RewardConfig) RewardEngine {");
    try builder.writeLine("        var engine: RewardEngine = undefined;");
    try builder.writeLine("        engine.config = config;");
    try builder.writeLine("        engine.node_count = 0;");
    try builder.writeLine("        engine.total_minted = 0;");
    try builder.writeLine("        engine.total_slashed = 0;");
    try builder.writeLine("        engine.total_challenges = 0;");
    try builder.writeLine("        return engine;");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    /// Register a node with initial stake");
    try builder.writeLine("    pub fn registerNode(self: *RewardEngine, stake_wei: u64) u16 {");
    try builder.writeLine("        if (self.node_count >= MAX_NODES) return MAX_NODES;");
    try builder.writeLine("        const id = self.node_count;");
    try builder.writeLine("        self.balances[id] = .{");
    try builder.writeLine("            .balance_wei = stake_wei,");
    try builder.writeLine("            .total_earned_wei = 0,");
    try builder.writeLine("            .total_slashed_wei = 0,");
    try builder.writeLine("            .challenges_passed = 0,");
    try builder.writeLine("            .challenges_failed = 0,");
    try builder.writeLine("            .is_active = stake_wei >= self.config.min_stake_wei,");
    try builder.writeLine("        };");
    try builder.writeLine("        self.node_count += 1;");
    try builder.writeLine("        return id;");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    /// Mint reward for passing PoS challenge");
    try builder.writeLine("    pub fn mintReward(self: *RewardEngine, node_id: u16) bool {");
    try builder.writeLine("        if (node_id >= self.node_count) return false;");
    try builder.writeLine("        if (!self.balances[node_id].is_active) return false;");
    try builder.writeLine("        if (self.balances[node_id].balance_wei < self.config.min_stake_wei) {");
    try builder.writeLine("            self.balances[node_id].is_active = false;");
    try builder.writeLine("            return false;");
    try builder.writeLine("        }");
    try builder.writeLine("        self.balances[node_id].balance_wei += self.config.base_reward_wei;");
    try builder.writeLine("        self.balances[node_id].total_earned_wei += self.config.base_reward_wei;");
    try builder.writeLine("        self.balances[node_id].challenges_passed += 1;");
    try builder.writeLine("        self.total_minted += self.config.base_reward_wei;");
    try builder.writeLine("        self.total_challenges += 1;");
    try builder.writeLine("        return true;");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    /// Slash node for failing PoS challenge");
    try builder.writeLine("    pub fn slashNode(self: *RewardEngine, node_id: u16) u64 {");
    try builder.writeLine("        if (node_id >= self.node_count) return 0;");
    try builder.writeLine("        const slash_amount = self.balances[node_id].balance_wei * self.config.slash_rate_pct / 100;");
    try builder.writeLine("        self.balances[node_id].balance_wei -= slash_amount;");
    try builder.writeLine("        self.balances[node_id].total_slashed_wei += slash_amount;");
    try builder.writeLine("        self.balances[node_id].challenges_failed += 1;");
    try builder.writeLine("        self.total_slashed += slash_amount;");
    try builder.writeLine("        self.total_challenges += 1;");
    try builder.writeLine("        // Deactivate if below min stake");
    try builder.writeLine("        if (self.balances[node_id].balance_wei < self.config.min_stake_wei) {");
    try builder.writeLine("            self.balances[node_id].is_active = false;");
    try builder.writeLine("        }");
    try builder.writeLine("        return slash_amount;");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    /// Get balance for a node");
    try builder.writeLine("    pub fn getBalance(self: *const RewardEngine, node_id: u16) u64 {");
    try builder.writeLine("        if (node_id >= self.node_count) return 0;");
    try builder.writeLine("        return self.balances[node_id].balance_wei;");
    try builder.writeLine("    }");
    try builder.writeLine("");
    try builder.writeLine("    /// Compute epoch summary");
    try builder.writeLine("    pub fn epochSummary(self: *const RewardEngine) EpochSummary {");
    try builder.writeLine("        var active: u16 = 0;");
    try builder.writeLine("        for (0..self.node_count) |i| {");
    try builder.writeLine("            if (self.balances[i].is_active) active += 1;");
    try builder.writeLine("        }");
    try builder.writeLine("        return .{");
    try builder.writeLine("            .total_minted_wei = self.total_minted,");
    try builder.writeLine("            .total_slashed_wei = self.total_slashed,");
    try builder.writeLine("            .active_earners = active,");
    try builder.writeLine("            .epoch_challenges = self.total_challenges,");
    try builder.writeLine("        };");
    try builder.writeLine("    }");
    try builder.writeLine("};");
    try builder.writeLine("");
}
