// tnf_cost_e2m8_add_top.v -- GENERATED by gen/gen_tnf_cost_sweep.py, do not edit by hand.
// TNF cost-sweep arm: E_t = 2 trits of balanced exponent -> 4 binary cells,
// M = 8 mantissa bits.  Physical width 13 cells; nominal width 11
// under the specification convention 1 + E_t + M.  Exponent reach +-4
// binades.  The two widths differ and the difference is the point: any accuracy
// claim must name which convention it uses.
//
// HAS_INF = 1: TNF reserves the top offset row for the non-finite class, so
// exp = all-ones must not decode as a finite maximum.
module tnf_cost_e2m8_add_top(
    input clk, input rst,
    input in_valid, input [12:0] in_a, input [12:0] in_b,
    output in_ready, output out_valid, output [12:0] out_y, input out_ready
);
    gf_adder_param #(.EXP_BITS(4), .MANT_BITS(8), .HAS_INF(1)) u (
        .clk(clk), .rst(rst), .in_valid(in_valid), .in_a(in_a), .in_b(in_b),
        .in_ready(in_ready), .out_valid(out_valid), .out_y(out_y), .out_ready(out_ready)
    );
endmodule
