// tnf_cost_e3m33_add_top.v -- GENERATED by gen/gen_tnf_cost_sweep.py, do not edit by hand.
// TNF cost-sweep arm: E_t = 3 trits of balanced exponent -> 5 binary cells,
// M = 33 mantissa bits.  Physical width 39 cells; nominal width 37
// under the specification convention 1 + E_t + M.  Exponent reach +-13
// binades.  The two widths differ and the difference is the point: any accuracy
// claim must name which convention it uses.
//
// HAS_INF = 1: TNF reserves the top offset row for the non-finite class, so
// exp = all-ones must not decode as a finite maximum.
module tnf_cost_e3m33_add_top(
    input clk, input rst,
    input in_valid, input [38:0] in_a, input [38:0] in_b,
    output in_ready, output out_valid, output [38:0] out_y, input out_ready
);
    gf_adder_param #(.EXP_BITS(5), .MANT_BITS(33), .HAS_INF(1), .PIPELINE(1)) u (
        .clk(clk), .rst(rst), .in_valid(in_valid), .in_a(in_a), .in_b(in_b),
        .in_ready(in_ready), .out_valid(out_valid), .out_y(out_y), .out_ready(out_ready)
    );
endmodule
