// tnf_cost_e4m13_mul_top.v -- GENERATED by gen/gen_tnf_cost_sweep.py, do not edit by hand.
// TNF cost-sweep arm: E_t = 4 trits of balanced exponent -> 7 binary cells,
// M = 13 mantissa bits.  Physical width 21 cells; nominal width 18
// under the specification convention 1 + E_t + M.  Exponent reach +-40
// binades.  The two widths differ and the difference is the point: any accuracy
// claim must name which convention it uses.
//
// HAS_INF = 1: TNF reserves the top offset row for the non-finite class, so
// exp = all-ones must not decode as a finite maximum.
module tnf_cost_e4m13_mul_top(
    input clk, input rst,
    input in_valid, input [20:0] in_a, input [20:0] in_b,
    output in_ready, output out_valid, output [20:0] out_y, input out_ready
);
    gf_mul_param #(.EXP_BITS(7), .MANT_BITS(13), .HAS_INF(1)) u (
        .clk(clk), .rst(rst), .in_valid(in_valid), .in_a(in_a), .in_b(in_b),
        .in_ready(in_ready), .out_valid(out_valid), .out_y(out_y), .out_ready(out_ready)
    );
endmodule
