// GENERATED by conformance/mxdot4_board_from_spec.mjs from specs/trinet/mxdot4_on_board_ax7203.t27 -- do not edit.
// spec sha256 e63d4a31b27078b239d57ce284f2fdc0b2cae0d7bceba76c94b784f4a5d7483d
// t27 compiler wasm sha256 bb39b9a5ca412a2695ab6a20a54e222933e10edaf08ef053670e4974d08f113f
`ifndef MXDOT4_BOARD_PARAMS
`define MXDOT4_BOARD_PARAMS
`define MXDOT4_BLOCK 8'd32
`define MXDOT4_ELEM_BITS 8'd4
`define MXDOT4_SUM_BITS 8'd14
`define MXDOT4_EXP_BITS 8'd9
`define MXDOT4_WORD_BITS 8'd24
`define MXDOT4_NAN_WORD 24'd8388608
`define MXDOT4_SCALE_NAN 8'd255
`define MXDOT4_E2M1_TABLE 32'hC8643210
`define MXDOT4_TNF4_TABLE 32'h0C864320
`define MXDOT4_BAUD_DIV 10'd60
`define MXDOT4_SYNC0 8'd170
`define MXDOT4_SYNC1 8'd85
`define MXDOT4_RESP_OK 8'd165
`define MXDOT4_RESP_BADOP 8'd229
`define MXDOT4_OP_MXFP4 8'd1
`define MXDOT4_OP_TNF4 8'd2
`define MXDOT4_REQ_BYTES 8'd38
`define MXDOT4_RESP_BYTES 8'd5
`define MXDOT4_CORE_STAGES 8'd3
`endif
