#!/bin/bash
# Sacred ALU Vivado Synthesis — Phase 6.4
# Accurate Fmax + utilization analysis
#
# Target: Digilent Arty A7-100T (XC7A100T-CSG324)
# Clock: 100 MHz onboard oscillator
# φ² + 1/φ² = 3
#
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SYNTH_DIR="$PROJECT_ROOT/fpga/openxc7-synth"
OUT_DIR="$PROJECT_ROOT/fpga/openxc7-synth/synth-vivado"

mkdir -p "$OUT_DIR"

# Check for vivado
if ! command -v vivado &> /dev/null; then
    echo "ERROR: vivado not found. Please install Vivado WebPACK or Design Suite."
    exit 1
fi

echo "=== Sacred ALU Vivado Synthesis ==="
echo "Target: XC7A100T-CSG324 (Arty A7-100T)"
echo "Clock: 100 MHz"
echo ""

# Create Vivado batch project
TCL_SCRIPT="$OUT_DIR/sacred_synth_batch.tcl"

cat > "$TCL_SCRIPT" << 'TCL_EOF'
# Sacred ALU Vivado Synthesis Project
# Generated by run-vivado.sh

# Project settings
set project sacred_alu_synth
set top_module sacred_alu

# Read design files
read_verilog [glob "./../../*.v"]

# Synthesis settings
set_property top_module [current_file]
set_property -name {TOP_MODULE} sacred_alu

# Clock constraint (100 MHz = 10 ns)
create_clock -period 10.000 -name clk

# Synthesis strategy (high effort)
set_property STRATEGY SYNTHESIS_SPEED

# Generate utilization report
report_utilization -file utilization.txt
report_timing_summary -file timing_summary.txt

# Generate netlist
write_edif -file sacred_alu.edif

# Generate bitstream (optional for full flow)
# launch_runs impl_1 -to_step write_bitstream

puts "Synthesis complete"
puts "Reports generated: utilization.txt, timing_summary.txt"
TCL_EOF

# Run Vivado in batch mode
echo "Running Vivado batch synthesis..."
vivado -mode batch -source "$TCL_SCRIPT" \
    -log "$OUT_DIR/vivado.log" \
    -journal "$OUT_DIR/vivado.jou" \
    -notrace

# Check for results
if [ -f "$OUT_DIR/utilization.txt" ]; then
    echo ""
    echo "=== Utilization Report ==="
    cat "$OUT_DIR/utilization.txt"
fi

if [ -f "$OUT_DIR/timing_summary.txt" ]; then
    echo ""
    echo "=== Timing Summary ==="
    cat "$OUT_DIR/timing_summary.txt"
fi

echo ""
echo "=== Synthesis Complete ==="
echo "Output directory: $OUT_DIR"
echo "Logs: $OUT_DIR/vivado.log"
echo ""
