// ═══════════════════════════════════════════════════════════════════════════════
// TRINITY AUTONOMOUS PAPER PUBLISHING v2.0
// ═══════════════════════════════════════════════════════════════════════════════
//
// +10% improvement triggers blog post generation, auto-deploy to docsite
//
// φ² + 1/φ² = 3
// ═══════════════════════════════════════════════════════════════════════════════

const std = @import("std");

pub const BenchmarkResult = struct {
    baseline_metric: f64,
    new_metric: f64,
    improvement_percent: f64,
    metric_name: []const u8,
    commit_hash: []const u8,
    timestamp: i64,

    pub fn format(self: BenchmarkResult, allocator: std.mem.Allocator) ![]const u8 {
        return std.fmt.allocPrint(allocator, "{s}: {d:.2} → {d:.2} (+{d:.1}%)", .{
            self.metric_name,
            self.baseline_metric,
            self.new_metric,
            self.improvement_percent,
        });
    }
};

pub const BlogPost = struct {
    title: []const u8,
    slug: []const u8,
    content: []const u8,
    tags: []const []const u8,
    category: []const u8,
    author: []const u8,
    date: []const u8,

    pub fn deinit(self: *BlogPost, allocator: std.mem.Allocator) void {
        allocator.free(self.title);
        allocator.free(self.slug);
        allocator.free(self.content);
        allocator.free(self.category);
        allocator.free(self.author);
        allocator.free(self.date);
        for (self.tags) |tag| {
            allocator.free(tag);
        }
        allocator.free(self.tags);
    }
};

pub const PaperPublisher = struct {
    allocator: std.mem.Allocator,
    docsite_path: []const u8,
    project_root: []const u8,

    pub fn init(allocator: std.mem.Allocator, docsite_path: []const u8, project_root: []const u8) PaperPublisher {
        return .{
            .allocator = allocator,
            .docsite_path = docsite_path,
            .project_root = project_root,
        };
    }

    /// Check if improvement meets publish threshold
    pub fn shouldPublish(self: *PaperPublisher, result: BenchmarkResult) bool {
        _ = self;
        return result.improvement_percent >= 10.0; // +10% threshold
    }

    /// Generate slug from title
    fn generateSlug(self: *PaperPublisher, title: []const u8) ![]const u8 {
        _ = self;

        // Simple slug generation: lowercase, replace spaces with hyphens
        const slug = try self.allocator.alloc(u8, title.len);
        var slug_idx: usize = 0;
        for (title) |c| {
            if (std.ascii.isAlNum(c)) {
                slug[slug_idx] = std.ascii.toLower(c);
                slug_idx += 1;
            } else if (c == ' ') {
                slug[slug_idx] = '-';
                slug_idx += 1;
            }
        }
        return slug[0..slug_idx];
    }

    /// Generate blog post from benchmark results
    pub fn generateBlogPost(self: *PaperPublisher, result: BenchmarkResult) !BlogPost {
        const date = try self.allocator.dupe(u8, "2026-03-06"); // TODO: actual date
        defer self.allocator.free(date);

        const title = try std.fmt.allocPrint(
            self.allocator,
            "Auto-Improvement: {d:.1}% on {s}",
            .{ result.improvement_percent, result.metric_name }
        );

        const slug = try self.generateSlug(title);

        // Generate markdown content
        const content = try std.fmt.allocPrint(
            self.allocator,
            \\# {s}
            \\
            \\**RALPH Autonomous Improvement**
            \\
            \\Trinity's self-improving AI agent has achieved a **{d:.1}% improvement** on `{s}` performance.
            \\
            \\## Results
            \\
            \\| Metric | Before | After | Improvement |
            \\|--------|--------|-------|------------|
            \\| {s} | {d:.2} | {d:.2} | +{d:.1}% |
            \\
            \\## Technical Details
            \\
            \\- **Commit**: `{s}`
            \\- **Timestamp**: {d}
            \\- **Improvement Type**: Autonomous optimization
            \\
            \\This improvement was automatically discovered and implemented by RALPH (Trinity's Orchestrator).
            \\
            \\φ² + 1/φ² = 3
            \\
            \\---
            \\
            \\*Auto-generated by TRINITY SELF-EVOLUTION SYSTEM*
        , .{
            title,
            result.improvement_percent,
            result.metric_name,
            result.metric_name,
            result.baseline_metric,
            result.new_metric,
            result.improvement_percent,
            result.commit_hash,
            result.timestamp,
        });

        // Tags
        const tags = try self.allocator.alloc([]const u8, 3);
        tags[0] = try self.allocator.dupe(u8, "auto-improvement");
        tags[1] = try self.allocator.dupe(u8, "benchmark");
        tags[2] = try self.allocator.dupe(u8, "trinity");

        return BlogPost{
            .title = title,
            .slug = slug,
            .content = content,
            .tags = tags,
            .category = try self.allocator.dupe(u8, "Research"),
            .author = try self.allocator.dupe(u8, "RALPH AI"),
            .date = date,
        };
    }

    /// Write blog post to docsite
    fn writeBlogPost(self: *PaperPublisher, post: BlogPost) !void {
        const research_dir = try std.fmt.allocPrint(
            self.allocator,
            "{s}/docs/research/auto-generated",
            .{self.docsite_path}
        );
        defer self.allocator.free(research_dir);

        // Create directory
        std.fs.cwd().makePath(research_dir) catch |err| {
            if (err != error.PathAlreadyExists) {
                return err;
            }
        };

        // Write markdown file
        const file_path = try std.fmt.allocPrint(
            self.allocator,
            "{s}/{s}.md",
            .{ research_dir, post.slug }
        );
        defer self.allocator.free(file_path);

        const file = try std.fs.cwd().createFile(file_path, .{});
        defer file.close();

        try file.writeAll(post.content);
    }

    /// Deploy blog post to docsite
    pub fn deployToDocsite(self: *PaperPublisher, post: BlogPost) !void {
        // Write blog post
        try self.writeBlogPost(post);

        // TODO: Update sidebar.ts
        // TODO: Run: cd docsite && npm run build
        // TODO: Deploy to gh-pages

        std.log.info("Blog post deployed: {s}.md", .{post.slug});
    }

    /// Post to X (Twitter)
    pub fn postToX(self: *PaperPublisher, message: []const u8) !void {
        _ = self;
        _ = message;
        // TODO: Implement X API integration
        // Requires API key and secret
        std.log.warn("X posting not yet implemented", .{});
    }

    /// Full publish workflow
    pub fn publishImprovement(self: *PaperPublisher, result: BenchmarkResult) !void {
        if (self.shouldPublish(result)) {
            const post = try self.generateBlogPost(result);
            defer post.deinit(self.allocator);

            try self.deployToDocsite(post);

            // Generate social media message
            const social_msg = try std.fmt.allocPrint(
                self.allocator,
                "🚀 TRINITY Auto-Improvement: +{d:.1}% on {s}!",
                .{ result.improvement_percent, result.metric_name }
            );
            defer self.allocator.free(social_msg);

            try self.postToX(social_msg);
        }
    }

    /// Generate improvement report
    pub fn generateReport(self: *PaperPublisher, results: []const BenchmarkResult) ![]const u8 {
        _ = self;

        var report = std.ArrayList(u8).init(self.allocator);
        const writer = report.writer();

        try writer.writeAll("# TRINITY Improvement Report\n\n");
        try writer.writeAll("| Metric | Improvement | Commit |\n");
        try writer.writeAll("|--------|-------------|--------|\n");

        for (results) |r| {
            try writer.print("| {s} | +{d:.1}% | {s} |\n", .{
                r.metric_name,
                r.improvement_percent,
                r.commit_hash[0..8],
            });
        }

        return report.toOwnedSlice();
    }
};

// CLI for testing
pub fn main() !void {
    const allocator = std.heap.page_allocator;

    const args = try std.process.argsAlloc(allocator);
    defer std.process.argsFree(allocator, args);

    std.debug.print("📝 TRINITY AUTONOMOUS PAPER PUBLISHING\n", .{});
    std.debug.print("φ² + 1/φ² = 3\n\n", .{});

    if (args.len < 2) {
        std.debug.print(
            \\Usage: paper_gen <command> [args]
            \\
            \\Commands:
            \\  generate <improvement> <metric>  - Generate blog post
            \\  report <baseline> <new> <metric>  - Generate report
            \\
            \\Example:
            \\  paper_gen generate 12.5 bind_speed
            \\  paper_gen report 100.0 112.5 throughput
            \\
        , .{});
        return;
    }

    const command = args[1];

    if (std.mem.eql(u8, command, "generate")) {
        if (args.len < 4) {
            std.debug.print("Usage: paper_gen generate <improvement> <metric>\n", .{});
            return;
        }

        const improvement = try std.fmt.parseFloat(f64, args[2]);
        const metric_name = args[3];

        var publisher = PaperPublisher.init(
            allocator,
            "/Users/playra/trinity-w1/docsite",
            "/Users/playra/trinity-w1"
        );

        const result = BenchmarkResult{
            .baseline_metric = 100.0,
            .new_metric = 100.0 * (1.0 + improvement / 100.0),
            .improvement_percent = improvement,
            .metric_name = metric_name,
            .commit_hash = "c40b16605",
            .timestamp = std.time.timestamp(),
        };

        const post = try publisher.generateBlogPost(result);
        defer post.deinit(allocator);

        std.debug.print("\n=== Generated Blog Post ===\n", .{});
        std.debug.print("Title: {s}\n", .{post.title});
        std.debug.print("Slug: {s}\n", .{post.slug});
        std.debug.print("\n{s}\n", .{post.content});

        if (publisher.shouldPublish(result)) {
            std.debug.print("\n✅ Meets publish threshold (+10%%)\n", .{});
        } else {
            std.debug.print("\n❌ Below publish threshold\n", .{});
        }
    } else {
        std.debug.print("Unknown command: {s}\n", .{command});
    }
}
