// ═══════════════════════════════════════════════════════════════════════════════
// trinity_v2_constraints v2.0.0 - FPGA Verilog from .vibee specification
// ═══════════════════════════════════════════════════════════════════════════════
//
// Golden Identity: φ² + 1/φ² = 3
//
// DO NOT EDIT - This file is auto-generated by VIBEE
//
// Target:   xilinx (50 MHz)
// ═══════════════════════════════════════════════════════════════════════════════

`timescale 1ns / 1ps

module trinity_v2_constraints (
wire  wire clk,
wire  wire rst_n,
wire  wire uart_rx,
wire  wire uart_tx,
wire  wire led
);

endmodule
