// ═══════════════════════════════════════════════════════════════════════════════
// uart_command_decoder v2.0.0 - FPGA Verilog from .vibee specification
// ═══════════════════════════════════════════════════════════════════════════════
//
// Golden Identity: φ² + 1/φ² = 3
//
// DO NOT EDIT - This file is auto-generated by VIBEE
//
// Target:   xilinx (50 MHz)
// ═══════════════════════════════════════════════════════════════════════════════

`timescale 1ns / 1ps

module uart_command_decoder (
wire  wire clk,
wire  wire rst_n,
wire  wire uart_rx,
wire  wire uart_tx,
wire  wire cmd_valid,
wire  wire [7:0] cmd_code,
wire  wire [255:0] payload_data,
wire  wire payload_valid,
wire  wire busy
);

endmodule
