#!/usr/bin/env python3
"""igla-coder's 32-token generation, parameters of specs/trinet/tern_tc_generate_long_ax7203.t27.

A thin arm, not a copy: the runner is the 8-token arm's conformance/tern_tc_generate_ax7203.py,
imported unchanged and pinned by sha256 in the spec. Every constant differs only through the
generated conformance/tern_tc_generate_long_params.py, which this wrapper installs under the module
name the pinned runner reads (tern_tc_generate_params) before importing it. Nothing else is done
here, so --self-test, --cpu, --refcell and the board arm all run the pinned code, and the spec's
`--check` still holds because no pinned file moved.

    python3 tern_tc_generate_long_ax7203.py --self-test
    python3 tern_tc_generate_long_ax7203.py --cpu                 # the 32-token integer reference
    python3 tern_tc_generate_long_ax7203.py --mode c              # the float-order reference
    python3 tern_tc_generate_long_ax7203.py --cpu --tokens 128    # the 128-token continuation
    python3 tern_tc_generate_long_ax7203.py --setkey --port /dev/cu.usbserial-110 --keys ../trinet-keys.txt

The pinned runner's flags pass through unchanged: "--self-test", "--cpu", "--mode", "--tokens",
"--refcell", "--setkey", "--port", "--keys" (quoted here so `tri fpga-selftest` finds the flag and
runs this arm's preflight with the long parameters, not only the 8-token ones).

The argparse help still says "8-token" in its first line: it is the pinned runner's text, kept as
is. The board arm of T34 runs through the reopen wrapper, tern_tc_generate_reopen_long_ax7203.py.

Author: Dmitrii Vasilev (@gHashTag)
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import tern_tc_generate_long_params  # noqa: E402  (generated by tern_tc_generate_long_from_spec.mjs)

sys.modules["tern_tc_generate_params"] = tern_tc_generate_long_params

import tern_tc_generate_ax7203 as pinned  # noqa: E402  (unchanged, sha-pinned by the spec)

if __name__ == "__main__":
    sys.exit(pinned.main())
