#!/usr/bin/env node
// ternary_storage_from_spec.mjs -- the ternary-storage search's parameters, generated from its spec.
//
//   node conformance/ternary_storage_from_spec.mjs            write the generated file
//   node conformance/ternary_storage_from_spec.mjs --check    exit 1 if it drifted
//
// Source: specs/numeric/ternary_storage_search.t27. Compiled by the t27 compiler (wasm), its test
// blocks evaluated against its constants, as conformance/mxdot4_board_from_spec.mjs does; the
// compiler and the AST helpers are imported from a gHashTag/trinity checkout (TRINITY_DIR,
// default ~/trinity), not copied.
//
// Output (path from the spec's GENERATED): research/block/ternary_storage_params.py, a SPEC dict
// the runner research/block/ternary_storage_search.py reads.

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { homedir } from 'node:os'

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const SPEC = 'specs/numeric/ternary_storage_search.t27'
const EXPECTED_MODULE = 'numeric_ternary_storage_search'
const TRINITY = process.env.TRINITY_DIR ?? join(homedir(), 'trinity')
const SITE = join(TRINITY, 'apps', 'website')
const WASM = join(SITE, 'public', 't27', 't27_compiler.wasm')

const sha256 = (b) => createHash('sha256').update(b).digest('hex')

async function helpers() {
  for (const p of [WASM, join(SITE, 'scripts', 'agents-from-specs.mjs')]) {
    if (!existsSync(p)) throw new Error(`${p} not found; set TRINITY_DIR to a gHashTag/trinity checkout`)
  }
  const a = await import(pathToFileURL(join(SITE, 'scripts', 'agents-from-specs.mjs')).href)
  const v = await import(pathToFileURL(join(SITE, 'scripts', 'viewport-from-spec.mjs')).href)
  return { ...a, runSpecTests: v.runSpecTests }
}

// Relations the test evaluator cannot state (no powers, no loops, no file reads). The level
// tables against block_tnf.py's own functions, and T27_N against NormalDist, are checked by the
// runner, which can execute them; here only the bytes of block_tnf.py are pinned.
function semanticProblems(f) {
  const p = []
  const increasing = (xs) => xs.every((x, i) => i === 0 || x > xs[i - 1])
  for (const name of ['E2M1', 'TNF4_7', 'E2M2', 'T27_U', 'T27_F', 'T27_N']) {
    if (!Array.isArray(f[name]) || f[name][0] !== 0) p.push(`${name} does not start at 0`)
    else if (!increasing(f[name])) p.push(`${name} not strictly increasing`)
  }
  for (const name of f.T27_CANDIDATES) {
    if (!Array.isArray(f[name]) || f[name].length !== f.T27_MAGS + 1) p.push(`${name} is not zero plus ${f.T27_MAGS} magnitudes`)
  }
  if (f.E2M2.length !== f.E2M2_ELEM_CODES / 2) p.push('E2M2 is not half its code count')
  if (f.E2M1.length !== f.MXFP4_ELEM_CODES / 2) p.push('E2M1 is not half its code count')
  const e2m1Missing = [...f.E2M1.keys()].filter((c) => !f.TNF4_AT_E2M1.includes(c))
  if (e2m1Missing.length !== 1 || e2m1Missing[0] !== f.E2M1_ONLY) p.push(`E2M1 codes without a TNF4 level: ${e2m1Missing}`)
  const e2m2Missing = [...f.E2M2.keys()].filter((c) => !f.T27_F_AT_E2M2.includes(c))
  if (e2m2Missing.join(',') !== '1,3') p.push(`E2M2 codes without a T27_F level: ${e2m2Missing} (spec says 1,3)`)
  if (f.CELL_CODES !== 3 ** f.CELL_TRITS) p.push('CELL_CODES != 3^CELL_TRITS')
  if (f.T27_SCALE_CODES !== 3 ** f.T27_SCALE_TRITS) p.push('T27_SCALE_CODES != 3^T27_SCALE_TRITS')
  if (f.E8M0_TRIT_CODES !== 3 ** f.E8M0_TRITS) p.push('E8M0_TRIT_CODES != 3^E8M0_TRITS')
  if (f.MXFP4_DENSE_TRITS !== Math.ceil(f.MXFP4_BLOCK_BITS / Math.log2(3))) p.push('MXFP4_DENSE_TRITS != ceil(136 / log2 3)')
  if (f.T27_ELEM_DENSE_BITS !== Math.ceil(f.BLOCK * f.CELL_TRITS * Math.log2(3))) p.push('T27_ELEM_DENSE_BITS != ceil(96 log2 3)')
  if (f.LOG2_3_E5 !== Math.floor(Math.log2(3) * 1e5)) p.push('LOG2_3_E5 != floor(1e5 log2 3)')
  if (f.BIT_SHARE_E3 !== Math.floor((Math.log2(27) - 4) * 1000)) p.push('BIT_SHARE_E3 != floor(1000 (log2 27 - 4))')
  if (f.BLOCK_TNF_FUNCS.length !== new Set(f.BLOCK_TNF_FUNCS).size) p.push('BLOCK_TNF_FUNCS repeats a name')
  const path = join(REPO, f.BLOCK_TNF_FILE)
  if (!existsSync(path)) p.push(`${f.BLOCK_TNF_FILE} missing`)
  else if (sha256(readFileSync(path)) !== f.BLOCK_TNF_SHA256) p.push(`${f.BLOCK_TNF_FILE}: sha256 differs from the spec`)
  return p
}

function pyLiteral(v) {
  if (typeof v === 'boolean') return v ? 'True' : 'False'
  if (Array.isArray(v)) return `[${v.map(pyLiteral).join(', ')}]`
  return JSON.stringify(v)
}

function renderPython(f, specSha, wasmSha) {
  const keys = Object.keys(f).sort()
  return [
    `# GENERATED by conformance/ternary_storage_from_spec.mjs from ${SPEC} -- do not edit.`,
    '"""Ternary-storage search parameters; the spec is the source, this file is a copy of it."""',
    '',
    `SPEC_FILE = ${JSON.stringify(SPEC)}`,
    `SPEC_SHA256 = ${JSON.stringify(specSha)}`,
    `COMPILER_WASM_SHA256 = ${JSON.stringify(wasmSha)}`,
    '',
    'SPEC = {',
    ...keys.map((k) => `    ${JSON.stringify(k)}: ${pyLiteral(f[k])},`),
    '}',
    '',
  ].join('\n')
}

export async function build() {
  const h = await helpers()
  const wasmBytes = readFileSync(WASM)
  const analyze = await h.loadCompiler(wasmBytes)
  const specText = readFileSync(join(REPO, SPEC), 'utf8')
  const problems = []
  const analysis = analyze(specText)
  const verdict = h.verdictOf(analysis)
  if (!verdict.typecheckOk || verdict.errors > 0 || verdict.discarded > 0 || !verdict.hirOk) problems.push(`compiler verdict not clean ${JSON.stringify(verdict)}`)
  problems.push(...h.compilerErrors(analysis))
  if (/[^\x00-\x7f]/.test(specText)) problems.push('non-ASCII byte in the spec')
  const moduleName = analysis.ast?.name ?? null
  if (moduleName !== EXPECTED_MODULE) problems.push(`module must be ${EXPECTED_MODULE}, is ${moduleName}`)
  let f = {}
  try {
    f = Object.fromEntries(Object.entries(h.constsOf(analysis)).map(([k, v]) => [k, v.value]))
  } catch (e) {
    problems.push(e.message)
  }
  let tests = { tests: 0, asserts: 0, failures: [] }
  if (problems.length === 0) {
    tests = h.runSpecTests(analysis, f)
    if (tests.tests === 0 || tests.asserts === 0) problems.push('no test block or no assert; the spec must test its own invariants')
    problems.push(...tests.failures.map((m) => `test ${m}`))
    problems.push(...semanticProblems(f))
  }
  const specSha = sha256(Buffer.from(specText, 'utf8'))
  const wasmSha = sha256(wasmBytes)
  const out = problems.length ? null : { [f.GENERATED[0]]: renderPython(f, specSha, wasmSha) }
  return { problems, verdict, tests, consts: Object.keys(f).length, specSha, wasmSha, out }
}

async function main() {
  const check = process.argv.includes('--check')
  const r = await build()
  console.log(`spec ${SPEC} sha256 ${r.specSha.slice(0, 16)}  wasm ${r.wasmSha.slice(0, 16)}  verdict ${JSON.stringify(r.verdict)}`)
  console.log(`constants ${r.consts}  tests ${r.tests.tests}  asserts ${r.tests.asserts}  failures ${r.tests.failures.length}`)
  if (r.problems.length) {
    for (const p of r.problems) console.log(`PROBLEM ${p}`)
    process.exit(1)
  }
  let drift = 0
  for (const [rel, text] of Object.entries(r.out)) {
    const path = join(REPO, rel)
    const cur = existsSync(path) ? readFileSync(path, 'utf8') : null
    if (cur === text) { console.log(`same   ${rel}`); continue }
    if (check) { console.log(`DRIFT  ${rel}`); drift++; continue }
    mkdirSync(dirname(path), { recursive: true })
    writeFileSync(path, text)
    console.log(`wrote  ${rel}`)
  }
  process.exit(drift ? 1 : 0)
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) main().catch((e) => { console.error(e.message); process.exit(2) })
