#!/usr/bin/env python3
"""igla-coder's 32-token generation on the AX7203 node, with retransmits and a port reopened on a
stop; parameters of specs/trinet/tern_tc_reopen_long_ax7203.t27.

A thin arm, not a copy: the runner is the 8-token reopen arm's
conformance/tern_tc_generate_reopen_ax7203.py, imported unchanged and pinned by sha256 in the spec.
That runner's main() reads two generated parameter modules by name --
tern_tc_reopen_params (this run's own) and tern_tc_generate_params (the long generation arm's) --
so this wrapper installs the long variants under exactly those names before importing it. From
there every --self-test, --refcell, preflight and board byte runs the pinned code; the pinned
runner believes it is running its own 8-token parameters and is handed 32.

    python3 tern_tc_generate_reopen_long_ax7203.py --self-test
    python3 tern_tc_generate_reopen_long_ax7203.py --refcell    # the full 32-token run, reference
                                                               # cell behind the RTL frame parser,
                                                               # losses and stalls; ~30 min
    python3 tern_tc_generate_reopen_long_ax7203.py --setkey --port /dev/cu.usbserial-110 --keys ../trinet-keys.txt

The pinned runner's flags pass through unchanged: "--self-test", "--refcell", "--setkey", "--port",
"--keys" (quoted here so `tri fpga-selftest` finds the flag and runs this arm's reopen self-test
with the long parameters, not only the 8-token ones).

The argparse help still says "8-token" in its first line: it is the pinned runner's text, kept as
is. The record is conformance/TERN_TC_GENERATE_LONG.md.

Author: Dmitrii Vasilev (@gHashTag)
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import tern_tc_generate_long_params  # noqa: E402  (generated by tern_tc_generate_long_from_spec.mjs)
import tern_tc_reopen_long_params  # noqa: E402  (generated by tern_tc_reopen_long_from_spec.mjs)

sys.modules["tern_tc_generate_params"] = tern_tc_generate_long_params
sys.modules["tern_tc_reopen_params"] = tern_tc_reopen_long_params

import tern_tc_generate_reopen_ax7203 as pinned  # noqa: E402  (unchanged, sha-pinned by the spec)

if __name__ == "__main__":
    sys.exit(pinned.main())
