#!/usr/bin/env node
// tnf16_board_from_spec.mjs -- the TNF16 board cell's parameters, generated from its spec.
//
//   node conformance/tnf16_board_from_spec.mjs            write the two generated files
//   node conformance/tnf16_board_from_spec.mjs --check    exit 1 if either file drifted
//
// Source: specs/trinet/tnf16_on_board_ax7203.t27. The file is compiled by the t27 compiler
// (wasm) and its test blocks are evaluated against its constants; the compiler's typecheck
// alone stays true for `assert 1 > 2`. The compiler and the helpers that read its AST are
// not copied here: they are imported from a gHashTag/trinity checkout (TRINITY_DIR, default
// ~/trinity), and the wasm's sha256 is written into both outputs.
//
// Outputs (paths come from the spec's GENERATED):
//   fpga/tnet/tnf16_board_params.v      `define TNF16_* macros for the RTL and testbench
//   conformance/tnf16_board_params.py   SPEC dict for the host and the vector generator

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { homedir } from 'node:os'

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const SPEC = 'specs/trinet/tnf16_on_board_ax7203.t27'
const EXPECTED_MODULE = 'trinet_tnf16_on_board_ax7203'
const TRINITY = process.env.TRINITY_DIR ?? join(homedir(), 'trinity')
const SITE = join(TRINITY, 'apps', 'website')
const WASM = join(SITE, 'public', 't27', 't27_compiler.wasm')

const sha256 = (b) => createHash('sha256').update(b).digest('hex')

async function helpers() {
  for (const p of [WASM, join(SITE, 'scripts', 'agents-from-specs.mjs')]) {
    if (!existsSync(p)) throw new Error(`${p} not found; set TRINITY_DIR to a gHashTag/trinity checkout`)
  }
  const a = await import(pathToFileURL(join(SITE, 'scripts', 'agents-from-specs.mjs')).href)
  const v = await import(pathToFileURL(join(SITE, 'scripts', 'viewport-from-spec.mjs')).href)
  return { ...a, runSpecTests: v.runSpecTests }
}

// Relations the test evaluator cannot state (no powers, no string search, no file reads).
function semanticProblems(f) {
  const p = []
  const bitLength = (n) => n.toString(2).length
  if (f.EXP_VALUES !== 3 ** f.EXP_TRITS) p.push('EXP_VALUES != 3^EXP_TRITS')
  if (f.MANT_SCALE !== 2 ** f.MANT_BITS) p.push('MANT_SCALE != 2^MANT_BITS')
  if (f.OFF_CODES !== 2 ** f.OFF_BITS) p.push('OFF_CODES != 2^OFF_BITS')
  if (f.OFF_BITS !== bitLength(f.OFFSET_MAX)) p.push('OFF_BITS != bit length of OFFSET_MAX')
  if (f.SIGN_BIT !== 2 ** f.SIGN_SHIFT) p.push('SIGN_BIT != 2^SIGN_SHIFT')
  if (f.EDGE_CODES !== f.EDGE_OFFSETS.length * f.EDGE_MANTS.length * 2) p.push('EDGE_CODES != offsets x mantissas x 2')
  if (f.CP2102N_N !== Math.round(f.CP2102N_REF_HZ / f.HOST_BAUD)) p.push('HOST_BAUD does not select CP2102N_N')
  if (f.WIRE_BAUD !== Math.floor(f.CP2102N_REF_HZ / f.CP2102N_N)) p.push('WIRE_BAUD != floor(24 MHz / N)')
  for (const line of [f.PASS_LINE, f.SIM_PASS_LINE]) {
    if (!line.includes(`${f.TOTAL_REQUESTS}/${f.TOTAL_REQUESTS} bit-exact`)) p.push(`pass line does not name ${f.TOTAL_REQUESTS}/${f.TOTAL_REQUESTS}: ${line}`)
  }
  for (const [file, want] of [[f.REF_FILE, f.REF_SHA256], [f.REF_VERSIONS_FILE, f.REF_VERSIONS_SHA256]]) {
    const path = join(REPO, file)
    if (!existsSync(path)) p.push(`${file} missing`)
    else if (sha256(readFileSync(path)) !== want) p.push(`${file}: sha256 differs from the spec`)
  }
  // The pinned vector file: its bytes, its header, its rows.
  const vpath = join(REPO, f.VEC_FILE)
  if (!existsSync(vpath)) {
    p.push(`${f.VEC_FILE} missing`)
  } else {
    const bytes = readFileSync(vpath)
    if (sha256(bytes) !== f.VEC_SHA256) p.push(`${f.VEC_FILE}: sha256 ${sha256(bytes)} != VEC_SHA256`)
    const text = bytes.toString('utf8')
    const want = [
      `# ${f.VEC_SPEC_VERSION}`, `# ladder_version=${f.REF_LADDER}`,
      `exp_trits=${f.EXP_TRITS} mant_bits=${f.MANT_BITS}`,
      `# exp_bits=${f.OFF_BITS} sign_shift=${f.SIGN_SHIFT} offset_max=${f.OFFSET_MAX} exp_offset=${f.EXP_OFFSET}`,
    ]
    for (const w of want) if (!text.includes(w)) p.push(`${f.VEC_FILE}: header lacks "${w}"`)
    const rows = text.split('\n').filter((l) => l && !l.startsWith('#'))
    const add = rows.filter((l) => l.startsWith('add ')).length
    const mul = rows.filter((l) => l.startsWith('mul ')).length
    if (add !== f.VEC_ADD || mul !== f.VEC_MUL || rows.length !== f.VEC_ROWS) p.push(`${f.VEC_FILE}: rows add ${add} mul ${mul} total ${rows.length}`)
  }
  return p
}

// Only what the RTL needs, as macros: yosys and iverilog both carry a `define across files.
function renderVerilog(f, specSha, wasmSha) {
  const d = (name, width, value) => `\`define TNF16_${name} ${width}'d${value}`
  return [
    `// GENERATED by conformance/tnf16_board_from_spec.mjs from ${SPEC} -- do not edit.`,
    `// spec sha256 ${specSha}`,
    `// t27 compiler wasm sha256 ${wasmSha}`,
    '`ifndef TNF16_BOARD_PARAMS',
    '`define TNF16_BOARD_PARAMS',
    d('MANT_BITS', 8, f.MANT_BITS),
    d('OFF_BITS', 8, f.OFF_BITS),
    d('EXP_OFFSET', 8, f.EXP_OFFSET),
    d('OFFSET_MAX', 8, f.OFFSET_MAX),
    d('SIGN_SHIFT', 8, f.SIGN_SHIFT),
    d('WORD_BITS', 8, f.WORD_BITS),
    d('CANON_NAN', 19, f.CANON_NAN),
    d('BAUD_DIV', 10, f.BAUD_DIV),
    d('SYNC0', 8, f.SYNC0),
    d('SYNC1', 8, f.SYNC1),
    d('RESP_OK', 8, f.RESP_OK),
    d('RESP_BADOP', 8, f.RESP_BADOP),
    d('OP_ADD', 8, f.OP_ADD),
    d('OP_MUL', 8, f.OP_MUL),
    d('CORE_STAGES', 8, f.CORE_STAGES),
    d('GUARD_BITS', 8, f.GUARD_BITS),
    '`endif',
    '',
  ].join('\n')
}

function pyLiteral(v) {
  if (typeof v === 'boolean') return v ? 'True' : 'False'
  if (Array.isArray(v)) return `[${v.map(pyLiteral).join(', ')}]`
  return JSON.stringify(v)
}

function renderPython(f, specSha, wasmSha) {
  const keys = Object.keys(f).sort()
  return [
    `# GENERATED by conformance/tnf16_board_from_spec.mjs from ${SPEC} -- do not edit.`,
    '"""TNF16 board cell parameters; the spec is the source, this file is a copy of it."""',
    '',
    `SPEC_FILE = ${JSON.stringify(SPEC)}`,
    `SPEC_SHA256 = ${JSON.stringify(specSha)}`,
    `COMPILER_WASM_SHA256 = ${JSON.stringify(wasmSha)}`,
    '',
    'SPEC = {',
    ...keys.map((k) => `    ${JSON.stringify(k)}: ${pyLiteral(f[k])},`),
    '}',
    '',
  ].join('\n')
}

export async function build() {
  const h = await helpers()
  const wasmBytes = readFileSync(WASM)
  const analyze = await h.loadCompiler(wasmBytes)
  const specText = readFileSync(join(REPO, SPEC), 'utf8')
  const problems = []
  const analysis = analyze(specText)
  const verdict = h.verdictOf(analysis)
  if (!verdict.typecheckOk || verdict.errors > 0 || verdict.discarded > 0 || !verdict.hirOk) problems.push(`compiler verdict not clean ${JSON.stringify(verdict)}`)
  problems.push(...h.compilerErrors(analysis))
  if (/[^\x00-\x7f]/.test(specText)) problems.push('non-ASCII byte in the spec')
  const moduleName = analysis.ast?.name ?? null
  if (moduleName !== EXPECTED_MODULE) problems.push(`module must be ${EXPECTED_MODULE}, is ${moduleName}`)
  let f = {}
  try {
    f = Object.fromEntries(Object.entries(h.constsOf(analysis)).map(([k, v]) => [k, v.value]))
  } catch (e) {
    problems.push(e.message)
  }
  let tests = { tests: 0, asserts: 0, failures: [] }
  if (problems.length === 0) {
    tests = h.runSpecTests(analysis, f)
    if (tests.tests === 0 || tests.asserts === 0) problems.push('no test block or no assert; the spec must test its own invariants')
    problems.push(...tests.failures.map((m) => `test ${m}`))
    problems.push(...semanticProblems(f))
  }
  const specSha = sha256(Buffer.from(specText, 'utf8'))
  const wasmSha = sha256(wasmBytes)
  const out = problems.length ? null : {
    [f.GENERATED[0]]: renderVerilog(f, specSha, wasmSha),
    [f.GENERATED[1]]: renderPython(f, specSha, wasmSha),
  }
  return { problems, verdict, tests, consts: Object.keys(f).length, specSha, wasmSha, out }
}

async function main() {
  const check = process.argv.includes('--check')
  const r = await build()
  console.log(`spec ${SPEC} sha256 ${r.specSha.slice(0, 16)}  wasm ${r.wasmSha.slice(0, 16)}  verdict ${JSON.stringify(r.verdict)}`)
  console.log(`constants ${r.consts}  tests ${r.tests.tests}  asserts ${r.tests.asserts}  failures ${r.tests.failures.length}`)
  if (r.problems.length) {
    for (const p of r.problems) console.log(`PROBLEM ${p}`)
    process.exit(1)
  }
  let drift = 0
  for (const [rel, text] of Object.entries(r.out)) {
    const path = join(REPO, rel)
    const cur = existsSync(path) ? readFileSync(path, 'utf8') : null
    if (cur === text) { console.log(`same   ${rel}`); continue }
    if (check) { console.log(`DRIFT  ${rel}`); drift++; continue }
    mkdirSync(dirname(path), { recursive: true })
    writeFileSync(path, text)
    console.log(`wrote  ${rel}`)
  }
  process.exit(drift ? 1 : 0)
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) main().catch((e) => { console.error(e.message); process.exit(2) })
