#!/usr/bin/env node
// uart_loss_hubfree_from_spec.mjs -- the hub-free UART loss arm's parameters, generated from its spec.
//
//   node conformance/uart_loss_hubfree_from_spec.mjs            write the generated file
//   node conformance/uart_loss_hubfree_from_spec.mjs --check    exit 1 if it drifted
//
// Source: specs/trinet/uart_loss_hubfree_ax7203.t27. Compiled by the t27 compiler (wasm), its test
// blocks evaluated against its constants, as conformance/uart_loss_diag_from_spec.mjs does; the
// compiler and the AST helpers are imported from a gHashTag/trinity checkout (TRINITY_DIR,
// default ~/trinity), not copied.
//
// Output (path from the spec's GENERATED): conformance/uart_loss_hubfree_params.py, a SPEC dict the
// runner conformance/uart_loss_hubfree_ax7203.py reads.

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { homedir } from 'node:os'

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const SPEC = 'specs/trinet/uart_loss_hubfree_ax7203.t27'
const EXPECTED_MODULE = 'trinet_uart_loss_hubfree_ax7203'
const TRINITY = process.env.TRINITY_DIR ?? join(homedir(), 'trinity')
const SITE = join(TRINITY, 'apps', 'website')
const WASM = join(SITE, 'public', 't27', 't27_compiler.wasm')

const sha256 = (b) => createHash('sha256').update(b).digest('hex')

async function helpers() {
  for (const p of [WASM, join(SITE, 'scripts', 'agents-from-specs.mjs')]) {
    if (!existsSync(p)) throw new Error(`${p} not found; set TRINITY_DIR to a gHashTag/trinity checkout`)
  }
  const a = await import(pathToFileURL(join(SITE, 'scripts', 'agents-from-specs.mjs')).href)
  const v = await import(pathToFileURL(join(SITE, 'scripts', 'viewport-from-spec.mjs')).href)
  return { ...a, runSpecTests: v.runSpecTests }
}

// Relations the test evaluator cannot state (no logarithms, no file reads). The diagnostic's runner
// and params are imported by the runner, never edited: their bytes are pinned, and every constant
// this spec repeats is read back out of the params it came from, so the two cannot drift apart.
const FROM_DIAG = ['NODE_ID', 'BAUD', 'RESP_LEN', 'FIRST_JOB_NONCE', 'JOBS_PER_PASS', 'READ_TIMEOUT_S']

function semanticProblems(f) {
  const p = []
  const where = (file) => join(REPO, file)
  const text = (file) => (existsSync(where(file)) ? readFileSync(where(file), 'utf8') : '')
  for (const [file, sha] of [[f.DIAG_SPEC_FILE, f.DIAG_SPEC_SHA256], [f.DIAG_PARAMS_FILE, f.DIAG_PARAMS_SHA256],
    [f.DIAG_RUNNER_FILE, f.DIAG_RUNNER_SHA256], [f.HARNESS_FILE, f.HARNESS_SHA256], [f.MAC32_FILE, f.MAC32_SHA256],
    [f.GENERATE_PARAMS_FILE, f.GENERATE_PARAMS_SHA256]]) {
    if (!existsSync(where(file))) p.push(`${file} missing`)
    else if (sha256(readFileSync(where(file))) !== sha) p.push(`${file}: sha256 differs from the spec`)
  }
  const num = (src, k) => {
    const m = src.match(new RegExp(`^    "${k}": (\\d+),$`, 'm'))
    return m ? Number(m[1]) : null
  }
  const diag = text(f.DIAG_PARAMS_FILE)
  for (const k of FROM_DIAG) if (num(diag, k) !== f[k]) p.push(`${k} ${f[k]} != diagnostic params ${num(diag, k)}`)
  if (num(diag, 'JOBS_PER_ARM') !== f.DIAG_JOBS_PER_ARM) p.push(`DIAG_JOBS_PER_ARM != diagnostic JOBS_PER_ARM ${num(diag, 'JOBS_PER_ARM')}`)
  const arms = diag.match(/^    "ARM_WINDOWS": \[([\d, ]+)\],$/m)
  const w = arms ? arms[1].split(',').map(Number) : []
  if (w[f.DIAG_ARM] !== f.WINDOW) p.push(`WINDOW ${f.WINDOW} != diagnostic ARM_WINDOWS[${f.DIAG_ARM}] ${w[f.DIAG_ARM]}`)
  if (num(text(f.GENERATE_PARAMS_FILE), 'JOBS_EXPECTED') !== f.JOBS_GEN) p.push('JOBS_GEN != generation JOBS_EXPECTED')
  const runner = text(f.DIAG_RUNNER_FILE)
  if (!/^def run_arm\(link, jobs, n_jobs, key, window, log=print, limit_s=None, drain=None\):$/m.test(runner)) p.push('diagnostic run_arm signature changed')
  if (!/^def summarize\(res, log=print\):$/m.test(runner)) p.push('diagnostic summarize signature changed')
  if (f.LN20_MILLI !== Math.ceil(1000 * Math.log(20))) p.push(`LN20_MILLI ${f.LN20_MILLI} != ceil(1000 ln 20)`)
  if (f.USB_VENDOR !== 0x10c4 || f.USB_PRODUCT !== 0xea60) p.push('USB_VENDOR:USB_PRODUCT is not 10c4:ea60 (CP2102N)')
  return p
}

function pyLiteral(v) {
  if (typeof v === 'boolean') return v ? 'True' : 'False'
  if (Array.isArray(v)) return `[${v.map(pyLiteral).join(', ')}]`
  return JSON.stringify(v)
}

function renderPython(f, specSha, wasmSha) {
  const keys = Object.keys(f).sort()
  return [
    `# GENERATED by conformance/uart_loss_hubfree_from_spec.mjs from ${SPEC} -- do not edit.`,
    '"""Hub-free UART loss arm parameters; the spec is the source, this file is a copy of it."""',
    '',
    `SPEC_FILE = ${JSON.stringify(SPEC)}`,
    `SPEC_SHA256 = ${JSON.stringify(specSha)}`,
    `COMPILER_WASM_SHA256 = ${JSON.stringify(wasmSha)}`,
    '',
    'SPEC = {',
    ...keys.map((k) => `    ${JSON.stringify(k)}: ${pyLiteral(f[k])},`),
    '}',
    '',
  ].join('\n')
}

export async function build() {
  const h = await helpers()
  const wasmBytes = readFileSync(WASM)
  const analyze = await h.loadCompiler(wasmBytes)
  const specText = readFileSync(join(REPO, SPEC), 'utf8')
  const problems = []
  const analysis = analyze(specText)
  const verdict = h.verdictOf(analysis)
  if (!verdict.typecheckOk || verdict.errors > 0 || verdict.discarded > 0 || !verdict.hirOk) problems.push(`compiler verdict not clean ${JSON.stringify(verdict)}`)
  problems.push(...h.compilerErrors(analysis))
  if (/[^\x00-\x7f]/.test(specText)) problems.push('non-ASCII byte in the spec')
  const moduleName = analysis.ast?.name ?? null
  if (moduleName !== EXPECTED_MODULE) problems.push(`module must be ${EXPECTED_MODULE}, is ${moduleName}`)
  let f = {}
  try {
    f = Object.fromEntries(Object.entries(h.constsOf(analysis)).map(([k, v]) => [k, v.value]))
  } catch (e) {
    problems.push(e.message)
  }
  let tests = { tests: 0, asserts: 0, failures: [] }
  if (problems.length === 0) {
    tests = h.runSpecTests(analysis, f)
    if (tests.tests === 0 || tests.asserts === 0) problems.push('no test block or no assert; the spec must test its own invariants')
    problems.push(...tests.failures.map((m) => `test ${m}`))
    problems.push(...semanticProblems(f))
  }
  const specSha = sha256(Buffer.from(specText, 'utf8'))
  const wasmSha = sha256(wasmBytes)
  const out = problems.length ? null : { [f.GENERATED[0]]: renderPython(f, specSha, wasmSha) }
  return { problems, verdict, tests, consts: Object.keys(f).length, specSha, wasmSha, out }
}

async function main() {
  const check = process.argv.includes('--check')
  const r = await build()
  console.log(`spec ${SPEC} sha256 ${r.specSha.slice(0, 16)}  wasm ${r.wasmSha.slice(0, 16)}  verdict ${JSON.stringify(r.verdict)}`)
  console.log(`constants ${r.consts}  tests ${r.tests.tests}  asserts ${r.tests.asserts}  failures ${r.tests.failures.length}`)
  if (r.problems.length) {
    for (const p of r.problems) console.log(`PROBLEM ${p}`)
    process.exit(1)
  }
  let drift = 0
  for (const [rel, text] of Object.entries(r.out)) {
    const path = join(REPO, rel)
    const cur = existsSync(path) ? readFileSync(path, 'utf8') : null
    if (cur === text) { console.log(`same   ${rel}`); continue }
    if (check) { console.log(`DRIFT  ${rel}`); drift++; continue }
    mkdirSync(dirname(path), { recursive: true })
    writeFileSync(path, text)
    console.log(`wrote  ${rel}`)
  }
  process.exit(drift ? 1 : 0)
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) main().catch((e) => { console.error(e.message); process.exit(2) })
