#!/usr/bin/env node
// uart_loss_diag_from_spec.mjs -- the UART loss diagnostic's parameters, generated from its spec.
//
//   node conformance/uart_loss_diag_from_spec.mjs            write the generated file
//   node conformance/uart_loss_diag_from_spec.mjs --check    exit 1 if it drifted
//
// Source: specs/trinet/uart_loss_diag_ax7203.t27. Compiled by the t27 compiler (wasm), its test
// blocks evaluated against its constants, as conformance/mxdot4_board_from_spec.mjs does; the
// compiler and the AST helpers are imported from a gHashTag/trinity checkout (TRINITY_DIR,
// default ~/trinity), not copied.
//
// Output (path from the spec's GENERATED): conformance/uart_loss_diag_params.py, a SPEC dict the
// runner conformance/uart_loss_diag_ax7203.py reads.

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { homedir } from 'node:os'

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const SPEC = 'specs/trinet/uart_loss_diag_ax7203.t27'
const EXPECTED_MODULE = 'trinet_uart_loss_diag_ax7203'
const TRINITY = process.env.TRINITY_DIR ?? join(homedir(), 'trinity')
const SITE = join(TRINITY, 'apps', 'website')
const WASM = join(SITE, 'public', 't27', 't27_compiler.wasm')

const sha256 = (b) => createHash('sha256').update(b).digest('hex')

async function helpers() {
  for (const p of [WASM, join(SITE, 'scripts', 'agents-from-specs.mjs')]) {
    if (!existsSync(p)) throw new Error(`${p} not found; set TRINITY_DIR to a gHashTag/trinity checkout`)
  }
  const a = await import(pathToFileURL(join(SITE, 'scripts', 'agents-from-specs.mjs')).href)
  const v = await import(pathToFileURL(join(SITE, 'scripts', 'viewport-from-spec.mjs')).href)
  return { ...a, runSpecTests: v.runSpecTests }
}

// Relations the test evaluator cannot state (no powers, no file reads). The harness is imported by
// the runner, never edited: its bytes are pinned, and the constants this spec repeats from it are
// read back out of its source here, so the two cannot drift apart.
function semanticProblems(f) {
  const p = []
  for (const [file, sha] of [[f.HARNESS_FILE, f.HARNESS_SHA256], [f.MAC32_FILE, f.MAC32_SHA256]]) {
    const path = join(REPO, file)
    if (!existsSync(path)) p.push(`${file} missing`)
    else if (sha256(readFileSync(path)) !== sha) p.push(`${file}: sha256 differs from the spec`)
  }
  const harness = existsSync(join(REPO, f.HARNESS_FILE)) ? readFileSync(join(REPO, f.HARNESS_FILE), 'utf8') : ''
  const num = (name) => {
    const m = harness.match(new RegExp(`^${name} = (0x[0-9A-Fa-f]+|\\d+)`, 'm'))
    return m ? Number(m[1]) : null
  }
  if (num('RESP_LEN') !== f.RESP_LEN) p.push(`RESP_LEN ${f.RESP_LEN} != harness ${num('RESP_LEN')}`)
  if (num('MAGIC_RESP') !== f.MAGIC_RESP) p.push(`MAGIC_RESP ${f.MAGIC_RESP} != harness ${num('MAGIC_RESP')}`)
  if (num('FIRST_JOB_NONCE') !== f.FIRST_JOB_NONCE) p.push(`FIRST_JOB_NONCE != harness ${num('FIRST_JOB_NONCE')}`)
  const seed = harness.match(/"--seed", type=int, default=(0x[0-9A-Fa-f]+)/)
  if (!seed || Number(seed[1]) !== f.SEED) p.push(`SEED ${f.SEED} != harness --seed default ${seed && seed[1]}`)
  if (!/timeout=2\)/.test(harness) || f.READ_TIMEOUT_S !== 2) p.push('READ_TIMEOUT_S is not the harness SerialLink timeout (2 s)')
  if (f.ARM_WINDOWS.length !== f.ARM_LOGS.length) p.push('ARM_WINDOWS and ARM_LOGS differ in length')
  if (new Set(f.ARM_LOGS).size !== f.ARM_LOGS.length) p.push('ARM_LOGS repeats a name')
  if (f.PRED_W64_EVENTS !== Math.floor(f.JOBS_PER_ARM / f.PRIOR_GENESYS_W64_JOBS)) p.push('PRED_W64_EVENTS != floor(JOBS_PER_ARM / PRIOR_GENESYS_W64_JOBS)')
  if (f.MIN_E64_ALONE !== Math.ceil(Math.log2(f.ALPHA_INV))) p.push('MIN_E64_ALONE != ceil(log2 ALPHA_INV)')
  if (f.NODE_ID !== 0x5452494e) p.push('NODE_ID is not 0x5452494e')
  return p
}

function pyLiteral(v) {
  if (typeof v === 'boolean') return v ? 'True' : 'False'
  if (Array.isArray(v)) return `[${v.map(pyLiteral).join(', ')}]`
  return JSON.stringify(v)
}

function renderPython(f, specSha, wasmSha) {
  const keys = Object.keys(f).sort()
  return [
    `# GENERATED by conformance/uart_loss_diag_from_spec.mjs from ${SPEC} -- do not edit.`,
    '"""UART loss diagnostic parameters; the spec is the source, this file is a copy of it."""',
    '',
    `SPEC_FILE = ${JSON.stringify(SPEC)}`,
    `SPEC_SHA256 = ${JSON.stringify(specSha)}`,
    `COMPILER_WASM_SHA256 = ${JSON.stringify(wasmSha)}`,
    '',
    'SPEC = {',
    ...keys.map((k) => `    ${JSON.stringify(k)}: ${pyLiteral(f[k])},`),
    '}',
    '',
  ].join('\n')
}

export async function build() {
  const h = await helpers()
  const wasmBytes = readFileSync(WASM)
  const analyze = await h.loadCompiler(wasmBytes)
  const specText = readFileSync(join(REPO, SPEC), 'utf8')
  const problems = []
  const analysis = analyze(specText)
  const verdict = h.verdictOf(analysis)
  if (!verdict.typecheckOk || verdict.errors > 0 || verdict.discarded > 0 || !verdict.hirOk) problems.push(`compiler verdict not clean ${JSON.stringify(verdict)}`)
  problems.push(...h.compilerErrors(analysis))
  if (/[^\x00-\x7f]/.test(specText)) problems.push('non-ASCII byte in the spec')
  const moduleName = analysis.ast?.name ?? null
  if (moduleName !== EXPECTED_MODULE) problems.push(`module must be ${EXPECTED_MODULE}, is ${moduleName}`)
  let f = {}
  try {
    f = Object.fromEntries(Object.entries(h.constsOf(analysis)).map(([k, v]) => [k, v.value]))
  } catch (e) {
    problems.push(e.message)
  }
  let tests = { tests: 0, asserts: 0, failures: [] }
  if (problems.length === 0) {
    tests = h.runSpecTests(analysis, f)
    if (tests.tests === 0 || tests.asserts === 0) problems.push('no test block or no assert; the spec must test its own invariants')
    problems.push(...tests.failures.map((m) => `test ${m}`))
    problems.push(...semanticProblems(f))
  }
  const specSha = sha256(Buffer.from(specText, 'utf8'))
  const wasmSha = sha256(wasmBytes)
  const out = problems.length ? null : { [f.GENERATED[0]]: renderPython(f, specSha, wasmSha) }
  return { problems, verdict, tests, consts: Object.keys(f).length, specSha, wasmSha, out }
}

async function main() {
  const check = process.argv.includes('--check')
  const r = await build()
  console.log(`spec ${SPEC} sha256 ${r.specSha.slice(0, 16)}  wasm ${r.wasmSha.slice(0, 16)}  verdict ${JSON.stringify(r.verdict)}`)
  console.log(`constants ${r.consts}  tests ${r.tests.tests}  asserts ${r.tests.asserts}  failures ${r.tests.failures.length}`)
  if (r.problems.length) {
    for (const p of r.problems) console.log(`PROBLEM ${p}`)
    process.exit(1)
  }
  let drift = 0
  for (const [rel, text] of Object.entries(r.out)) {
    const path = join(REPO, rel)
    const cur = existsSync(path) ? readFileSync(path, 'utf8') : null
    if (cur === text) { console.log(`same   ${rel}`); continue }
    if (check) { console.log(`DRIFT  ${rel}`); drift++; continue }
    mkdirSync(dirname(path), { recursive: true })
    writeFileSync(path, text)
    console.log(`wrote  ${rel}`)
  }
  process.exit(drift ? 1 : 0)
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) main().catch((e) => { console.error(e.message); process.exit(2) })
