#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Simulate every repaired wrapper's conversion stages, not just the one.

Pass 106 tested corona_compute_gf16_div and found six defects in a file that three
careful readings had already repaired. The other eight wrappers repaired alongside it
-- gf4, gf8 and gf16 in sqrt and quire, and gf4 and gf8 in div -- were still verified
only by construction, which pass 106 showed is not enough.

The conversion stages do not depend on the operation: a wrapper decodes its operand
into binary32 and packs the binary32 result back, whatever sits between. So one golden
per format covers all three operations, and the testbench differs only in the module
name it instantiates.

    decode   the code's exact value, as binary32
    pack     the binary32 value, rounded to the format, with its own overflow,
             underflow and special-value behaviour

Exhaustive for gf4 and gf8 and gf16 -- 16, 256 and 65,536 codes -- since all three
formats are small enough to enumerate completely.

    python3 conformance/wrapper_conversion_conformance.py [--cell gf16_div] [--limit N]
"""
from __future__ import annotations

import argparse
import bisect
import os
import struct
import subprocess
import sys
import tempfile
from fractions import Fraction

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(HERE, "..", "research"))

from gf_ref import FORMATS                                   # noqa: E402
from verify_add_oracle import _grid                          # noqa: E402

RTL = os.path.join(HERE, "..", "fpga", "openxc7-synth")
CELLS = [(f, op) for f in ("gf4", "gf8", "gf16")
         for op in ("div", "sqrt", "quire")]

TB = """`timescale 1ns / 1ps
// generated by conformance/wrapper_conversion_conformance.py -- do not edit
module STARTUPE2 #(parameter PROG_USR = "FALSE", parameter SIM_CCLK_FREQ = 0.0)
    (output CFGCLK, output reg CFGMCLK, output EOS,
     input CLK, input GSR, input GTS, input KEYCLEARB, input PACK,
     input USRCCLKO, input USRCCLKTS, input USRDONEO, input USRDONETS);
    assign CFGCLK = 1'b0;
    assign EOS = 1'b1;
    initial CFGMCLK = 1'b0;
    always #5 CFGMCLK = ~CFGMCLK;
endmodule

module tb_conv;
    reg rst_n = 1'b0;
    wire uart_tx;
    wire [3:0] led;
    {module} dut (.rst_n(rst_n), .uart_rx(1'b1), .uart_tx(uart_tx), .led(led));
    integer code;
    reg [{wmsb}:0] a_in;
    reg [31:0] q_in;
    initial begin
        #40 rst_n = 1'b1;
        #40;
        while (1) begin
            code = $fscanf('h8000_0000, "%h %h\\n", a_in, q_in);
            if (code != 2) $finish;
            force dut.a_reg = a_in;
            force dut.comp_result = q_in;
            #1;
            $display("IN %h %08h OUT %08h %h",
                     a_in, dut.fp32_a, q_in, dut.q_result);
        end
    end
endmodule
"""


# ------------------------------------------------------------------ golden

def value_of(fmt, code: int):
    s = (code >> fmt.sign_shift) & 1
    e = (code >> fmt.mant_bits) & fmt.exp_max
    m = code & fmt.mant_max
    if fmt.has_inf and e == fmt.exp_max:
        return ("nan" if m else "inf"), s, None
    if e == 0:
        return "finite", s, Fraction(m, 1 << fmt.mant_bits) * Fraction(2) ** (1 - fmt.bias)
    return "finite", s, (1 + Fraction(m, 1 << fmt.mant_bits)) * Fraction(2) ** (e - fmt.bias)


def to_binary32(fmt, code: int) -> int:
    kind, s, v = value_of(fmt, code)
    if kind == "nan":
        return 0x7FC00000
    if kind == "inf":
        return 0xFF800000 if s else 0x7F800000
    if v == 0:
        return 0x80000000 if s else 0x00000000
    f = float(v) * (-1 if s else 1)
    return struct.unpack(">I", struct.pack(">f", f))[0]


def round_to_format(fmt, mag: Fraction, sign: int) -> int:
    vals, codes = _grid(fmt)
    sbit = sign << fmt.sign_shift
    if mag > vals[-1]:
        top = fmt.exp_max - 1 if fmt.has_inf else fmt.exp_max
        ulp = Fraction(2) ** (top - fmt.bias - fmt.mant_bits)
        return (fmt.pos_overflow(sign) if mag >= vals[-1] + ulp / 2
                else sbit | codes[-1])
    i = bisect.bisect_left(vals, mag)
    if vals[i] == mag:
        return sbit | codes[i]
    lo_v, lo_c, hi_v, hi_c = vals[i - 1], codes[i - 1], vals[i], codes[i]
    d_lo, d_hi = mag - lo_v, hi_v - mag
    if d_lo < d_hi:
        return sbit | lo_c
    if d_hi < d_lo:
        return sbit | hi_c
    return sbit | (lo_c if lo_c % 2 == 0 else hi_c)


def from_binary32(fmt, word: int) -> int:
    f = struct.unpack(">f", struct.pack(">I", word))[0]
    if f != f:
        return fmt.quiet_nan if fmt.has_inf else 0
    if f in (float("inf"), float("-inf")):
        if not fmt.has_inf:
            return fmt.pos_overflow(1 if f < 0 else 0)
        return fmt.neg_inf if f < 0 else fmt.pos_inf
    if f == 0.0:
        return fmt.neg_zero if (word >> 31) & 1 else fmt.pos_zero
    v = Fraction(f)
    sign = 1 if v < 0 else 0
    return round_to_format(fmt, -v if v < 0 else v, sign)


# ------------------------------------------------------------------ simulate

def run_cell(fname: str, op: str, limit: int):
    fmt = FORMATS[fname]
    width = 1 + fmt.exp_bits + fmt.mant_bits
    module = f"corona_compute_{fname}_{op}_ax7203"
    src = os.path.join(RTL, f"{module}.v")
    if not os.path.exists(src):
        return None, f"{module}.v is not in the tree"

    with tempfile.TemporaryDirectory() as td:
        tbp = os.path.join(td, "tb.v")
        open(tbp, "w").write(TB.format(module=module, wmsb=width - 1))
        exe = os.path.join(td, "tb")
        deps = [os.path.join(RTL, d) for d in
                ("gf_div_param.v", "gf_sqrt_param.v", "gf_quire_param.v",
                 "gf_adder_param.v", "gf_mul_param.v")
                if os.path.exists(os.path.join(RTL, d))]
        r = subprocess.run(["iverilog", "-g2012", "-o", exe, tbp, src] + deps,
                           capture_output=True, text=True)
        if r.returncode != 0:
            return None, (r.stdout + r.stderr).strip().splitlines()[-1][:110]

        codes = list(range(1 << width))
        if limit:
            codes = codes[:limit]
        pairs = [(c, to_binary32(fmt, c)) for c in codes]
        stdin = "".join(f"{a:0{(width + 3) // 4}X} {q:08X}\n" for a, q in pairs)
        sim = subprocess.run(["vvp", exe], input=stdin,
                             capture_output=True, text=True)
        got = []
        for line in sim.stdout.splitlines():
            p = line.split()
            if len(p) == 6 and p[0] == "IN" and p[3] == "OUT":
                got.append((int(p[2], 16), int(p[5], 16)))
        if len(got) != len(pairs):
            return None, f"simulator returned {len(got)} of {len(pairs)} results"

        dec = pack = 0
        first = []
        for (code, want_fp), (got_fp, got_gf) in zip(pairs, got):
            want_gf = from_binary32(fmt, want_fp)
            if got_fp == want_fp:
                dec += 1
            elif len(first) < 2:
                first.append(f"decode 0x{code:0{(width+3)//4}X} want 0x{want_fp:08X} "
                             f"got 0x{got_fp:08X}")
            if got_gf == want_gf:
                pack += 1
            elif len(first) < 2:
                first.append(f"pack 0x{want_fp:08X} want 0x{want_gf:04X} "
                             f"got 0x{got_gf:04X}")
        return (len(pairs), dec, pack, first), None


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--cell", help="one cell, e.g. gf16_div")
    ap.add_argument("--limit", type=int, default=0)
    args = ap.parse_args()

    cells = CELLS
    if args.cell:
        f, _, op = args.cell.partition("_")
        cells = [(f, op)]

    print(f"{'cell':<16} {'codes':>7} {'decode':>16} {'pack':>16}")
    failed = 0
    skipped = 0
    for fname, op in cells:
        res, err = run_cell(fname, op, args.limit)
        if err:
            skipped += 1
            print(f"  {fname}_{op:<10} SKIPPED -- {err}")
            continue
        n, dec, pack, first = res
        mark = "" if (dec == n and pack == n) else "   <-- FAIL"
        if mark:
            failed += 1
        print(f"  {fname}_{op:<10} {n:>7} {dec:>10}/{n:<6} {pack:>10}/{n:<6}{mark}")
        for line in first:
            print(f"      {line}")

    print(f"\ncells exact in both directions : {len(cells) - failed - skipped}")
    print(f"cells with a divergence        : {failed}")
    print(f"cells not simulated            : {skipped}")
    print("""
Conversion stages only. The operation between them is forced rather than exercised,
and no hardware is involved.""")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
