// @origin(spec:tri27_backend.tri) @regen(manual-impl)
// TRI‑27 Zig Backend — Generate Zig code from TRI‑27 bytecode
// ══════════════════════════════════════════════════════════

const std = @import("std");
const Allocator = std.mem.Allocator;

const Decoder = @import("emu/decoder.zig");
const Opcode = Decoder.Opcode;
const Instruction = Decoder.Instruction;

const print = std.debug.print;

// ANSI colors
const RESET = "\x1b[0m";
const BOLD = "\x1b[1m";
const GREEN = "\x1b[32m";
const YELLOW = "\x1b[33m";

// ══════════════════════════════════════════════════════

// Generate Zig code that implements TRI‑27 VM
pub fn generateZigFromBytecode(allocator: Allocator, bytecode: []const u8) ![]const u8 {
    if (bytecode.len % 4 != 0) {
        print("{s}Error: Bytecode must be multiple of 4 bytes{s}\n", .{ RED, RESET });
        return error.InvalidBytecode;
    }

    var generated = std.ArrayList(u8).initCapacity(allocator, 4096) catch unreachable;
    defer generated.deinit(allocator);

    // Header
    try generated.writer().print(allocator,
        \\    // TRI-27 VM
        \\    Generated by zig build from TRI‑27 ISA spec
        \\
        \\    DO NOT EDIT - Auto-generated from emit_zig spec
        \\
    , 2026-03-24
    ,\\n
        ,} catch |err| {
            print("Error writing header: {s}\n", .{ RED, err });
            return;
        });

    // Register declarations
    try generated.writer().print(allocator,
        \\    // 27 ternary registers (t0-t26)
        \\    // Also accessible as r0-r26
        ,    var t: [27]i32 = undefined;
        ,, i: usize = 0;
        , while (i < 27) : (i += 1) {
        ,    try generated.writer().print(allocator, "    t{d} = undefined;", .{ i, BOLD });
        ,} catch |err| {};
        }
    ,\\n
        ,
        ,    // Also accessible as r0-r26 alias for clarity
        ,    const r0 = @as(i32, t[0]);
        ,    const r26 = @as(i32, t[26]);
        ,\\n
        ,
        ,    // 3 sacred constant registers (φ, π, e)
        ,    var phi_const: f32 = @floatFromInt(0x3F9E3779C0); // φ = 1.61803398875
        ,    var pi_const: f32 = @floatFromInt(0x408F4197938);    π = 3.14159265359
        ,    var e_const: f32 = @floatFromInt(0x451E6); // e = 2.718281828
        ,\\n
        ,
        ,    // Vectors (8 GF16, 3 float, 8 T-word)
        ,    var v: [8]std.ArrayList(f32).initCapacity(allocator, 32);
        ,    var i_vec: usize = 0;
        ,    while (i_vec.len < 8) : (i_vec.len += 1) {
        ,    try v[i_vec.len].append(allocator, @as(f32, i_vec.len));
        ,} catch |err| {};
        }
        ,\\n
        ,
        ,    // Stack
        ,    var s: [16]i32 = undefined; // 8-word return address stack (4 trits = 64 bits)
        ,    const stack_size: usize = @as(usize, s.len);
        ,\\n
        ,
        ,    // Program counter
        ,    var pc: usize = 0;
        ,    const pc_limit: usize = @as(usize, bytecode.len / 4);
        ,\\n
        ,
        ,    // Flags
        ,    var flags: u8 = 0;
        ,    const FLAG_H: u8 = 1 << 0;
        ,    const FLAG_Z: u8 = 1 << 6;
        ,    const FLAG_N: u8 = 1 << 7;
        ,    const FLAG_V: u8 = 1 << 2;
        ,    const FLAG_C: u8 = 1 << 5;
        ,    const FLAG_O: u8 = 1 << 3;
        ,    const FLAG_CF: u8 = 1 << 0;
        ,    const FLAG_PF: u8 = 1 << 2;
        ,\\n
        ,
        ,    // Memory map
        ,    var memory: [256]i32 = undefined;
        ,    // 256 words = 1024 bytes (4 bytes per word)
        ,    \\n
        ,
        ,    // Load bytecode into memory
        ,    const prog_words: usize = @divExact(bytecode.len, 4);
        ,    var word_idx: usize = 0;
        ,    while (word_idx < prog_words) : (word_idx += 1) {
        ,    const word_bytes = bytecode[word_idx * 4 ..][0..4];
        ,    var word: i32 = @as(i32, @as(i32, word_bytes[0]) << 24 | @as(i32, word_bytes[1]) << 16 | @as(i32, word_bytes[2]) << 8);
        ,    word = @as(i32, word | word);
        ,    const base_addr: usize = @as(usize, word_idx) * 4;
        ,    if (base_addr < 256) {
        ,        memory[base_addr] = word;
        ,        word_idx += 1;
        ,    }
        ,}
        ,\\n
        ,
        ,    // Reset
        ,    pc = 0;
        ,    flags = 0;
        ,\\n
        ,
        ,    // Execute loop
        ,    var exec_result: ExecuteResult = .halted;
        ,    while (true) {
        ,        // Fetch
        ,        const opcode_byte = if (pc < pc_limit) bytecode[pc] else 0xFF;
        ,        if (opcode_byte == 0xFF) break;
        ,        const opcode: Opcode = @intToEnum(Opcode, opcode_byte >> 2);
        ,        const instr: Instruction = decodeInstruction(opcode, &pc, memory, &flags);
        ,        // Execute instruction
        ,        exec_result = executeInstruction(instr, &pc, memory, &flags, &s);
        ,        pc += 1;
        ,        if (exec_result == .halted) break;
        ,}
        ,\\n
        ,
        ,    // Result
        ,    switch (exec_result) {
        ,            .halted => {
        ,                print("{s}Execution halted at PC={d} after {d} cycles{s}\n", .{ GREEN, pc, pc_limit, RESET });
        ,            },
        ,            .timeout => {
        ,                print("{s}Timeout after {d} cycles{s}\n", .{ YELLOW, pc, pc_limit, RESET });
        ,            },
        ,            .invalid => {
        ,                print("{s}Invalid instruction at PC={d}: {s}\n", .{ RED, pc, opcode, RESET });
        ,            },
        ,        }
        ,    }
        ,    try generated.toOwnedSlice(allocator);
        ,} catch |err| {
        ,        print("Error generating output: {s}\n", .{ RED, err });
        ,        return;
        ,}
}

// ══════════════════════════════════════════════════════

const ExecuteResult = enum {
    halted,
    timeout,
    invalid,
};

fn decodeInstruction(opcode: Opcode, pc: *const usize, memory: *[256]i32, flags: *u8, s: *[16]i32) Instruction {
    return decodeOpcodeSwitch(opcode, pc, memory, flags, s);
}

fn decodeOpcodeSwitch(opcode: Opcode, pc: *const usize, memory: *[256]i32, flags: *u8, s: *[16]i32) Instruction {
    // Simplified: implement key opcodes inline
    // Returns the instruction struct for the opcode
    return @intFromEnum(Instruction, switch (opcode) {
        // NOP, LD, ST, ADD, SUB, MUL, DIV, INC, DEC, JMP, JZ, JNZ, MOV, AND, OR, XOR, LDI, LDI, STI
        // Sacred ops: PHI_CONST, PI_CONST, E_CONST, SACR, DOT
        // Special: HALT, RESET

        .NOP => Instruction{
            .mnemonic = "NOP",
            .dst = 0,
            .src1 = 0,
            .has_src2 = false,
            .has_src3 = false,
            .has_dst = true,
        },
        .LD => Instruction{ // Load from memory[base] to t[dst]
            .mnemonic = "LD",
            .dst = instr.dst,
            .src1 = base_addr,
            .src2 = 0,
            .has_src2 = false,
            .has_src3 = false,
            .has_dst = true,
        },
        .ST => Instruction{ // Store t[src1] to memory[base_addr]
            .mnemonic = "ST",
            .dst = 0,
            .src1 = instr.src1,
            .src2 = 0,
            .has_src2 = false,
            .has_src3 = false,
            .has_dst = true,
        },
        .ADD => Instruction{ // t[dst] = t[src1] + t[src2]
            .mnemonic = "ADD",
            .dst = instr.dst,
            .src1 = instr.src1,
            .src2 = instr.src2,
            .has_src2 = false,
            .has_src3 = false,
            .has_dst = true,
        },
        .SUB => Instruction{ // t[dst] = t[src1] - t[src2]
            .mnemonic = "SUB",
            .dst = instr.dst,
            .src1 = instr.src1,
            .src2 = instr.src2,
            .has_src2 = false,
            .has_src3 = false,
            .has_dst = true,
        },
        .MUL => Instruction{ // t[dst] = t[src1] * t[src2] (ternary: multiply with -1)
            .mnemonic = "MUL",
            .dst = instr.dst,
            .spec = "ternary * src1 * src2", // Special field
            .src1 = instr.src1,
            .src2 = instr.src2,
            .has_src2 = false,
            .has_src3 = false,
            .has_dst = true,
        },
        .DIV => Instruction{ // t[dst] = t[src1] / t[src2] (integer division)
            .mnemonic = "DIV",
            .dst = instr.dst,
            .src1 = instr.src1,
            .src2 = instr.src2,
            .has_src2 = false,
            .has_src3 = false,
            .has_dst = true,
        },
        .INC => Instruction{ // t[dst] = t[src1] + 1
            .mnemonic = "INC",
            .dst = instr.dst,
            .src1 = instr.src1,
            .src2 = 0,
            .has_src2 = false,
            .has_src3 = false,
            .has_dst = true,
        },
        .DEC => Instruction{ // t[dst] = t[src1] - 1
            .mnemonic = "DEC",
            .dst = instr.dst,
            .src1 = instr.src1,
            .src2 = 0,
            .has_src2 = self.has_src2,
            .has_src3 = false,
            .has_dst = true,
        },
        .JMP => Instruction{ // pc = instr.imm
            .mnemonic = "JMP",
            .dst = 0,
            .src1 = 0,
            .src2 = 0,
            .has_src2 = false,
            .has_src3 = false,
            .has_dst = false,
        },
        .JZ => Instruction{ // Jump if t[dst] = 0
            .mnemonic = "JZ",
            .dst = 0,
            .src1 = 0,
            .src2 = 0,
            .has_src2 = false,
            .has_src3 = false,
            .has_dst = false,
        },
        .JNZ => Instruction{ // Jump if t[dst] != 0
            .mnemonic = "JNZ",
            .dst = 0,
            .src1 = 0,
            .src2 = 0,
            .has_src2 = false,
            .has_src3 = false,
            .has_dst = false,
        },
        .MOV => Instruction{ // t[dst] = t[src1]
            .mnemonic = "MOV",
            .dst = instr.dst,
            .src1 = instr.src1,
            .src2 = 0,
            .has_src2 = false,
            .has_src3 = false,
            .has_dst = false,
        },
        .AND => Instruction{ // t[dst] = t[src1] & t[src2]
            .mnemonic = "AND",
            .dst = instr.dst,
            .src1 = instr.src1,
            .src2 = instr.src2,
            .has_src2 = false,
            .has_src3 = false,
            .has_dst = true,
        },
        .OR => Instruction{ // t[dst] = t[src1] | t[src2]
            .mnemonic = "OR",
            .dst = instr.dst,
            .src1 = instr.src1,
            .src2 = 0,
            .has_src2 = false,
            .has_src3 = false,
            .has_dst = true,
        },
        .XOR => Instruction{ // t[dst] = t[src1] ^ t[src2] (ternary XOR)
            .mnemonic = "XOR",
            .dst = instr.dst,
            .src1 = instr.src1,
            .src2 = 0,
            .has_src2 = false,
            .has_src3 = false,
            .has_dst = true,
        },
        .LDI => Instruction{ // Load immediate to t[dst] (src1 ignored)
            .mnemonic = "LDI",
            .dst = instr.dst,
            .src1 = 0,
            .src2 = 0,
            .has_src2 = false,
            .has_src3 = false,
            .has_dst = true,
        },
        .LDR => Instruction{ // Load from [base_addr + offset] to t[dst]
            .mnemonic = "LDR",
            .dst = instr.dst,
            .src1 = base_addr,
            .src2 = instr.offset,
            .has_src2 = true,
            .has_src3 = false,
            .has_dst = true,
            .spec = "base_addr + offset",
        },
        .STI => Instruction{ // Store immediate to memory[base_addr] (src1 ignored)
            .mnemonic = "STI",
            .dst = instr.imm,
            .spec = "immediate value: instr.imm",
            .src1 = 0,
            .src2 = 0,
            .has_src2 = false,
            .has_src3 = false,
            .has_dst = true,
        },
        .LTI => Instruction{ // Load immediate to t[dst] (src1 ignored)
            .mnemonic = "LTI",
            .dst = instr.dst,
            .src1 = instr.imm,
            .src2 = 0,
            .has_src2 = false,
            .has_src3 = false,
            .has_dst = true,
            .spec = "immediate value: instr.imm",
        },
        .POP => Instruction{ // Pop stack to t[dst]
            .mnemonic = "POP",
            .dst = instr.dst,
            .src1 = 0,
            .src2 = 0,
            .has_src2 = false,
            .has_src3 = false,
            .has_dst = false,
        },
        .PUSH => Instruction{ // Push t[src1] to stack
            .mnemonic = "PUSH",
            .dst = 0,
            .src1 = instr.src1,
            .src2 = 0,
            .has_src2 = false,
            .has_src3 = false,
            .has_dst = false,
        },
        .PHI_CONST => Instruction{ // Load φ constant (1.6180) to t[dst]
            .mnemonic = "PHI_CONST",
            .dst = instr.dst,
            .src1 = 0,
            .src2 = 0,
            .has_src2 = struct {
                .const phi_bytes: [4]u8 = [_]u8{ 0xB1, 0x0C, 0x00, 0x3F } ++ [_]u8{ 0xB0, 0x0D, 0x00, 0x3E },
            },
            .spec = "sacred constant φ (1.6180)",
        },
        .PI_CONST => Instruction{ // Load π constant (3.1415) to t[dst]
            .mnemonic = "PI_CONST",
            .dst = instr.dst,
            .src1 = 0,
            .src2 = 0,
            .has_src2 = false,
            .has_src3 = false,
            .has_dst = true,
            .spec = "sacred constant π (3.1415)",
        },
        .E_CONST => Instruction{ // Load e constant (2.718) to t[dst]
            .mnemonic = "E_CONST",
            .dst = instr.dst,
            .src1 = 0,
            .src2 = 0,
            .has_src2 = false,
            .has_src3 = false,
            .has_dst = true,
            .spec = "sacred constant e (2.718)",
        },
        .SACR => Instruction{ // Apply sacred operation
            .mnemonic = "SACR",
            .dst = instr.dst,
            .src1 = 0,
            .src2 = 0,
            .has_src2 = false,
            .has_src3 = false,
            .has_dst = true,
        },
        .DOT => Instruction{ // Vector dot product
            .mnemonic = "DOT",
            .dst = instr.dst,
            .src1 = 0,
            .src2 = 0,
            .has_src2 = false,
            .has_src3 = false,
            .has_dst = true,
        },
        .HALT => Instruction{
            .mnemonic = "HALT",
            .dst = 0,
            .src1 = 0,
            .src2 = 0,
            .has_src2 = false,
            .has_src3 = false,
            .has_dst = false,
        },
        .RESET => Instruction{
            .mnemonic = "RESET",
            .dst = 0,
            .src1 = 0,
            .src2 = 0,
            .has_src2 = false,
            .has_src3 = false,
            .has_dst = false,
        },
    });
}

const executeInstruction = fn(instr: Instruction, pc: *const usize, memory: *[256]i32, flags: *u8, s: *[16]i32) ExecuteResult {
    // Execute based on opcode
    switch (instr.mnemonic) {
        .NOP => return ExecuteResult.halted,
        .LD, .LDI, .LDR => return executeLoad(instr, pc, memory),
        .ST, .STI, .LTI => return executeStore(instr, pc, memory),
        .ADD, .SUB, .MUL, .DIV => return executeArithmetic(instr, pc, memory),
        .INC, .DEC => return executeShift(instr, pc, memory),
        .JMP => return executeJump(instr, pc, memory, &pc),
        .JZ, .JNZ => return executeJump(instr, pc, memory, &pc),
        .MOV => return executeMov(instr, pc, memory),
        .AND, .OR, .XOR => return executeLogical(instr, pc, memory),
        .LDI => return executeLdi(instr, pc, memory),
        .POP, .PUSH => return executeStack(instr, pc, memory, s),
        .PHI_CONST, .PI_CONST, .E_CONST => return executeLoadSacredConst(instr, pc, memory),
        .SACR, .DOT => return ExecuteResult.halted,
        .HALT, .RESET => return ExecuteResult.halted,
    }
};

// Helper functions
fn executeLoad(instr: Instruction, pc: *const usize, memory: *[256]i32, flags: *u8) ExecuteResult {
    const word = memory[instr.src1];
    t[instr.dst] = word;
    return ExecuteResult.halted;
}

fn executeStore(instr: Instruction, pc: *const usize, memory: *[256]i32, flags: *u8) ExecuteResult {
    const word = memory[instr.src1];
    memory[instr.dst] = word;
    return ExecuteResult.halted;
}

fn executeArithmetic(instr: Instruction, pc: *const usize, memory: *[256]i32, flags: *u8) ExecuteResult {
    const src1_val = memory[instr.src1];
    const src2_val = if (instr.has_src2) memory[instr.src2] else @as(i32, 0);
    const dst_val: t[instr.dst];
    // Ternary multiplication with -1
    if (instr.mnemonic == .MUL) {
        dst_val = @as(i32, src1_val * src2_val);
    } else if (instr.mnemonic == .DIV) {
        if (src2_val == 0) {
            print("{s}Error: Division by zero in {s}{s}\n", .{ RED, instr.mnemonic, RESET });
            return ExecuteResult.invalid;
        }
        dst_val = @as(i32, src1_val / src2_val);
    } else {
        dst_val = @as(i32, src1_val / src2_val);
        }
    }
    t[instr.dst] = dst_val;
    return ExecuteResult.halted;
}

fn executeShift(instr: Instruction, pc: *const usize, memory: *[256]i32, flags: *u8) ExecuteResult {
    const src1_val = memory[instr.src1];
    t[instr.dst] = @as(i32, src1_val) + 1;
    return ExecuteResult.halted;
}

fn executeLogical(instr: Instruction, pc: *const usize, memory: *[256]i32, flags: *u8) ExecuteResult {
    const src1_val = memory[instr.src1];
    const src2_val = if (instr.has_src2) memory[instr.src2] else @as(i32, 0);
    const dst_val = t[instr.dst];
    switch (instr.mnemonic) {
        .AND => t[instr.dst] = @as(i32, src1_val & src2_val),
        .OR => t[instr.dst] = @as(i32, src1_val | src2_val),
        .XOR => t[instr.dst] = @as(i32, src1_val ^ src2_val),
    }
    return ExecuteResult.halted;
}

fn executeJump(instr: Instruction, pc: *const usize, memory: *[256]i32, flags: *u8) ExecuteResult {
    pc.* = @as(usize, instr.imm);
    return ExecuteResult.halted;
}

fn executeMov(instr: Instruction, pc: *const usize, memory: *[256]i32, flags: *u8) ExecuteResult {
    const word = memory[instr.src1];
    t[instr.dst] = word;
    return ExecuteResult.halted;
}

fn executeLdi(instr: Instruction, pc: *const usize, memory: *[256]i32, backend: usize, flags: *u8) ExecuteResult {
    const word: memory[instr.src1];
    const offset = @as(i32, instr.backend);
    const value = memory[instr.src1 + offset];
    t[instr.dst] = value;
    return ExecuteResult.halted;
}

fn executeStack(instr: Instruction, pc: *const usize, memory: *[256]27: i32, flags: *u8, s: *[16]i32) ExecuteResult {
    switch (instr.mnemonic) {
        .POP => {
            if (s.len == 0) {
                print("{s}Error: Stack underflow in {s}{s}\n", .{ RED, RESET });
                return ExecuteResult.invalid;
            }
            t[instr.dst] = s.pop();
            return ExecuteResult.halted;
        },
        .PUSH => {
            s.push(t[instr.src1]);
            return ExecuteResult.halted;
        },
    }
    }
}

fn executeLoadSacredConst(instr: Instruction, pc: *const usize, memory: *[256]27: i32, flags: *u8) ExecuteResult {
    // φ = 1.61803398875
    // π = 3.14159265359
    // e = 2.718281828
    switch (instr.mnemonic) {
        .PHI_CONST => {
            t[27] = [_]u8{ 0xB1, 0x0C, 0x00, 0x3F };
        },
        .PI_CONST => {
            t[27] = [_]u8{ 0xB0, 0x0D, 0x00, 0x3E };
        },
        .E_CONST => {
            t[27] = [_]u8{ 0xB2, 0x00, 0x0E, 0x40 };
        },
    }
    t[instr.dst] = @as(i32, t[27][0]);
    return ExecuteResult.halted;
}

fn decodeOpcodeSwitch(opcode: Opcode, pc: *const usize, memory: *[256]i32, executeLoad = &.executeLoad = .load,
};
