# ═══════════════════════════════════════════════════════════════════════════════
# VSA Pipeline Constraints — KOSCHEI Week 4
# ═══════════════════════════════════════════════════════════════════════════════
#
# Target: Digilent Arty A7-100T (XC7A100T-CSG324)
# Clock: 100 MHz onboard oscillator
# UART: 115200 baud for FPGA → Host communication
# LED: T23 for pipeline activity indication
#
# φ² + 1/φ² = 3
#
# ═══════════════════════════════════════════════════════════════════════════════

# ═══════════════════════════════════════════════════════════════════════════════
# CLOCK (100 MHz onboard oscillator)
# ═══════════════════════════════════════════════════════════════════════════════

set_property -dict {PACKAGE_PIN E3    IOSTANDARD LVCMOS33} [get_ports clk]
create_generated_clock -name clk_100mhz -source [get_ports clk] \
    -multiply_by 1 -divide_by 1 [get_pins vsa_pipeline_256_top/clk]

# ═══════════════════════════════════════════════════════════════════════════════
# RESET (Button C0 - active high with pull-down)
# ═══════════════════════════════════════════════════════════════════════════════

set_property -dict {PACKAGE_PIN C9    IOSTANDARD LVCMOS33 PULLDOWN true} [get_ports rst]

# ═══════════════════════════════════════════════════════════════════════════════
# LED DEBUG (T23 - Yellow LED near RGB LEDs)
# ═══════════════════════════════════════════════════════════════════════════════

set_property -dict {PACKAGE_PIN T14   IOSTANDARD LVCMOS33} [get_ports led]

# ═══════════════════════════════════════════════════════════════════════════════
# UART (FTDI USB → Serial, 115200 baud)
# ═══════════════════════════════════════════════════════════════════════════════
#
# TX: FPGA → Host (data output)
# RX: Host → FPGA (commands input)
# RTS: Reset trigger (optional, uses button C0)
#

# UART TX (FPGA → Host, pin on J1 USB-UART)
set_property -dict {PACKAGE_PIN A9    IOSTANDARD LVCMOS33} [get_ports uart_tx]

# UART RX (Host → FPGA, pin on J1 USB-UART)
set_property -dict {PACKAGE_PIN D10   IOSTANDARD LVCMOS33 PULLDOWN true} [get_ports uart_rx]

# ═══════════════════════════════════════════════════════════════════════════════
# ADDITIONAL LEDs (Optional status indicators)
# ═══════════════════════════════════════════════════════════════════════════════

# LED 0-4: Status (pipeline stage activity)
set_property -dict {PACKAGE_PIN H17   IOSTANDARD LVCMOS33} [get_ports status_led[0]]
set_property -dict {PACKAGE_PIN K15   IOSTANDARD LVCMOS33} [get_ports status_led[1]]
set_property -dict {PACKAGE_PIN J13   IOSTANDARD LVCMOS33} [get_ports status_led[2]]
set_property -dict {PACKAGE_PACKET N14   IOSTANDARD LVCMOS33} [get_ports status_led[3]]
set_property -dict {PACKAGE_PIN M14   IOSTANDARD LVCMOS33} [get_ports status_led[4]]

# ═══════════════════════════════════════════════════════════════════════════════
# TIMING CONSTRAINTS
# ═══════════════════════════════════════════════════════════════════════════════

# Primary clock: 100 MHz = 10 ns period
set_property -dict {IS_LOC_FIXED 1 IS_HIER_FIXED 1} [get_ports clk]

# Generated clocks for pipeline stages (should all derive from 100 MHz)
# Target: 50 MHz operation = 20 ns period (easily achievable)

# UART baud rate: 115200
# Bit time = 1/115200 ≈ 8.68 µs
# No special timing needed (async protocol)

# ═══════════════════════════════════════════════════════════════════════════════
# PLACEMENT UTILIZATION (Target: <10% of XC7A100T resources)
# ═══════════════════════════════════════════════════════════════════════════════
#
# VSA Pipeline uses approximately:
# - 256 trit multipliers (LUT5)
# - 256-input majority vote (LUT6)
# - 256-bit population count
# - Pipeline registers (FF)
#
# Estimated: <2000 LUT, <500 FF (<2% of device)
#

# pblock_placement (auto-generated by openxc7-synth)

# φ² + 1/φ² = 3 = TRINITY
