# ============================================================================
# φ-ARITHMETIC TOP LEVEL — QMTECH Artix-7 XC7A100T-1FGG676C Constraints
# ============================================================================
#
# Demonstrates φ² = φ + 1 → 0 DSP48 multiplication
#
# ⚠️ CRITICAL: LED on T23 is ACTIVE-LOW!
#   led = 0 → LED ON  |  led = 1 → LED OFF
#   Verilog: assign led = ~led_state;
#
# Generated by TRI sacred-const phi-arith
# φ² + 1/φ² = 3 = TRINITY
#
# ============================================================================

# Clock: 50 MHz oscillator (U22)
set_property PACKAGE_PIN U22 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]

# LED: T23 (ACTIVE-LOW! Must invert Verilog output)
set_property PACKAGE_PIN T23 [get_ports led]
set_property IOSTANDARD LVCMOS33 [get_ports led]
