set_property IOSTANDARD LVCMOS33 [current_design]
set_property PACKAGE_PIN E3  [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -period 10.000 -name sys_clk [get_ports clk]
set_property PACKAGE_PIN A8  [get_ports d]
set_property IOSTANDARD LVCMOS33 [get_ports d]
set_property PACKAGE_PIN H5   [get_ports q]
set_property IOSTANDARD LVCMOS33 [get_ports q]
