apiVersion: v1
kind: Service
metadata:
  name: trinity-swarm
  labels:
    app: trinity-swarm
spec:
  type: LoadBalancer
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app: trinity-swarm
