// ═══════════════════════════════════════════════════════════════════════════════
// test_multi_led v1.0.0 - FPGA Verilog from .vibee specification
// ═══════════════════════════════════════════════════════════════════════════════
//
// Golden Identity: φ² + 1/φ² = 3
//
// DO NOT EDIT - This file is auto-generated by VIBEE
//
// Target:   xilinx (50 MHz)
// ═══════════════════════════════════════════════════════════════════════════════

`timescale 1ns / 1ps

module test_multi_led (
input  wire clk,
output  wire [6:0] led
);

          // 26-bit counter
      reg [25:0] counter = 26'h0;

      always @(posedge clk) begin
          counter <= counter + 1'b1;
      end

      // Each LED uses a different bit of the counter
      // LED[0] uses bit 20 (fastest: 2^20 / 50MHz ≈ 21ms toggle)
      // LED[7] uses bit 27 (slowest: 2^27 / 50MHz ≈ 2.7s toggle)
      // But we only have 26 bits, so adjust:
      // LED[0] = bit 23, LED[1] = bit 22, etc.
      //
      // Actually, let's use a simpler pattern - each LED blinks at power-of-2 rate

      // Generate individual LED signals
      wire led0 = counter[23];  // Fastest (~0.1s period)
      wire led1 = counter[22];  // ~0.2s period
      wire led2 = counter[21];  // ~0.4s period
      wire led3 = counter[20];  // ~0.8s period
      wire led4 = counter[19];  // ~1.6s period
      wire led5 = counter[18];  // ~3.2s period
      wire led6 = counter[17];  // ~6.4s period

      // Combine into bus (active-low)
      assign led = ~{led0, led1, led2, led3, led4, led5, led6};



endmodule
