#!/usr/bin/env python3
"""
MCP Registry Loader — P1.5: Load MCP tools from registry.json
Instead of 203 manual @app.call_tool() decorators, load tools dynamically.
"""

import json
import os
from pathlib import Path
from typing import Any, Dict, List
from mcp.types import Tool


class RegistryLoader:
    """Load MCP tools from registry.json generated by Zig build."""

    def __init__(self, registry_path: str = ".trinity/registry.json"):
        self.registry_path = Path(registry_path)
        self.registry: Dict[str, Any] = {}
        self.tools: List[Tool] = []
        self.load()

    def load(self) -> None:
        """Load registry from disk."""
        if not self.registry_path.exists():
            raise FileNotFoundError(
                f"Registry not found at {self.registry_path}. "
                "Run 'zig build export-registry' first."
            )

        with open(self.registry_path, 'r') as f:
            self.registry = json.load(f)

        self._generate_tools()

    def _generate_tools(self) -> None:
        """Generate MCP Tool objects from registry commands."""
        self.tools = []
        for cmd in self.registry.get("commands", []):
            if not cmd.get("mcp_enabled", False):
                continue

            tool = self._command_to_tool(cmd)
            self.tools.append(tool)

    def _command_to_tool(self, cmd: Dict[str, Any]) -> Tool:
        """Convert a command definition to MCP Tool."""
        # Get MCP-specific name or use command name
        mcp_name = cmd.get("mcp_name") or cmd["name"]

        # Get display name or use description
        display_name = cmd.get("mcp_display_name") or cmd["description"]

        # Build input schema
        input_schema = self._build_input_schema(cmd)

        return Tool(
            name=mcp_name,
            description=display_name,
            inputSchema=input_schema
        )

    def _build_input_schema(self, cmd: Dict[str, Any]) -> Dict[str, Any]:
        """Build JSON Schema for input parameters."""
        schema = {
            "type": "object",
            "properties": {},
        }

        input_params = cmd.get("input_params", [])

        # Build properties from input_params
        required = []
        for param in input_params:
            param_name = param["name"]
            param_type = param.get("type", "string")

            # Map Zig types to JSON Schema types
            json_type = self._map_type(param_type)

            prop_schema = {"type": json_type}

            if param.get("description"):
                prop_schema["description"] = param["description"]

            if param.get("default_value"):
                prop_schema["default"] = param["default_value"]

            schema["properties"][param_name] = prop_schema

            if param.get("required", False):
                required.append(param_name)

        if required:
            schema["required"] = required

        return schema

    def _map_type(self, zig_type: str) -> str:
        """Map Zig type to JSON Schema type."""
        type_mapping = {
            "string": "string",
            "integer": "integer",
            "float": "number",
            "boolean": "boolean",
            "array": "array",
            "object": "object",
        }
        return type_mapping.get(zig_type, "string")

    def get_tool(self, name: str) -> Tool | None:
        """Get a specific tool by name."""
        for tool in self.tools:
            if tool.name == name:
                return tool
        return None

    def get_command_for_tool(self, tool_name: str) -> Dict[str, Any] | None:
        """Get the command definition for a given tool name."""
        for cmd in self.registry.get("commands", []):
            if cmd.get("mcp_enabled") and cmd.get("mcp_name") == tool_name:
                return cmd
            if cmd.get("mcp_enabled") and cmd["name"] == tool_name:
                return cmd
        return None

    def get_all_tools(self) -> List[Tool]:
        """Get all MCP-enabled tools."""
        return self.tools

    def get_stats(self) -> Dict[str, Any]:
        """Get registry statistics."""
        commands = self.registry.get("commands", [])

        stats = {
            "total_commands": len(commands),
            "mcp_enabled": len(self.tools),
            "by_mode": {"sync": 0, "job": 0, "stream": 0},
            "by_stability": {"stable": 0, "experimental": 0, "dangerous": 0},
            "by_namespace": {"core": 0, "dev": 0, "forge": 0, "agent": 0, "mcp": 0, "system": 0},
        }

        for cmd in commands:
            mode = cmd.get("mode", "sync")
            if mode in stats["by_mode"]:
                stats["by_mode"][mode] += 1

            stability = cmd.get("stability", "stable")
            if stability in stats["by_stability"]:
                stats["by_stability"][stability] += 1

            namespace = cmd.get("cli_namespace", "core")
            if namespace in stats["by_namespace"]:
                stats["by_namespace"][namespace] += 1

        return stats

    def get_tri_command(self, tool_name: str, args: Dict[str, Any]) -> List[str]:
        """
        Convert MCP tool call to TRI CLI command args.

        Returns a list of command arguments to pass to subprocess.
        """
        cmd = self.get_command_for_tool(tool_name)
        if not cmd:
            raise ValueError(f"Unknown tool: {tool_name}")

        # Start with the base command name
        tri_args = [cmd["name"]]

        # Add aliases if needed (usually we use the primary name)

        # Add arguments from input params
        input_params = cmd.get("input_params", [])
        for param in input_params:
            param_name = param["name"]
            if param_name in args:
                value = args[param_name]

                # Convert Python bool to CLI flag
                if param.get("type") == "boolean":
                    if value:
                        # Boolean flags are usually just --flag without value
                        # or --flag=true
                        if isinstance(value, bool):
                            if value:
                                tri_args.append(f"--{param_name}")
                        else:
                            tri_args.extend([f"--{param_name}", str(value)])
                else:
                    # Regular parameters: --name value or just value (positional)
                    if param.get("required", False):
                        # Positional argument
                        tri_args.append(str(value))
                    else:
                        # Optional argument with flag
                        tri_args.extend([f"--{param_name}", str(value)])

        return tri_args


# Singleton instance
_loader_instance: RegistryLoader | None = None


def get_loader(registry_path: str = ".trinity/registry.json") -> RegistryLoader:
    """Get the singleton RegistryLoader instance."""
    global _loader_instance
    if _loader_instance is None:
        _loader_instance = RegistryLoader(registry_path)
    return _loader_instance


def reload_loader(registry_path: str = ".trinity/registry.json") -> RegistryLoader:
    """Force reload the registry from disk."""
    global _loader_instance
    _loader_instance = RegistryLoader(registry_path)
    return _loader_instance
