// Arbitrary 8-entry codebook decode -- the challenger.
//
// GENERATED by gen_cb.py; do not edit. Levels, exact:
//   0.00000, 0.07701, 0.18828, 0.31396, 0.46561, 0.61130, 0.79074, 1.00000
// quantised to 4 fractional bits (round-to-nearest):
//   0/16 = 0.00000, 1/16 = 0.06250, 3/16 = 0.18750, 5/16 = 0.31250, 7/16 = 0.43750, 10/16 = 0.62500, 13/16 = 0.81250, 16/16 = 1.00000
// monotone: yes.  distinct: yes.  both asserted at generation time.
//
// There is no arithmetic here and there cannot be: the levels are not
// dyadic, so no shift-and-add of the code reproduces them. This is the
// lookup whose cost is the question.
`default_nettype none
module cb4_decode_b4 (
    input  wire        [3:0] code,   // {sign, index[2:0]}
    output wire signed [5:0] w       // two's complement, units of 2^-4
);
    wire       s = code[3];
    wire [2:0] i = code[2:0];
    reg  [4:0] mag;
    always @(*) case (i)
      3'd0: mag = 5'd0;
      3'd1: mag = 5'd1;
      3'd2: mag = 5'd3;
      3'd3: mag = 5'd5;
      3'd4: mag = 5'd7;
      3'd5: mag = 5'd10;
      3'd6: mag = 5'd13;
      3'd7: mag = 5'd16;
    endcase
    assign w = s ? -$signed({1'b0, mag}) : $signed({1'b0, mag});
endmodule
`default_nettype wire
