// Arbitrary 8-entry codebook decode -- the challenger.
//
// GENERATED by gen_cb.py; do not edit. Levels, exact:
//   0.00000, 0.07701, 0.18828, 0.31396, 0.46561, 0.61130, 0.79074, 1.00000
// quantised to 10 fractional bits (round-to-nearest):
//   0/1024 = 0.00000, 79/1024 = 0.07715, 193/1024 = 0.18848, 321/1024 = 0.31348, 477/1024 = 0.46582, 626/1024 = 0.61133, 810/1024 = 0.79102, 1024/1024 = 1.00000
// monotone: yes.  distinct: yes.  both asserted at generation time.
//
// There is no arithmetic here and there cannot be: the levels are not
// dyadic, so no shift-and-add of the code reproduces them. This is the
// lookup whose cost is the question.
`default_nettype none
module cb4_decode_b10 (
    input  wire        [3:0] code,   // {sign, index[2:0]}
    output wire signed [11:0] w       // two's complement, units of 2^-10
);
    wire       s = code[3];
    wire [2:0] i = code[2:0];
    reg  [10:0] mag;
    always @(*) case (i)
      3'd0: mag = 11'd0;
      3'd1: mag = 11'd79;
      3'd2: mag = 11'd193;
      3'd3: mag = 11'd321;
      3'd4: mag = 11'd477;
      3'd5: mag = 11'd626;
      3'd6: mag = 11'd810;
      3'd7: mag = 11'd1024;
    endcase
    assign w = s ? -$signed({1'b0, mag}) : $signed({1'b0, mag});
endmodule
`default_nettype wire
