// Arbitrary 8-entry codebook decode -- the challenger.
//
// GENERATED by gen_cb.py; do not edit. Levels, exact:
//   0.00000, 0.07701, 0.18828, 0.31396, 0.46561, 0.61130, 0.79074, 1.00000
// quantised to 5 fractional bits (round-to-nearest):
//   0/32 = 0.00000, 2/32 = 0.06250, 6/32 = 0.18750, 10/32 = 0.31250, 15/32 = 0.46875, 20/32 = 0.62500, 25/32 = 0.78125, 32/32 = 1.00000
// monotone: yes.  distinct: yes.  both asserted at generation time.
//
// There is no arithmetic here and there cannot be: the levels are not
// dyadic, so no shift-and-add of the code reproduces them. This is the
// lookup whose cost is the question.
`default_nettype none
module cb4_decode_b5 (
    input  wire        [3:0] code,   // {sign, index[2:0]}
    output wire signed [6:0] w       // two's complement, units of 2^-5
);
    wire       s = code[3];
    wire [2:0] i = code[2:0];
    reg  [5:0] mag;
    always @(*) case (i)
      3'd0: mag = 6'd0;
      3'd1: mag = 6'd2;
      3'd2: mag = 6'd6;
      3'd3: mag = 6'd10;
      3'd4: mag = 6'd15;
      3'd5: mag = 6'd20;
      3'd6: mag = 6'd25;
      3'd7: mag = 6'd32;
    endcase
    assign w = s ? -$signed({1'b0, mag}) : $signed({1'b0, mag});
endmodule
`default_nettype wire
