#!/usr/bin/env python3
"""Emit the Campaign-B decoders: MX-asym-NEAR0 and its width-matched controls.

The book is NOT retyped here. It is imported from research/block/campaignB_books.py
-- the same object the perplexity campaign quantised with -- and the T38 assert is
re-run on BOTH tails before any RTL is written.

Why a units-of-1/24 grid. E2M1's magnitudes normalised to max|level| = 1 are
0, 1/12, 1/6, 1/4, 1/3, 1/2, 2/3, 1, i.e. the integers 0,1,2,3,4,6,8,12 in units
of 1/12 -- four bits, exactly, which is what makes the incumbent decoder cheap.
MX-asym-NEAR0 adds one positive level at HALF the smallest E2M1 step, so it is not
on that grid; the coarsest grid carrying every level is 1/24. In those units the
book is the integer set

    {0, +-2, +-4, +-6, +-8, +-12, +-16, +-24}  and  +1

so the decoded weight needs a signed 6-bit field where E2M1 needs 5. That extra
bit is a real, measured cost of the sixteenth codeword and is priced below rather
than argued away.

The per-format unit constant folds into the shared E8M0 exponent exactly as
CODEBOOK_SILICON_2026-08-11 describes for E2M1's 0.5: 1/24 = (1/12)/2 and 2 is a
power of two, so the two formats' units differ by a power of two and neither is
charged for its normalisation. That is why the grid change costs a BIT, not an
adder.

Four decoders are emitted so that exactly one thing changes at a time:

  mx_u24_struct  E2M1, structural sign+shift, 6-bit out  -- width-matched control
  mx_u24_flat    E2M1, flat 16-entry case,    6-bit out  -- encoding-matched control
  asym_mx        NEAR0, flat 16-entry case,   6-bit out  -- MX bit layout, the
                 -0 slot repurposed for +1/24
  asym_srt       NEAR0, flat 16-entry case,   6-bit out  -- codes in ascending
                 value order

asym_mx and asym_srt express the SAME sixteen values and therefore the same
perplexity; they differ only in which code carries which value, which is free to
choose and is not free in LUT masks. Both are measured so the choice is priced.
"""
import os, sys
from fractions import Fraction as F

HERE = os.path.dirname(os.path.abspath(__file__))
RB = os.path.abspath(os.path.join(HERE, "..", "..", "research", "block"))
sys.path.insert(0, RB)
import campaignB_books as B                                    # noqa: E402

W = 6                                                          # signed, units 1/24
U = 24


def near0_units():
    """The measured book, pulled from the campaign source and re-asserted."""
    lv = B.mx_family()["MX-asym-NEAR0"]
    assert len(lv) == len(set(lv)) == 16, lv
    # T38 on BOTH tails, exactly, before anything is written.
    assert max(lv) == 1.0 and min(lv) == -1.0, ("T38", max(lv), min(lv))
    ints = []
    for x in lv:
        f = F(x).limit_denominator(10 ** 6) * U
        assert f.denominator == 1, (x, f)
        assert float(F(int(f), U)) == x, (x, f)                # exact, not rounded
        ints.append(int(f))
    assert sorted(ints) == ints
    assert max(ints) == U and min(ints) == -U                  # T38 in integer form
    assert all(-(1 << (W - 1)) <= v < (1 << (W - 1)) for v in ints), "W too narrow"
    return ints


def e2m1_units():
    """E2M1's magnitudes on the same 1/24 grid."""
    m = [0] + [2 * u for u in B.MX_UNITS]                      # 0,2,4,6,8,12,16,24
    assert m == [0, 2, 4, 6, 8, 12, 16, 24], m
    return m


def tc(v, w=W):
    """Two's-complement bit pattern, so the netlist constant is auditable."""
    return format(v & ((1 << w) - 1), f"0{w}b")


HDR = """// GENERATED by gen_asym.py; do not edit.
// Book imported from research/block/campaignB_books.py (the campaign's own
// object). T38 re-asserted on both tails at generation time.
`default_nettype none
"""


def emit_flat(name, values, note, w=W, u=U):
    """4-bit index -> one of 16 signed values. No sign path: the sign is IN the
    table. This is the whole structural claim of an asymmetric book."""
    assert len(values) == 16
    assert all(-(1 << (w - 1)) <= v < (1 << (w - 1)) for v in values), (name, w)
    q = [HDR, f"// {note}", f"// code -> value, in units of 1/{u}:"]
    for c, v in enumerate(values):
        q.append(f"//   {c:2d} ({format(c,'04b')}) -> {v:+3d}/{u} = {v/u:+.6f}")
    q.append(f"module {name} (")
    q.append("    input  wire        [3:0] code,")
    q.append(f"    output reg  signed [{w-1}:0] w      // two's complement, units 1/{u}")
    q.append(");")
    q.append("    always @(*) case (code)")
    for c, v in enumerate(values):
        q.append(f"      4'd{c:<2d}: w = {w}'b{tc(v, w)};   // {v:+3d}")
    q.append("    endcase")
    q.append("endmodule")
    q.append("`default_nettype wire")
    p = os.path.join(HERE, f"{name}.v")
    open(p, "w").write("\n".join(q) + "\n")
    return p


def emit_struct_u24(name):
    """E2M1 on the 1/24 grid, keeping the incumbent's structure. The magnitude in
    units of 1/24 is twice the magnitude in units of 1/12, and a doubling is a
    wire, so this is mxfp4_decode.v with one hard zero appended and a 6-bit
    negate. It isolates 'wider field' from 'different table'."""
    q = [HDR,
         "// E2M1 magnitudes on the 1/24 grid, structural sign+shift (the incumbent's",
         "// shape, one bit wider). Width-matched control for the asymmetric table.",
         f"module {name} (",
         "    input  wire        [3:0] code,   // {sign, e[1:0], m}",
         f"    output wire signed [{W-1}:0] w       // two's complement, units 1/{U}",
         ");",
         "    wire       s = code[3];",
         "    wire [1:0] e = code[2:1];",
         "    wire       m = code[0];",
         "    wire [3:0] mag12 = (e == 2'b00) ? {3'b000, m}",
         "                                    : ({2'b00, 1'b1, m} << (e - 2'b01));",
         "    wire [4:0] mag24 = {mag12, 1'b0};          // x2 is a wire, not an adder",
         "    assign w = s ? -$signed({1'b0, mag24}) : $signed({1'b0, mag24});",
         "endmodule",
         "`default_nettype wire"]
    p = os.path.join(HERE, f"{name}.v")
    open(p, "w").write("\n".join(q) + "\n")
    return p


def main():
    near0 = near0_units()
    e2m1 = e2m1_units()

    # --- asym, ascending value order -------------------------------------
    srt = list(near0)

    # --- asym, MX bit layout: {s,i}; s=1,i=0 would be -0, repurposed to +1 --
    mx = [0] * 16
    for i, m in enumerate(e2m1):
        mx[i] = m                       # s=0 -> +magnitude
        mx[8 + i] = -m                  # s=1 -> -magnitude
    assert mx[8] == 0                   # the -0 slot
    mx[8] = 1                           # ... spent on the sixteenth codeword
    assert sorted(mx) == srt, (sorted(mx), srt)      # same book, different order

    # --- symmetric control on the same grid, flat encoding ---------------
    fl = [0] * 16
    for i, m in enumerate(e2m1):
        fl[i] = m
        fl[8 + i] = -m
    assert len(set(fl)) == 15 and fl.count(0) == 2   # +0 and -0: the wasted codeword

    # --- symmetric control on the INCUMBENT's own 1/12 grid, flat encoding ---
    # Without this arm, "flat" and "one bit wider" are confounded: every other
    # flat table here is 6 bits because NEAR0 needs the 1/24 grid. This one is
    # E2M1 at E2M1's own width, so the encoding change is isolated.
    e2m1_12 = [0, 1, 2, 3, 4, 6, 8, 12]
    assert [float(F(m, 12)) for m in e2m1_12] == [0.0] + [float(F(u, 12)) for u in B.MX_UNITS]
    f12 = [0] * 16
    for i, m in enumerate(e2m1_12):
        f12[i] = m
        f12[8 + i] = -m
    assert max(f12) == 12 and min(f12) == -12                # T38, both tails
    assert len(set(f12)) == 15 and f12.count(0) == 2

    ps = [
        emit_flat("mx_u12_flat", f12,
                  "E2M1 (SYMMETRIC) on the incumbent's own 1/12 grid, flat "
                  "encoding. Isolates 'flat table' from 'one bit wider'.",
                  w=5, u=12),
        emit_flat("asym_srt", srt,
                  "MX-asym-NEAR0, codes in ascending value order."),
        emit_flat("asym_mx", mx,
                  "MX-asym-NEAR0 in the MX bit layout {s,e,m}; the -0 codeword "
                  "carries +1/24."),
        emit_flat("mx_u24_flat", fl,
                  "E2M1 (SYMMETRIC) on the same 1/24 grid, same flat encoding. "
                  "Two codes are zero -- fifteen distinct values from sixteen "
                  "codewords."),
        emit_struct_u24("mx_u24_struct"),
    ]
    for p in ps:
        print("wrote", os.path.basename(p))
    print("NEAR0 x24 :", near0)
    print("E2M1  x24 :", e2m1)
    print("T38: max +1.000000  min -1.000000  (both tails, exact)")
    return {"asym_srt": srt, "asym_mx": mx, "mx_u24_flat": fl,
            "mx_u24_struct": fl, "mxfp4_decode": None}


if __name__ == "__main__":
    main()
