// GENERATED by gen_asym.py; do not edit.
// Book imported from research/block/campaignB_books.py (the campaign's own
// object). T38 re-asserted on both tails at generation time.
`default_nettype none

// E2M1 (SYMMETRIC) on the incumbent's own 1/12 grid, flat encoding. Isolates 'flat table' from 'one bit wider'.
// code -> value, in units of 1/12:
//    0 (0000) ->  +0/12 = +0.000000
//    1 (0001) ->  +1/12 = +0.083333
//    2 (0010) ->  +2/12 = +0.166667
//    3 (0011) ->  +3/12 = +0.250000
//    4 (0100) ->  +4/12 = +0.333333
//    5 (0101) ->  +6/12 = +0.500000
//    6 (0110) ->  +8/12 = +0.666667
//    7 (0111) -> +12/12 = +1.000000
//    8 (1000) ->  +0/12 = +0.000000
//    9 (1001) ->  -1/12 = -0.083333
//   10 (1010) ->  -2/12 = -0.166667
//   11 (1011) ->  -3/12 = -0.250000
//   12 (1100) ->  -4/12 = -0.333333
//   13 (1101) ->  -6/12 = -0.500000
//   14 (1110) ->  -8/12 = -0.666667
//   15 (1111) -> -12/12 = -1.000000
module mx_u12_flat (
    input  wire        [3:0] code,
    output reg  signed [4:0] w      // two's complement, units 1/12
);
    always @(*) case (code)
      4'd0 : w = 5'b00000;   //  +0
      4'd1 : w = 5'b00001;   //  +1
      4'd2 : w = 5'b00010;   //  +2
      4'd3 : w = 5'b00011;   //  +3
      4'd4 : w = 5'b00100;   //  +4
      4'd5 : w = 5'b00110;   //  +6
      4'd6 : w = 5'b01000;   //  +8
      4'd7 : w = 5'b01100;   // +12
      4'd8 : w = 5'b00000;   //  +0
      4'd9 : w = 5'b11111;   //  -1
      4'd10: w = 5'b11110;   //  -2
      4'd11: w = 5'b11101;   //  -3
      4'd12: w = 5'b11100;   //  -4
      4'd13: w = 5'b11010;   //  -6
      4'd14: w = 5'b11000;   //  -8
      4'd15: w = 5'b10100;   // -12
    endcase
endmodule
`default_nettype wire
