// GENERATED by gen_asym.py; do not edit.
// Book imported from research/block/campaignB_books.py (the campaign's own
// object). T38 re-asserted on both tails at generation time.
`default_nettype none

// E2M1 magnitudes on the 1/24 grid, structural sign+shift (the incumbent's
// shape, one bit wider). Width-matched control for the asymmetric table.
module mx_u24_struct (
    input  wire        [3:0] code,   // {sign, e[1:0], m}
    output wire signed [5:0] w       // two's complement, units 1/24
);
    wire       s = code[3];
    wire [1:0] e = code[2:1];
    wire       m = code[0];
    wire [3:0] mag12 = (e == 2'b00) ? {3'b000, m}
                                    : ({2'b00, 1'b1, m} << (e - 2'b01));
    wire [4:0] mag24 = {mag12, 1'b0};          // x2 is a wire, not an adder
    assign w = s ? -$signed({1'b0, mag24}) : $signed({1'b0, mag24});
endmodule
`default_nettype wire
