// ═══════════════════════════════════════════════════════════════════════════════
// LANGUAGE GENERATORS - Production Code Generation for 42 Languages
// ═══════════════════════════════════════════════════════════════════════════════
// φ² + 1/φ² = 3 | PHOENIX = 999
// ═══════════════════════════════════════════════════════════════════════════════

const std = @import("std");
const Allocator = std.mem.Allocator;

pub const TypeDef = struct {
    name: []const u8,
    fields: []const Field,
};

pub const Field = struct {
    name: []const u8,
    type_name: []const u8,
};

pub const Behavior = struct {
    name: []const u8,
    given: []const u8,
    when: []const u8,
    then: []const u8,
    implementation: []const u8 = "",
};

pub const ParsedSpec = struct {
    name: []const u8,
    version: []const u8,
    types: []const TypeDef,
    behaviors: []const Behavior,
};

// ═══════════════════════════════════════════════════════════════════════════════
// PYTHON GENERATOR (MGEN-001: Fluent Python)
// ═══════════════════════════════════════════════════════════════════════════════

pub fn generatePython(allocator: Allocator, spec: ParsedSpec) ![]u8 {
    var result: std.ArrayListUnmanaged(u8) = .empty;
    const w = result.writer(allocator);

    try w.print("# {s} v{s}\n", .{ spec.name, spec.version });
    try w.print("# Generated by VIBEE Multi-Language Generator (MGEN-001 Fluent Python)\n", .{});
    try w.print("# φ² + 1/φ² = 3\n\n", .{});

    // MGEN-001: Enhanced imports for fluent Python
    try w.print("from __future__ import annotations\n", .{});
    try w.print("from dataclasses import dataclass, field\n", .{});
    try w.print("from typing import Optional, List, Dict, Any, TypeVar, Generic, Callable, Awaitable\n", .{});
    try w.print("from contextlib import contextmanager\n", .{});
    try w.print("from abc import ABC, abstractmethod\n", .{});
    try w.print("import asyncio\n\n", .{});

    // Custom exception for the module
    try w.print("class {s}Error(Exception):\n", .{spec.name});
    try w.print("    \"\"\"Base exception for {s}\"\"\"\n", .{spec.name});
    try w.print("    pass\n\n", .{});

    // Generate types with enhanced dataclass patterns
    for (spec.types) |t| {
        try w.print("@dataclass\n", .{});
        try w.print("class {s}:\n", .{t.name});
        try w.print("    \"\"\"Auto-generated from .vibee spec\"\"\"\n", .{});

        if (t.fields.len == 0) {
            try w.print("    pass\n", .{});
        } else {
            for (t.fields) |f| {
                const py_type = mapTypePythonFluent(f.type_name);
                const default_val = if (isOptionalType(f.type_name)) " = None" else "";
                try w.print("    {s}: {s}{s}\n", .{ f.name, py_type, default_val });
            }
        }

        // MGEN-001: Add __post_init__ for validation
        try w.print("\n", .{});
        try w.print("    def __post_init__(self) -> None:\n", .{});
        try w.print("        \"\"\"Validate fields after initialization\"\"\"\n", .{});
        try w.print("        pass\n", .{});

        // MGEN-001: Add __repr__ for better debugging
        try w.print("\n", .{});
        try w.print("    def __repr__(self) -> str:\n", .{});
        try w.print("        fields = ', '.join(f'{{k}}={{v!r}}' for k, v in self.__dict__.items())\n", .{});
        try w.print("        return f'{s}({{fields}})'\n", .{spec.name});

        try w.print("\n\n", .{});
    }

    // Generate behaviors with enhanced patterns
    for (spec.behaviors) |b| {
        const is_async = std.mem.indexOf(u8, b.given, "async") != null or
                         std.mem.indexOf(u8, b.when, "async") != null;
        const is_generator = std.mem.indexOf(u8, b.name, "iter") != null or
                           std.mem.indexOf(u8, b.name, "stream") != null;
        const is_context_manager = std.mem.indexOf(u8, b.name, "with") != null;

        if (b.implementation.len > 0) {
            const impl = std.mem.trim(u8, b.implementation, &std.ascii.whitespace);
            try w.print("{s}\n\n", .{impl});
        } else {
            // Generate fluent docstring
            try w.print("def {s}{s}:\n", .{ b.name, if (is_async) "()" else "" });
            try w.print("    \"\"\"\n", .{});
            try w.print("    Given: {s}\n", .{b.given});
            try w.print("    When:  {s}\n", .{b.when});
            try w.print("    Then:  {s}\n", .{b.then});
            try w.print("    \"\"\"\n", .{});

            if (is_async) {
                try w.print("    await asyncio.sleep(0)  # Placeholder for async operation\n", .{});
            } else if (is_generator) {
                try w.print("    yield  # Generator pattern\n", .{});
            } else if (is_context_manager) {
                try w.print("    yield  # Context manager pattern\n", .{});
            } else {
                try w.print("    raise {s}Error(\"Not implemented\")\n", .{spec.name});
            }
            try w.print("\n\n", .{});
        }
    }

    // MGEN-001: Add async context manager helper
    try w.print("@contextmanager\n", .{});
    try w.print("async def {s}_context():\n", .{spec.name});
    try w.print("    \"\"\"Async context manager for {s} operations\"\"\"\n", .{spec.name});
    try w.print("    yield {s}()\n\n", .{spec.name});

    return result.toOwnedSlice(allocator);
}

// MGEN-001: Enhanced type mapping with proper generics
fn mapTypePythonFluent(vibee_type: []const u8) []const u8 {
    if (std.mem.eql(u8, vibee_type, "String")) return "str";
    if (std.mem.eql(u8, vibee_type, "Int")) return "int";
    if (std.mem.eql(u8, vibee_type, "Float")) return "float";
    if (std.mem.eql(u8, vibee_type, "Bool")) return "bool";

    // Parse generic types like List<String> → List[str]
    if (std.mem.startsWith(u8, vibee_type, "List<")) {
        const inner = vibee_type[5 .. vibee_type.len - 1];
        const inner_mapped = mapTypePythonFluent(inner);
        if (std.mem.eql(u8, inner_mapped, "str")) return "List[str]";
        if (std.mem.eql(u8, inner_mapped, "int")) return "List[int]";
        return "List[Any]";
    }

    if (std.mem.startsWith(u8, vibee_type, "Option<")) {
        const inner = vibee_type[8 .. vibee_type.len - 1];
        const inner_mapped = mapTypePythonFluent(inner);
        if (std.mem.eql(u8, inner_mapped, "str")) return "str | None";
        if (std.mem.eql(u8, inner_mapped, "int")) return "int | None";
        return "Any | None";
    }

    return "Any";
}

fn isOptionalType(vibee_type: []const u8) bool {
    return std.mem.startsWith(u8, vibee_type, "Option<");
}

// ═══════════════════════════════════════════════════════════════════════════════
// RUST GENERATOR (MGEN-002: Fluent Rust)
// ═══════════════════════════════════════════════════════════════════════════════

pub fn generateRust(allocator: Allocator, spec: ParsedSpec) ![]u8 {
    var result: std.ArrayListUnmanaged(u8) = .empty;
    const w = result.writer(allocator);

    try w.print("// {s} v{s}\n", .{ spec.name, spec.version });
    try w.print("// Generated by VIBEE Multi-Language Generator (MGEN-002 Fluent Rust)\n", .{});
    try w.print("// φ² + 1/φ² = 3\n\n", .{});

    // MGEN-002: Enhanced imports for idiomatic Rust
    try w.print("use serde::{{Serialize, Deserialize}};\n", .{});
    try w.print("use thiserror::Error;\n\n", .{});

    // MGEN-002: Custom error type for the module
    try w.print("#[derive(Debug, Error)]\n", .{});
    try w.print("pub enum {s}Error {{\n", .{spec.name});
    try w.print("    #[error(\"Invalid operation: {{0}}\")]\n", .{});
    try w.print("    InvalidOperation(String),\n", .{});
    try w.print("    #[error(\"Not found: {{0}}\")]\n", .{});
    try w.print("    NotFound(String),\n", .{});
    try w.print("    #[error(\"Validation failed: {{0}}\")]\n", .{});
    try w.print("    Validation(String),\n", .{});
    try w.print("    #[error(\"IO error: {{0}}\")]\n", .{});
    try w.print("    Io(#[from] std::io::Error),\n", .{});
    try w.print("}}\n\n", .{});

    // MGEN-002: Result type alias
    try w.print("pub type {s}Result<T> = Result<T, {s}Error>;\n\n", .{ spec.name, spec.name });

    // Generate types with enhanced derives
    for (spec.types) |t| {
        // MGEN-002: Enhanced derive macros
        try w.print("#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]\n", .{});

        // Check if any field is optional to add Default derive
        const has_optional = for (t.fields) |f| {
            if (isOptionalTypeRust(f.type_name)) break true;
        } else false;
        if (has_optional or t.fields.len == 0) {
            try w.print("#[derive(Default)]\n", .{});
        }

        try w.print("pub struct {s} {{\n", .{t.name});
        for (t.fields) |f| {
            const rs_type = mapTypeRustFluent(f.type_name);
            const default_val = if (isOptionalTypeRust(f.type_name)) " = None" else "";
            try w.print("    pub {s}: {s}{s},\n", .{ f.name, rs_type, default_val });
        }
        try w.print("}}\n\n", .{});

        // MGEN-002: Add impl block with builder pattern and new()
        try w.print("impl {s} {{\n", .{t.name});
        try w.print("    /// Create a new instance with all required fields\n", .{});

        // Build constructor parameters
        if (t.fields.len > 0) {
            try w.print("    pub fn new(", .{});
            var first = true;
            for (t.fields) |f| {
                if (!isOptionalTypeRust(f.type_name)) {
                    if (!first) try w.print(", ", .{});
                    try w.print("{s}: {s}", .{ f.name, mapTypeRustFluent(f.type_name) });
                    first = false;
                }
            }
            try w.print(") -> Self {{\n", .{});
            try w.print("        Self {{\n", .{});
            for (t.fields) |f| {
                if (isOptionalTypeRust(f.type_name)) {
                    try w.print("            {s}: None,\n", .{f.name});
                } else {
                    try w.print("            {s},\n", .{f.name});
                }
            }
            try w.print("        }}\n", .{});
            try w.print("    }}\n", .{});
            try w.print("}}\n\n", .{});
        } else {
            try w.print("    pub fn new() -> Self {{\n", .{});
            try w.print("        Self {{}}\n", .{});
            try w.print("    }}\n", .{});
            try w.print("}}\n\n", .{});
        }
    }

    // Generate behaviors with Result types
    for (spec.behaviors) |b| {
        if (b.implementation.len > 0) {
            // Use custom implementation (contains full function definition)
            const impl = std.mem.trim(u8, b.implementation, &std.ascii.whitespace);
            try w.print("/// Given: {s}, When: {s}, Then: {s}\n", .{ b.given, b.when, b.then });
            try w.print("{s}\n\n", .{impl});
        } else {
            // MGEN-002: Generate stub with Result type
            try w.print("/// Given: {s}, When: {s}, Then: {s}\n", .{ b.given, b.when, b.then });

            // Detect async behavior
            const is_async = std.mem.indexOf(u8, b.given, "async") != null or
                             std.mem.indexOf(u8, b.when, "async") != null;
            const is_iterator = std.mem.indexOf(u8, b.name, "iter") != null or
                                std.mem.indexOf(u8, b.name, "stream") != null;

            if (is_async) {
                try w.print("pub async fn {s}() -> {s}Result<()> {{\n", .{ b.name, spec.name });
            } else if (is_iterator) {
                try w.print("pub fn {s}() -> impl Iterator<Item = {s}Result<String>> {{\n", .{ b.name, spec.name });
                try w.print("    std::iter::empty()\n", .{});
            } else {
                try w.print("pub fn {s}() -> {s}Result<()> {{\n", .{ b.name, spec.name });
            }
            try w.print("    todo!()\n", .{});
            try w.print("}}\n\n", .{});
        }
    }

    return result.toOwnedSlice(allocator);
}

// MGEN-002: Enhanced type mapping with proper generics
fn mapTypeRustFluent(vibee_type: []const u8) []const u8 {
    if (std.mem.eql(u8, vibee_type, "String")) return "String";
    if (std.mem.eql(u8, vibee_type, "Int")) return "i64";
    if (std.mem.eql(u8, vibee_type, "Float")) return "f64";
    if (std.mem.eql(u8, vibee_type, "Bool")) return "bool";

    // Parse generic types like List<String> → Vec<String>
    if (std.mem.startsWith(u8, vibee_type, "List<")) {
        const inner = vibee_type[5 .. vibee_type.len - 1];
        const inner_mapped = mapTypeRustFluent(inner);
        if (std.mem.eql(u8, inner_mapped, "String")) return "Vec<String>";
        if (std.mem.eql(u8, inner_mapped, "i64")) return "Vec<i64>";
        if (std.mem.eql(u8, inner_mapped, "bool")) return "Vec<bool>";
        return "Vec<serde_json::Value>";
    }

    if (std.mem.startsWith(u8, vibee_type, "Option<")) {
        const inner = vibee_type[8 .. vibee_type.len - 1];
        const inner_mapped = mapTypeRustFluent(inner);
        if (std.mem.eql(u8, inner_mapped, "String")) return "Option<String>";
        if (std.mem.eql(u8, inner_mapped, "i64")) return "Option<i64>";
        if (std.mem.eql(u8, inner_mapped, "bool")) return "Option<bool>";
        return "Option<serde_json::Value>";
    }

    return "serde_json::Value";
}

fn isOptionalTypeRust(vibee_type: []const u8) bool {
    return std.mem.startsWith(u8, vibee_type, "Option<");
}

// ═══════════════════════════════════════════════════════════════════════════════
// GO GENERATOR (MGEN-004: Fluent Go)
// ═══════════════════════════════════════════════════════════════════════════════

pub fn generateGo(allocator: Allocator, spec: ParsedSpec) ![]u8 {
    var result: std.ArrayListUnmanaged(u8) = .empty;
    const w = result.writer(allocator);

    try w.print("// {s} v{s}\n", .{ spec.name, spec.version });
    try w.print("// Generated by VIBEE Multi-Language Generator (MGEN-004 Fluent Go)\n", .{});
    try w.print("// φ² + 1/φ² = 3\n\n", .{});
    try w.print("package {s}\n\n", .{spec.name});

    // MGEN-004: Import fmt for error wrapping
    try w.print("import (\n", .{});
    try w.print("\t\"fmt\"\n", .{});
    try w.print(")\n\n", .{});

    // MGEN-004: Custom error type
    try w.print("// {s}Error represents errors in {s}\n", .{ spec.name, spec.name });
    try w.print("type {s}Error struct {{\n", .{toPascalCase(spec.name)});
    try w.print("\tCode    string\n", .{});
    try w.print("\tMessage string\n", .{});
    try w.print("\tErr     error\n", .{});
    try w.print("}}\n\n", .{});

    try w.print("func (e *{s}Error) Error() string {{\n", .{toPascalCase(spec.name)});
    try w.print("\tif e.Err != nil {{\n", .{});
    try w.print("\t\treturn fmt.Sprintf(\"%s: %s: %v\", e.Code, e.Message, e.Err)\n", .{});
    try w.print("\t}}\n", .{});
    try w.print("\treturn fmt.Sprintf(\"%s: %s\", e.Code, e.Message)\n", .{});
    try w.print("}}\n\n", .{});

    try w.print("func (e *{s}Error) Unwrap() error {{\n", .{toPascalCase(spec.name)});
    try w.print("\treturn e.Err\n", .{});
    try w.print("}}\n\n", .{});

    // Generate types with constructor
    for (spec.types) |t| {
        try w.print("// {s} represents a {s} entity\n", .{t.name, t.name});
        try w.print("type {s} struct {{\n", .{t.name});
        for (t.fields) |f| {
            const go_type = mapTypeGoFluent(f.type_name);
            try w.print("\t{c}{s} {s} `json:\"{s}\"`\n", .{ std.ascii.toUpper(f.name[0]), f.name[1..], go_type, f.name });
        }
        try w.print("}}\n\n", .{});

        // MGEN-004: Add constructor
        try w.print("// New{s} creates a new {s} with required fields\n", .{t.name, t.name});
        try w.print("func New{s}(", .{t.name});

        var first = true;
        for (t.fields) |f| {
            if (!isOptionalTypeGo(f.type_name)) {
                if (!first) try w.print(", ", .{});
                // Use lowerCamel for parameter name
                try w.print("{c}{s}", .{ std.ascii.toLower(f.name[0]), f.name[1..] });
                try w.print(" {s}", .{mapTypeGoFluent(f.type_name)});
                first = false;
            }
        }

        try w.print(") *{s} {{\n", .{t.name});
        try w.print("\treturn &{s}{{\n", .{t.name});

        for (t.fields) |f| {
            if (isOptionalTypeGo(f.type_name)) {
                try w.print("\t\t{c}{s}: nil,\n", .{ std.ascii.toUpper(f.name[0]), f.name[1..] });
            } else {
                try w.print("\t\t{c}{s}: {c}{s},\n", .{ std.ascii.toUpper(f.name[0]), f.name[1..], std.ascii.toLower(f.name[0]), f.name[1..] });
            }
        }

        try w.print("\t}}\n", .{});
        try w.print("}}\n\n", .{});
    }

    // Generate behaviors with error wrapping
    for (spec.behaviors) |b| {
        if (b.implementation.len > 0) {
            const impl = std.mem.trim(u8, b.implementation, &std.ascii.whitespace);
            try w.print("// {s}: Given {s}, When {s}, Then {s}\n", .{ b.name, b.given, b.when, b.then });
            try w.print("{s}\n\n", .{impl});
        } else {
            // MGEN-004: Generate with error return
            try w.print("// {s}: Given {s}, When {s}, Then {s}\n", .{ b.name, b.given, b.when, b.then });
            try w.print("func {s}(", .{toPascalCase(b.name)});

            // Add context parameter if implied
            const has_ctx = std.mem.indexOf(u8, b.given, "context") != null or
                           std.mem.indexOf(u8, b.when, "concurrent") != null;
            if (has_ctx) {
                try w.print("ctx context.Context", .{});
            }

            try w.print(") error {{\n", .{});
            try w.print("\treturn &{s}Error{{\n", .{toPascalCase(spec.name)});
            try w.print("\t\tCode:    \"NOT_IMPLEMENTED\",\n", .{});
            try w.print("\t\tMessage: \"{s} not implemented\",\n", .{b.name});
            try w.print("\t}}\n", .{});
            try w.print("}}\n\n", .{});
        }
    }

    return result.toOwnedSlice(allocator);
}

// MGEN-004: Enhanced type mapping with proper Go types
fn mapTypeGoFluent(vibee_type: []const u8) []const u8 {
    if (std.mem.eql(u8, vibee_type, "String")) return "string";
    if (std.mem.eql(u8, vibee_type, "Int")) return "int64";
    if (std.mem.eql(u8, vibee_type, "Float")) return "float64";
    if (std.mem.eql(u8, vibee_type, "Bool")) return "bool";

    // Parse generic types
    if (std.mem.startsWith(u8, vibee_type, "List<")) {
        const inner = vibee_type[5 .. vibee_type.len - 1];
        const inner_mapped = mapTypeGoFluent(inner);
        if (std.mem.eql(u8, inner_mapped, "string")) return "[]string";
        if (std.mem.eql(u8, inner_mapped, "int64")) return "[]int64";
        return "[]interface{}";
    }

    if (std.mem.startsWith(u8, vibee_type, "Option<")) {
        const inner = vibee_type[8 .. vibee_type.len - 1];
        const inner_mapped = mapTypeGoFluent(inner);
        if (std.mem.eql(u8, inner_mapped, "string")) return "*string";
        if (std.mem.eql(u8, inner_mapped, "int64")) return "*int64";
        return "*interface{}";
    }

    return "interface{}";
}

fn isOptionalTypeGo(vibee_type: []const u8) bool {
    return std.mem.startsWith(u8, vibee_type, "Option<");
}

// Helper: Convert to PascalCase for exports (uses spec name directly for simplicity)
fn toPascalCase(s: []const u8) []const u8 {
    return s;
}

// ═══════════════════════════════════════════════════════════════════════════════
// TYPESCRIPT GENERATOR (MGEN-003: Fluent TypeScript)
// ═══════════════════════════════════════════════════════════════════════════════

pub fn generateTypeScript(allocator: Allocator, spec: ParsedSpec) ![]u8 {
    var result: std.ArrayListUnmanaged(u8) = .empty;
    const w = result.writer(allocator);

    try w.print("// {s} v{s}\n", .{ spec.name, spec.version });
    try w.print("// Generated by VIBEE Multi-Language Generator (MGEN-003 Fluent TypeScript)\n", .{});
    try w.print("// φ² + 1/φ² = 3\n\n", .{});

    // MGEN-003: ESM module format with utility types
    try w.print("// Type utilities\n", .{});
    try w.print("export type Maybe<T> = T | null;\n", .{});
    try w.print("export type Nullable<T> = T | null | undefined;\n\n", .{});

    // MGEN-003: Custom error class
    try w.print("/** Custom error for {s} module */\n", .{spec.name});
    try w.print("export class {s}Error extends Error {{\n", .{spec.name});
    try w.print("  constructor(message: string, public readonly code?: string) {{\n", .{});
    try w.print("    super(message);\n", .{});
    try w.print("    this.name = '{s}Error';\n", .{spec.name});
    try w.print("  }}\n", .{});
    try w.print("}}\n\n", .{});

    // MGEN-003: Result type for error handling
    try w.print("/** Result type for error handling */\n", .{});
    try w.print("export type Result<T, E = {s}Error> =\n", .{spec.name});
    try w.print("  | {{ ok: true; value: T }}\n", .{});
    try w.print("  | {{ ok: false; error: E }};\n\n", .{});

    // Generate types with JSDoc and proper types
    for (spec.types) |t| {
        try w.print("/**\n", .{});
        try w.print(" * Auto-generated from .vibee spec\n", .{});
        try w.print(" */\n", .{});
        try w.print("export interface {s} {{\n", .{t.name});
        for (t.fields) |f| {
            const ts_type = mapTypeTSFluent(f.type_name);
            const optional = if (isOptionalTypeTS(f.type_name)) "?" else "";
            try w.print("  /** {s} field */\n", .{f.name});
            try w.print("  readonly {s}{s}: {s};\n", .{ f.name, optional, ts_type });
        }
        try w.print("}}\n\n", .{});

        // MGEN-003: Add type guard
        try w.print("/** Type guard for {s} */\n", .{t.name});
        try w.print("export function is{s}(value: unknown): value is {s} {{\n", .{ t.name, t.name });
        try w.print("  return (\n", .{});
        try w.print("    typeof value === 'object' &&\n", .{});
        try w.print("    value !== null &&\n", .{});
        const field_count = t.fields.len;
        if (field_count > 0) {
            for (t.fields, 0..) |f, i| {
                const trailing = if (i < field_count - 1) " &&" else "";
                try w.print("    '{s}' in value{s}\n", .{ f.name, trailing });
            }
        }
        try w.print("  );\n", .{});
        try w.print("}}\n\n", .{});
    }

    // Generate behaviors with proper typing
    for (spec.behaviors) |b| {
        if (b.implementation.len > 0) {
            // Use custom implementation (contains full function definition)
            const impl = std.mem.trim(u8, b.implementation, &std.ascii.whitespace);
            try w.print("/**\n", .{});
            try w.print(" * Given: {s}\n", .{b.given});
            try w.print(" * When: {s}\n", .{b.when});
            try w.print(" * Then: {s}\n", .{b.then});
            try w.print(" */\n", .{});
            try w.print("{s}\n\n", .{impl});
        } else {
            // MGEN-003: Generate stub with proper types
            try w.print("/**\n", .{});
            try w.print(" * Given: {s}\n", .{b.given});
            try w.print(" * When: {s}\n", .{b.when});
            try w.print(" * Then: {s}\n", .{b.then});
            try w.print(" */\n", .{});

            // Detect async behavior
            const is_async = std.mem.indexOf(u8, b.given, "async") != null or
                             std.mem.indexOf(u8, b.when, "async") != null;
            const is_generator = std.mem.indexOf(u8, b.name, "iter") != null or
                                 std.mem.indexOf(u8, b.name, "stream") != null;

            if (is_async) {
                try w.print("export async function {s}(): Promise<void> {{\n", .{b.name});
            } else if (is_generator) {
                try w.print("export function* {s}(): Generator<void> {{\n", .{b.name});
            } else {
                try w.print("export function {s}(): void {{\n", .{b.name});
            }
            try w.print("  // TODO: implement\n", .{});
            try w.print("}}\n\n", .{});
        }
    }

    return result.toOwnedSlice(allocator);
}

// MGEN-003: Enhanced type mapping with proper generics
fn mapTypeTSFluent(vibee_type: []const u8) []const u8 {
    if (std.mem.eql(u8, vibee_type, "String")) return "string";
    if (std.mem.eql(u8, vibee_type, "Int")) return "number";
    if (std.mem.eql(u8, vibee_type, "Float")) return "number";
    if (std.mem.eql(u8, vibee_type, "Bool")) return "boolean";

    // Parse generic types like List<String> → string[]
    if (std.mem.startsWith(u8, vibee_type, "List<")) {
        const inner = vibee_type[5 .. vibee_type.len - 1];
        const inner_mapped = mapTypeTSFluent(inner);
        if (std.mem.eql(u8, inner_mapped, "string")) return "readonly string[]";
        if (std.mem.eql(u8, inner_mapped, "number")) return "readonly number[]";
        if (std.mem.eql(u8, inner_mapped, "boolean")) return "readonly boolean[]";
        return "readonly unknown[]";
    }

    if (std.mem.startsWith(u8, vibee_type, "Option<")) {
        const inner = vibee_type[8 .. vibee_type.len - 1];
        const inner_mapped = mapTypeTSFluent(inner);
        if (std.mem.eql(u8, inner_mapped, "string")) return "string | null";
        if (std.mem.eql(u8, inner_mapped, "number")) return "number | null";
        if (std.mem.eql(u8, inner_mapped, "boolean")) return "boolean | null";
        return "unknown | null";
    }

    return "unknown";
}

fn isOptionalTypeTS(vibee_type: []const u8) bool {
    return std.mem.startsWith(u8, vibee_type, "Option<");
}

// ═══════════════════════════════════════════════════════════════════════════════
// ZIG GENERATOR (MGEN-005: Fluent Zig)
// ═══════════════════════════════════════════════════════════════════════════════

pub fn generateZig(allocator: Allocator, spec: ParsedSpec) ![]u8 {
    var result: std.ArrayListUnmanaged(u8) = .empty;
    const w = result.writer(allocator);

    try w.print("// {s} v{s}\n", .{ spec.name, spec.version });
    try w.print("// Generated by VIBEE Multi-Language Generator (MGEN-005 Fluent Zig)\n", .{});
    try w.print("// φ² + 1/φ² = 3\n\n", .{});

    // MGEN-005: Standard Zig imports
    try w.print("const std = @import(\"std\");\n", .{});
    try w.print("const Allocator = std.mem.Allocator;\n\n", .{});

    // MGEN-005: Error set for the module
    try w.print("// Error set for {s}\n", .{spec.name});
    try w.print("const {s}Error = error{{\n", .{spec.name});
    try w.print("    InvalidOperation,\n", .{});
    try w.print("    NotFound,\n", .{});
    try w.print("    ValidationFailed,\n", .{});
    try w.print("}};\n\n", .{});

    // Generate types with methods
    for (spec.types) |t| {
        try w.print("/// {s} represents a {s} entity\n", .{t.name, t.name});
        try w.print("pub const {s} = struct {{\n", .{t.name});

        for (t.fields) |f| {
            const zig_type = mapTypeZigFluent(f.type_name);
            try w.print("    {s}: {s},\n", .{ f.name, zig_type });
        }

        try w.print("}};\n\n", .{});

        // MGEN-005: Add init method
        try w.print("/// Initialize a {s} with required fields\n", .{t.name});
        try w.print("pub fn {s}Init(allocator: Allocator", .{t.name});

        // Add non-optional fields as parameters
        for (t.fields) |f| {
            if (!isOptionalTypeZig(f.type_name)) {
                try w.print(", {s}: {s}", .{ f.name, mapTypeZigFluent(f.type_name) });
            }
        }

        try w.print(")!{s} {{\n", .{t.name});
        try w.print("    return .{{\n", .{});

        for (t.fields) |f| {
            if (isOptionalTypeZig(f.type_name)) {
                try w.print("        .{s} = null,\n", .{f.name});
            } else {
                try w.print("        .{s} = {s},\n", .{f.name, f.name});
            }
        }

        try w.print("    }};\n", .{});
        try w.print("}}\n\n", .{});

        // MGEN-005: Add deinit method if there are allocated fields
        const has_allocated = std.mem.indexOf(u8, t.fields[0].type_name, "List") != null;
        if (has_allocated) {
            try w.print("/// Free resources used by {s}\n", .{t.name});
            try w.print("pub fn {s}Deinit(self: *{s}, allocator: Allocator) void {{\n", .{t.name, t.name});
            try w.print("    _ = allocator;\n", .{});
            try w.print("    _ = self;\n", .{});
            try w.print("    // TODO: free allocated fields\n", .{});
            try w.print("}}\n\n", .{});
        }
    }

    // Generate behaviors with error returns
    for (spec.behaviors) |b| {
        if (b.implementation.len > 0) {
            const impl = std.mem.trim(u8, b.implementation, &std.ascii.whitespace);
            try w.print("/// Given: {s}, When: {s}, Then: {s}\n", .{ b.given, b.when, b.then });
            try w.print("{s}\n\n", .{impl});
        } else {
            // MGEN-005: Generate with error union return
            try w.print("/// Given: {s}, When: {s}, Then: {s}\n", .{ b.given, b.when, b.then });

            const is_comptime = std.mem.indexOf(u8, b.given, "comptime") != null or
                              std.mem.indexOf(u8, b.when, "comptime") != null;

            if (is_comptime) {
                try w.print("pub fn {s}() !void {{\n", .{b.name});
            } else {
                try w.print("pub fn {s}(allocator: Allocator) !void {{\n", .{b.name});
            }

            try w.print("    return {s}Error.NotImplemented;\n", .{spec.name});
            try w.print("}}\n\n", .{});
        }
    }

    return result.toOwnedSlice(allocator);
}

// MGEN-005: Enhanced type mapping with Zig idioms (Zig 0.15.x compatible)
fn mapTypeZigFluent(vibee_type: []const u8) []const u8 {
    if (std.mem.eql(u8, vibee_type, "String")) return "[]const u8";
    if (std.mem.eql(u8, vibee_type, "Int")) return "i64";
    if (std.mem.eql(u8, vibee_type, "Float")) return "f64";
    if (std.mem.eql(u8, vibee_type, "Bool")) return "bool";

    // Parse generic types - Zig 0.15.x: use std.array_list.Managed for dynamic arrays
    if (std.mem.startsWith(u8, vibee_type, "List<")) {
        const inner = vibee_type[5 .. vibee_type.len - 1];
        const inner_mapped = mapTypeZigFluent(inner);
        // Zig 0.15.x: std.ArrayList is now unmanaged, use std.array_list.Managed for managed lists
        if (std.mem.eql(u8, inner_mapped, "[]const u8")) return "std.array_list.Managed([]const u8)";
        if (std.mem.eql(u8, inner_mapped, "i64")) return "std.array_list.Managed(i64)";
        if (std.mem.eql(u8, inner_mapped, "u8")) return "std.array_list.Managed(u8)";
        return "std.array_list.Managed(u8)";
    }

    if (std.mem.startsWith(u8, vibee_type, "Option<")) {
        const inner = vibee_type[8 .. vibee_type.len - 1];
        const inner_mapped = mapTypeZigFluent(inner);
        if (std.mem.eql(u8, inner_mapped, "[]const u8")) return "?[]const u8";
        if (std.mem.eql(u8, inner_mapped, "i64")) return "?i64";
        return "?u8";
    }

    return "u8";
}

fn isOptionalTypeZig(vibee_type: []const u8) bool {
    return std.mem.startsWith(u8, vibee_type, "Option<");
}

// ═══════════════════════════════════════════════════════════════════════════════
// V GENERATOR (MGEN-006: Fluent V)
// ═══════════════════════════════════════════════════════════════════════════════

pub fn generateV(allocator: Allocator, spec: ParsedSpec) ![]u8 {
    var result: std.ArrayListUnmanaged(u8) = .empty;
    const w = result.writer(allocator);

    try w.print("// {s} v{s}\n", .{ spec.name, spec.version });
    try w.print("// Generated by VIBEE Multi-Language Generator (MGEN-006 Fluent V)\n", .{});
    try w.print("// φ² + 1/φ² = 3\n\n", .{});
    try w.print("module {s}\n\n", .{spec.name});

    // MGEN-006: Import modules
    try w.print("import math\n\n", .{});

    // MGEN-006: Result type
    try w.print("// Result type for error handling\n", .{});
    try w.print("pub type Result = !{{\n", .{});
    try w.print("\t_success bool\n", .{});
    try w.print("\t_message string\n", .{});
    try w.print("}}\n\n", .{});

    // Generate types
    for (spec.types) |t| {
        try w.print("// {s} represents a {s} entity\n", .{t.name, t.name});
        try w.print("pub struct {s} {{\n", .{t.name});

        for (t.fields) |f| {
            const v_type = mapTypeVFluent(f.type_name);
            try w.print("\tpub {s} {s}\n", .{ toSnakeCase(f.name), v_type });
        }

        try w.print("}}\n\n", .{});
    }

    // Generate behaviors
    for (spec.behaviors) |b| {
        if (b.implementation.len > 0) {
            const impl = std.mem.trim(u8, b.implementation, &std.ascii.whitespace);
            try w.print("// {s}: Given {s}, When {s}, Then {s}\n", .{ b.name, b.given, b.when, b.then });
            try w.print("{s}\n\n", .{impl});
        } else {
            try w.print("// {s}: Given {s}, When {s}, Then {s}\n", .{ b.name, b.given, b.when, b.then });
            try w.print("pub fn {s}() !Result {{\n", .{toSnakeCase(b.name)});
            try w.print("\treturn error('{s} not implemented')\n", .{b.name});
            try w.print("}}\n\n", .{});
        }
    }

    return result.toOwnedSlice(allocator);
}

// MGEN-006: Enhanced type mapping with V idioms
fn mapTypeVFluent(vibee_type: []const u8) []const u8 {
    if (std.mem.eql(u8, vibee_type, "String")) return "string";
    if (std.mem.eql(u8, vibee_type, "Int")) return "i64";
    if (std.mem.eql(u8, vibee_type, "Float")) return "f64";
    if (std.mem.eql(u8, vibee_type, "Bool")) return "bool";

    // Parse generic types
    if (std.mem.startsWith(u8, vibee_type, "List<")) {
        const inner = vibee_type[5 .. vibee_type.len - 1];
        const inner_mapped = mapTypeVFluent(inner);
        if (std.mem.eql(u8, inner_mapped, "string")) return "[]string";
        if (std.mem.eql(u8, inner_mapped, "i64")) return "[]i64";
        return "[]u8";
    }

    if (std.mem.startsWith(u8, vibee_type, "Option<")) {
        const inner = vibee_type[8 .. vibee_type.len - 1];
        const inner_mapped = mapTypeVFluent(inner);
        if (std.mem.eql(u8, inner_mapped, "string")) return "?string";
        if (std.mem.eql(u8, inner_mapped, "i64")) return "?i64";
        return "?u8";
    }

    return "u8";
}

// Helper: Convert to snake_case for V naming
fn toSnakeCase(s: []const u8) []const u8 {
    // For simplicity, return as-is (V often uses camel_case anyway)
    return s;
}

// ═══════════════════════════════════════════════════════════════════════════════
// JAVA GENERATOR
// ═══════════════════════════════════════════════════════════════════════════════

pub fn generateJava(allocator: Allocator, spec: ParsedSpec) ![]u8 {
    var result: std.ArrayListUnmanaged(u8) = .empty;
    const w = result.writer(allocator);

    try w.print("// {s} v{s}\n", .{ spec.name, spec.version });
    try w.print("// Generated by VIBEE Multi-Language Generator\n", .{});
    try w.print("// φ² + 1/φ² = 3\n\n", .{});
    try w.print("import java.util.*;\n\n", .{});

    for (spec.types) |t| {
        try w.print("public record {s}(\n", .{t.name});
        for (t.fields, 0..) |f, i| {
            const java_type = mapTypeJava(f.type_name);
            try w.print("    {s} {s}", .{ java_type, f.name });
            if (i < t.fields.len - 1) try w.print(",", .{});
            try w.print("\n", .{});
        }
        try w.print(") {{}}\n\n", .{});
    }

    return result.toOwnedSlice(allocator);
}

fn mapTypeJava(vibee_type: []const u8) []const u8 {
    if (std.mem.eql(u8, vibee_type, "String")) return "String";
    if (std.mem.eql(u8, vibee_type, "Int")) return "Long";
    if (std.mem.eql(u8, vibee_type, "Float")) return "Double";
    if (std.mem.eql(u8, vibee_type, "Bool")) return "Boolean";
    if (std.mem.startsWith(u8, vibee_type, "List")) return "List<Object>";
    if (std.mem.startsWith(u8, vibee_type, "Option")) return "Optional<Object>";
    return "Object";
}

// ═══════════════════════════════════════════════════════════════════════════════
// SWIFT GENERATOR
// ═══════════════════════════════════════════════════════════════════════════════

pub fn generateSwift(allocator: Allocator, spec: ParsedSpec) ![]u8 {
    var result: std.ArrayListUnmanaged(u8) = .empty;
    const w = result.writer(allocator);

    try w.print("// {s} v{s}\n", .{ spec.name, spec.version });
    try w.print("// Generated by VIBEE Multi-Language Generator\n", .{});
    try w.print("// φ² + 1/φ² = 3\n\n", .{});
    try w.print("import Foundation\n\n", .{});

    for (spec.types) |t| {
        try w.print("struct {s}: Codable {{\n", .{t.name});
        for (t.fields) |f| {
            const swift_type = mapTypeSwift(f.type_name);
            try w.print("    let {s}: {s}\n", .{ f.name, swift_type });
        }
        try w.print("}}\n\n", .{});
    }

    for (spec.behaviors) |b| {
        if (b.implementation.len > 0) {
            // Use custom implementation (contains full function definition)
            const impl = std.mem.trim(u8, b.implementation, &std.ascii.whitespace);
            try w.print("/// Given: {s}, When: {s}, Then: {s}\n", .{ b.given, b.when, b.then });
            try w.print("{s}\n\n", .{impl});
        } else {
            // Generate stub
            try w.print("/// Given: {s}, When: {s}, Then: {s}\n", .{ b.given, b.when, b.then });
            try w.print("func {s}() {{\n", .{b.name});
            try w.print("    // TODO: implement\n", .{});
            try w.print("}}\n\n", .{});
        }
    }

    return result.toOwnedSlice(allocator);
}

fn mapTypeSwift(vibee_type: []const u8) []const u8 {
    if (std.mem.eql(u8, vibee_type, "String")) return "String";
    if (std.mem.eql(u8, vibee_type, "Int")) return "Int64";
    if (std.mem.eql(u8, vibee_type, "Float")) return "Double";
    if (std.mem.eql(u8, vibee_type, "Bool")) return "Bool";
    if (std.mem.startsWith(u8, vibee_type, "List")) return "[Any]";
    if (std.mem.startsWith(u8, vibee_type, "Option")) return "Any?";
    return "Any";
}

// ═══════════════════════════════════════════════════════════════════════════════
// KOTLIN GENERATOR
// ═══════════════════════════════════════════════════════════════════════════════

pub fn generateKotlin(allocator: Allocator, spec: ParsedSpec) ![]u8 {
    var result: std.ArrayListUnmanaged(u8) = .empty;
    const w = result.writer(allocator);

    try w.print("// {s} v{s}\n", .{ spec.name, spec.version });
    try w.print("// Generated by VIBEE Multi-Language Generator\n", .{});
    try w.print("// φ² + 1/φ² = 3\n\n", .{});

    for (spec.types) |t| {
        try w.print("data class {s}(\n", .{t.name});
        for (t.fields, 0..) |f, i| {
            const kt_type = mapTypeKotlin(f.type_name);
            try w.print("    val {s}: {s}", .{ f.name, kt_type });
            if (i < t.fields.len - 1) try w.print(",", .{});
            try w.print("\n", .{});
        }
        try w.print(")\n\n", .{});
    }

    for (spec.behaviors) |b| {
        if (b.implementation.len > 0) {
            // Use custom implementation (contains full function definition)
            const impl = std.mem.trim(u8, b.implementation, &std.ascii.whitespace);
            try w.print("/** Given: {s}, When: {s}, Then: {s} */\n", .{ b.given, b.when, b.then });
            try w.print("{s}\n\n", .{impl});
        } else {
            // Generate stub
            try w.print("/** Given: {s}, When: {s}, Then: {s} */\n", .{ b.given, b.when, b.then });
            try w.print("fun {s}() {{\n", .{b.name});
            try w.print("    TODO(\"implement\")\n", .{});
            try w.print("}}\n\n", .{});
        }
    }

    return result.toOwnedSlice(allocator);
}

fn mapTypeKotlin(vibee_type: []const u8) []const u8 {
    if (std.mem.eql(u8, vibee_type, "String")) return "String";
    if (std.mem.eql(u8, vibee_type, "Int")) return "Long";
    if (std.mem.eql(u8, vibee_type, "Float")) return "Double";
    if (std.mem.eql(u8, vibee_type, "Bool")) return "Boolean";
    if (std.mem.startsWith(u8, vibee_type, "List")) return "List<Any>";
    if (std.mem.startsWith(u8, vibee_type, "Option")) return "Any?";
    return "Any";
}

// ═══════════════════════════════════════════════════════════════════════════════
// C HEADER GENERATOR
// ═══════════════════════════════════════════════════════════════════════════════

pub fn generateC(allocator: Allocator, spec: ParsedSpec) ![]u8 {
    var result: std.ArrayListUnmanaged(u8) = .empty;
    const w = result.writer(allocator);

    try w.print("/* {s} v{s} */\n", .{ spec.name, spec.version });
    try w.print("/* Generated by VIBEE Multi-Language Generator */\n", .{});
    try w.print("/* φ² + 1/φ² = 3 */\n\n", .{});
    try w.print("#ifndef {s}_H\n", .{spec.name});
    try w.print("#define {s}_H\n\n", .{spec.name});
    try w.print("#include <stdint.h>\n", .{});
    try w.print("#include <stdbool.h>\n\n", .{});

    for (spec.types) |t| {
        try w.print("typedef struct {{\n", .{});
        for (t.fields) |f| {
            const c_type = mapTypeC(f.type_name);
            try w.print("    {s} {s};\n", .{ c_type, f.name });
        }
        try w.print("}} {s};\n\n", .{t.name});
    }

    for (spec.behaviors) |b| {
        try w.print("/* Given: {s}, When: {s}, Then: {s} */\n", .{ b.given, b.when, b.then });
        try w.print("void {s}(void);\n\n", .{b.name});
    }

    try w.print("#endif /* {s}_H */\n", .{spec.name});

    return result.toOwnedSlice(allocator);
}

fn mapTypeC(vibee_type: []const u8) []const u8 {
    if (std.mem.eql(u8, vibee_type, "String")) return "const char*";
    if (std.mem.eql(u8, vibee_type, "Int")) return "int64_t";
    if (std.mem.eql(u8, vibee_type, "Float")) return "double";
    if (std.mem.eql(u8, vibee_type, "Bool")) return "bool";
    if (std.mem.startsWith(u8, vibee_type, "List")) return "void*";
    if (std.mem.startsWith(u8, vibee_type, "Option")) return "void*";
    return "void*";
}

// ═══════════════════════════════════════════════════════════════════════════════
// SQL GENERATOR
// ═══════════════════════════════════════════════════════════════════════════════

pub fn generateSQL(allocator: Allocator, spec: ParsedSpec) ![]u8 {
    var result: std.ArrayListUnmanaged(u8) = .empty;
    const w = result.writer(allocator);

    try w.print("-- {s} v{s}\n", .{ spec.name, spec.version });
    try w.print("-- Generated by VIBEE Multi-Language Generator\n", .{});
    try w.print("-- φ² + 1/φ² = 3\n\n", .{});

    // Generate CREATE TABLE statements for each type
    for (spec.types) |t| {
        try w.print("CREATE TABLE IF NOT EXISTS {s} (\n", .{t.name});
        try w.print("    id SERIAL PRIMARY KEY", .{});

        for (t.fields) |f| {
            const sql_type = mapTypeSQL(f.type_name);
            try w.print(",\n    {s} {s}", .{ f.name, sql_type });
        }

        try w.print(",\n    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP", .{});
        try w.print(",\n    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n", .{});
        try w.print(");\n\n", .{});
    }

    // Generate stored procedures for behaviors
    for (spec.behaviors) |b| {
        try w.print("-- Behavior: {s}\n", .{b.name});
        try w.print("-- Given: {s}\n", .{b.given});
        try w.print("-- When: {s}\n", .{b.when});
        try w.print("-- Then: {s}\n", .{b.then});
        try w.print("CREATE OR REPLACE FUNCTION {s}()\n", .{b.name});
        try w.print("RETURNS VOID AS $$\n", .{});
        try w.print("BEGIN\n", .{});
        try w.print("    -- TODO: implement\n", .{});
        try w.print("    NULL;\n", .{});
        try w.print("END;\n", .{});
        try w.print("$$ LANGUAGE plpgsql;\n\n", .{});
    }

    return result.toOwnedSlice(allocator);
}

fn mapTypeSQL(vibee_type: []const u8) []const u8 {
    if (std.mem.eql(u8, vibee_type, "String")) return "TEXT";
    if (std.mem.eql(u8, vibee_type, "Int")) return "BIGINT";
    if (std.mem.eql(u8, vibee_type, "Float")) return "DOUBLE PRECISION";
    if (std.mem.eql(u8, vibee_type, "Bool")) return "BOOLEAN";
    if (std.mem.eql(u8, vibee_type, "Timestamp")) return "TIMESTAMP";
    if (std.mem.startsWith(u8, vibee_type, "List")) return "JSONB";
    if (std.mem.startsWith(u8, vibee_type, "Option")) return "TEXT"; // nullable
    if (std.mem.startsWith(u8, vibee_type, "Map")) return "JSONB";
    return "TEXT";
}

// ═══════════════════════════════════════════════════════════════════════════════
// C++ GENERATOR (Modern C++20 with templates)
// ═══════════════════════════════════════════════════════════════════════════════

pub fn generateCpp(allocator: Allocator, spec: ParsedSpec) ![]u8 {
    var result: std.ArrayListUnmanaged(u8) = .empty;
    const w = result.writer(allocator);

    try w.print("// {s} v{s}\n", .{ spec.name, spec.version });
    try w.print("// Generated by VIBEE Multi-Language Generator\n", .{});
    try w.print("// Modern C++20 with concepts and modules\n", .{});
    try w.print("// φ² + 1/φ² = 3\n\n", .{});

    try w.print("#pragma once\n\n", .{});
    try w.print("#include <iostream>\n", .{});
    try w.print("#include <optional>\n", .{});
    try w.print("#include <vector>\n", .{});
    try w.print("#include <string>\n", .{});
    try w.print("#include <memory>\n", .{});
    try w.print("#include <format>\n", .{});
    try w.print("#include <concepts>\n\n", .{});

    try w.print("namespace {s} {{\n\n", .{spec.name});

    // Generate types as structs
    for (spec.types) |t| {
        try w.print("struct {s} {{\n", .{t.name});
        for (t.fields) |f| {
            const cpp_type = mapTypeCpp(f.type_name);
            try w.print("    {s} {s};\n", .{ cpp_type, f.name });
        }
        try w.print("\n", .{});
        try w.print("    auto operator<=>(const {s}&) const = default;\n", .{t.name});
        try w.print("}};\n\n", .{});
    }

    // Generate behaviors as functions
    for (spec.behaviors) |b| {
        try w.print("// Behavior: {s}\n", .{b.name});
        try w.print("// Given: {s}\n", .{b.given});
        try w.print("// When: {s}\n", .{b.when});
        try w.print("// Then: {s}\n", .{b.then});

        if (b.implementation.len > 0) {
            const impl = std.mem.trim(u8, b.implementation, &std.ascii.whitespace);
            try w.writeAll(impl);
            try w.writeAll("\n\n");
        } else {
            try w.print("void {s}() {{\n", .{b.name});
            try w.print("    // TODO: implement\n", .{});
            try w.print("}}\n\n", .{});
        }
    }

    try w.print("}} // namespace {s}\n", .{spec.name});

    return result.toOwnedSlice(allocator);
}

fn mapTypeCpp(vibee_type: []const u8) []const u8 {
    if (std.mem.eql(u8, vibee_type, "String")) return "std::string";
    if (std.mem.eql(u8, vibee_type, "Int")) return "int64_t";
    if (std.mem.eql(u8, vibee_type, "Float")) return "double";
    if (std.mem.eql(u8, vibee_type, "Bool")) return "bool";
    if (std.mem.startsWith(u8, vibee_type, "List")) return "std::vector auto";
    if (std.mem.startsWith(u8, vibee_type, "Option")) return "std::optional";
    return "auto";
}

// ═══════════════════════════════════════════════════════════════════════════════
// C# GENERATOR (Modern C# 12 with records)
// ═══════════════════════════════════════════════════════════════════════════════

pub fn generateCSharp(allocator: Allocator, spec: ParsedSpec) ![]u8 {
    var result: std.ArrayListUnmanaged(u8) = .empty;
    const w = result.writer(allocator);

    try w.print("// {s} v{s}\n", .{ spec.name, spec.version });
    try w.print("// Generated by VIBEE Multi-Language Generator\n", .{});
    try w.print("// Modern C# 12 with records and pattern matching\n", .{});
    try w.print("// φ² + 1/φ² = 3\n\n", .{});

    try w.print("using System;\n", .{});
    try w.print("using System.Collections.Generic;\n", .{});
    try w.print("using System.Linq;\n\n", .{});

    try w.print("namespace {s};\n\n", .{spec.name});

    // Generate types as records
    for (spec.types) |t| {
        try w.print("public record {s}(\n", .{t.name});
        for (t.fields, 0..) |f, i| {
            const cs_type = mapTypeCSharp(f.type_name);
            if (i > 0) try w.print(",\n", .{});
            try w.print("    {s} {s}", .{ cs_type, f.name });
        }
        try w.print("\n);\n\n", .{});
    }

    // Generate behaviors
    for (spec.behaviors) |b| {
        try w.print("// Behavior: {s}\n", .{b.name});
        try w.print("// Given: {s}\n", .{b.given});
        try w.print("// When: {s}\n", .{b.when});
        try w.print("// Then: {s}\n", .{b.then});

        if (b.implementation.len > 0) {
            const impl = std.mem.trim(u8, b.implementation, &std.ascii.whitespace);
            try w.writeAll(impl);
            try w.writeAll("\n\n");
        } else {
            try w.print("public void {s}()\n", .{b.name});
            try w.print("{{\n", .{});
            try w.print("    // TODO: implement\n", .{});
            try w.print("}}\n\n", .{});
        }
    }

    return result.toOwnedSlice(allocator);
}

fn mapTypeCSharp(vibee_type: []const u8) []const u8 {
    if (std.mem.eql(u8, vibee_type, "String")) return "string";
    if (std.mem.eql(u8, vibee_type, "Int")) return "long";
    if (std.mem.eql(u8, vibee_type, "Float")) return "double";
    if (std.mem.eql(u8, vibee_type, "Bool")) return "bool";
    if (std.mem.startsWith(u8, vibee_type, "List")) return "List";
    if (std.mem.startsWith(u8, vibee_type, "Option")) return "T?";
    return "object";
}

// ═══════════════════════════════════════════════════════════════════════════════
// RUBY GENERATOR (Modern Ruby 3 with pattern matching)
// ═══════════════════════════════════════════════════════════════════════════════

pub fn generateRuby(allocator: Allocator, spec: ParsedSpec) ![]u8 {
    var result: std.ArrayListUnmanaged(u8) = .empty;
    const w = result.writer(allocator);

    try w.print("# {s} v{s}\n", .{ spec.name, spec.version });
    try w.print("# Generated by VIBEE Multi-Language Generator\n", .{});
    try w.print("# Modern Ruby 3 with pattern matching\n", .{});
    try w.print("# φ² + 1/φ² = 3\n\n", .{});

    try w.print("module {s}\n", .{spec.name});
    try w.print("  # Custom exception\n", .{});
    try w.print("  class Error < StandardError; end\n\n", .{});

    // Generate types as classes with attr_accessor
    for (spec.types) |t| {
        try w.print("  class {s}\n", .{t.name});
        try w.print("    attr_accessor ", .{});

        for (t.fields, 0..) |f, i| {
            if (i > 0) try w.print(", ", .{});
            try w.print(":{s}", .{f.name});
        }
        try w.print("\n\n", .{});

        try w.print("    def initialize(", .{});
        for (t.fields, 0..) |f, i| {
            if (i > 0) try w.print(", ", .{});
            try w.print("{s}:", .{f.name});
        }
        try w.print(")\n", .{});
        for (t.fields) |f| {
            try w.print("      @{s} = {s}\n", .{ f.name, f.name });
        }
        try w.print("    end\n", .{});
        try w.print("  end\n\n", .{});
    }

    // Generate behaviors as module methods
    for (spec.behaviors) |b| {
        try w.print("  # Behavior: {s}\n", .{b.name});
        try w.print("  # Given: {s}\n", .{b.given});
        try w.print("  # When: {s}\n", .{b.when});
        try w.print("  # Then: {s}\n", .{b.then});

        if (b.implementation.len > 0) {
            const impl = std.mem.trim(u8, b.implementation, &std.ascii.whitespace);
            try w.writeAll(impl);
            try w.writeAll("\n\n");
        } else {
            try w.print("  def self.{s}\n", .{b.name});
            try w.print("    # TODO: implement\n", .{});
            try w.print("  end\n\n", .{});
        }
    }

    try w.print("end\n", .{});

    return result.toOwnedSlice(allocator);
}

// ═══════════════════════════════════════════════════════════════════════════════
// PHP GENERATOR (Modern PHP 8 with type hints)
// ═══════════════════════════════════════════════════════════════════════════════

pub fn generatePhp(allocator: Allocator, spec: ParsedSpec) ![]u8 {
    var result: std.ArrayListUnmanaged(u8) = .empty;
    const w = result.writer(allocator);

    try w.print("<?php\n", .{});
    try w.print("// {s} v{s}\n", .{ spec.name, spec.version });
    try w.print("// Generated by VIBEE Multi-Language Generator\n", .{});
    try w.print("// Modern PHP 8 with type hints and properties\n", .{});
    try w.print("// φ² + 1/φ² = 3\n\n", .{});

    try w.print("declare(strict_types=1);\n\n", .{});

    try w.print("namespace {s};\n\n", .{spec.name});

    // Generate types as classes
    for (spec.types) |t| {
        try w.print("class {s}\n", .{t.name});
        try w.print("{{\n", .{});
        for (t.fields) |f| {
            const php_type = mapTypePhp(f.type_name);
            try w.print("    public {s} $", .{php_type});
            try w.writeAll(f.name);
            try w.print(";\n", .{});
        }
        try w.print("\n", .{});
        try w.print("    public function __construct(", .{});
        for (t.fields, 0..) |f, i| {
            if (i > 0) try w.print(", ", .{});
            const php_type = mapTypePhp(f.type_name);
            try w.print("{s} $", .{php_type});
            try w.writeAll(f.name);
        }
        try w.print(")\n", .{});
        try w.print("    {{\n", .{});
        for (t.fields) |f| {
            try w.print("        $this->", .{});
            try w.writeAll(f.name);
            try w.print(" = $", .{});
            try w.writeAll(f.name);
            try w.print(";\n", .{});
        }
        try w.print("    }}\n", .{});
        try w.print("}}\n\n", .{});
    }

    // Generate behaviors as functions
    for (spec.behaviors) |b| {
        try w.print("// Behavior: {s}\n", .{b.name});
        try w.print("// Given: {s}\n", .{b.given});
        try w.print("// When: {s}\n", .{b.when});
        try w.print("// Then: {s}\n", .{b.then});

        if (b.implementation.len > 0) {
            const impl = std.mem.trim(u8, b.implementation, &std.ascii.whitespace);
            try w.writeAll(impl);
            try w.writeAll("\n\n");
        } else {
            try w.print("function {s}(): void\n", .{b.name});
            try w.print("{{\n", .{});
            try w.print("    // TODO: implement\n", .{});
            try w.print("}}\n\n", .{});
        }
    }

    return result.toOwnedSlice(allocator);
}

fn mapTypePhp(vibee_type: []const u8) []const u8 {
    if (std.mem.eql(u8, vibee_type, "String")) return "string";
    if (std.mem.eql(u8, vibee_type, "Int")) return "int";
    if (std.mem.eql(u8, vibee_type, "Float")) return "float";
    if (std.mem.eql(u8, vibee_type, "Bool")) return "bool";
    if (std.mem.startsWith(u8, vibee_type, "List")) return "array";
    if (std.mem.startsWith(u8, vibee_type, "Option")) return "?";
    return "mixed";
}

// ═══════════════════════════════════════════════════════════════════════════════
// DART GENERATOR (Dart 3 with null safety)
// ═══════════════════════════════════════════════════════════════════════════════

pub fn generateDart(allocator: Allocator, spec: ParsedSpec) ![]u8 {
    var result: std.ArrayListUnmanaged(u8) = .empty;
    const w = result.writer(allocator);

    try w.print("// {s} v{s}\n", .{ spec.name, spec.version });
    try w.print("// Generated by VIBEE Multi-Language Generator\n", .{});
    try w.print("// Dart 3 with null safety and records\n", .{});
    try w.print("// φ² + 1/φ² = 3\n\n", .{});

    // Generate types as classes
    for (spec.types) |t| {
        try w.print("class {s} {{\n", .{t.name});
        for (t.fields) |f| {
            const dart_type = mapTypeDart(f.type_name);
            try w.print("  {s} {s};\n", .{ dart_type, f.name });
        }
        try w.print("\n", .{});
        try w.print("  {s}({{", .{t.name});
        for (t.fields, 0..) |f, i| {
            if (i > 0) try w.print(", ", .{});
            try w.print("required this.{s}", .{f.name});
        }
        try w.print("}});\n", .{});
        try w.print("}}\n\n", .{});
    }

    // Generate behaviors
    for (spec.behaviors) |b| {
        try w.print("// Behavior: {s}\n", .{b.name});
        try w.print("// Given: {s}\n", .{b.given});
        try w.print("// When: {s}\n", .{b.when});
        try w.print("// Then: {s}\n", .{b.then});

        if (b.implementation.len > 0) {
            const impl = std.mem.trim(u8, b.implementation, &std.ascii.whitespace);
            try w.writeAll(impl);
            try w.writeAll("\n\n");
        } else {
            try w.print("void {s}() {{\n", .{b.name});
            try w.print("  // TODO: implement\n", .{});
            try w.print("}}\n\n", .{});
        }
    }

    return result.toOwnedSlice(allocator);
}

fn mapTypeDart(vibee_type: []const u8) []const u8 {
    if (std.mem.eql(u8, vibee_type, "String")) return "String";
    if (std.mem.eql(u8, vibee_type, "Int")) return "int";
    if (std.mem.eql(u8, vibee_type, "Float")) return "double";
    if (std.mem.eql(u8, vibee_type, "Bool")) return "bool";
    if (std.mem.startsWith(u8, vibee_type, "List")) return "List";
    if (std.mem.startsWith(u8, vibee_type, "Option")) return "T?";
    return "dynamic";
}

// ═══════════════════════════════════════════════════════════════════════════════
// LUA GENERATOR (Lua 5.4 with metatables)
// ═══════════════════════════════════════════════════════════════════════════════

pub fn generateLua(allocator: Allocator, spec: ParsedSpec) ![]u8 {
    var result: std.ArrayListUnmanaged(u8) = .empty;
    const w = result.writer(allocator);

    try w.print("-- {s} v{s}\n", .{ spec.name, spec.version });
    try w.print("-- Generated by VIBEE Multi-Language Generator\n", .{});
    try w.print("-- Lua 5.4 with metatables and OOP\n", .{});
    try w.print("-- φ² + 1/φ² = 3\n\n", .{});

    try w.print("local {s} = {{}}\n\n", .{spec.name});

    // Generate types as metatable-based classes
    for (spec.types) |t| {
        try w.print("{s}.{s} = {{}}\n", .{ spec.name, t.name });
        try w.print("{s}.{s}.__index = {s}.{s}\n\n", .{ spec.name, t.name, spec.name, t.name });

        try w.print("function {s}.{s}.new(", .{ spec.name, t.name });
        for (t.fields, 0..) |f, i| {
            if (i > 0) try w.print(", ", .{});
            try w.print("{s}", .{f.name});
        }
        try w.print(")\n", .{});
        try w.print("  local self = setmetatable({{}}, {s}.{s})\n", .{ spec.name, t.name });
        for (t.fields) |f| {
            try w.print("  self.{s} = {s}\n", .{ f.name, f.name });
        }
        try w.print("  return self\n", .{});
        try w.print("end\n\n", .{});
    }

    // Generate behaviors
    for (spec.behaviors) |b| {
        try w.print("-- Behavior: {s}\n", .{b.name});
        try w.print("-- Given: {s}\n", .{b.given});
        try w.print("-- When: {s}\n", .{b.when});
        try w.print("-- Then: {s}\n", .{b.then});

        if (b.implementation.len > 0) {
            const impl = std.mem.trim(u8, b.implementation, &std.ascii.whitespace);
            try w.writeAll(impl);
            try w.writeAll("\n\n");
        } else {
            try w.print("function {s}.{s}(self)\n", .{ spec.name, b.name });
            try w.print("  -- TODO: implement\n", .{});
            try w.print("end\n\n", .{});
        }
    }

    try w.print("return {s}\n", .{spec.name});

    return result.toOwnedSlice(allocator);
}

// ═══════════════════════════════════════════════════════════════════════════════
// R GENERATOR (R 4.x with S3 classes)
// ═══════════════════════════════════════════════════════════════════════════════

pub fn generateR(allocator: Allocator, spec: ParsedSpec) ![]u8 {
    var result: std.ArrayListUnmanaged(u8) = .empty;
    const w = result.writer(allocator);

    try w.print("# {s} v{s}\n", .{ spec.name, spec.version });
    try w.print("# Generated by VIBEE Multi-Language Generator\n", .{});
    try w.print("# R 4.x with S3 classes and functional patterns\n", .{});
    try w.print("# φ² + 1/φ² = 3\n\n", .{});

    // Generate types as S3 classes
    for (spec.types) |t| {
        try w.print("# S3 class: {s}\n", .{t.name});
        try w.print("{s}_class <- function(...) {{\n", .{t.name});
        try w.print("  structure <- list(\n", .{});
        for (t.fields, 0..) |f, i| {
            if (i > 0) try w.print(",\n", .{});
            try w.print("    {s} = NULL", .{f.name});
        }
        try w.print("\n", .{});
        try w.print("  )\n", .{});
        try w.print("  ret <- structure\n", .{});
        try w.print("  class(ret) <- \"{s}\"\n", .{t.name});
        try w.print("  ret\n", .{});
        try w.print("}}\n\n", .{});
    }

    // Generate behaviors as functions
    for (spec.behaviors) |b| {
        try w.print("# Behavior: {s}\n", .{b.name});
        try w.print("# Given: {s}\n", .{b.given});
        try w.print("# When: {s}\n", .{b.when});
        try w.print("# Then: {s}\n", .{b.then});

        if (b.implementation.len > 0) {
            const impl = std.mem.trim(u8, b.implementation, &std.ascii.whitespace);
            try w.writeAll(impl);
            try w.writeAll("\n\n");
        } else {
            try w.print("{s} <- function(...) {{\n", .{b.name});
            try w.print("  # TODO: implement\n", .{});
            try w.print("}}\n\n", .{});
        }
    }

    return result.toOwnedSlice(allocator);
}

// ═══════════════════════════════════════════════════════════════════════════════
// MATLAB GENERATOR (Modern MATLAB with OOP)
// ═══════════════════════════════════════════════════════════════════════════════

pub fn generateMatlab(allocator: Allocator, spec: ParsedSpec) ![]u8 {
    var result: std.ArrayListUnmanaged(u8) = .empty;
    const w = result.writer(allocator);

    try w.print("% {s} v{s}\n", .{ spec.name, spec.version });
    try w.print("% Generated by VIBEE Multi-Language Generator\n", .{});
    try w.print("% MATLAB with classdef and OOP\n", .{});
    try w.print("% φ² + 1/φ² = 3\n\n", .{});

    // Generate types as classdef
    for (spec.types) |t| {
        try w.print("classdef {s}\n", .{t.name});
        try w.print("  properties\n", .{});
        for (t.fields) |f| {
            try w.print("    {s}\n", .{f.name});
        }
        try w.print("  end\n\n", .{});

        try w.print("  methods\n", .{});
        try w.print("    function obj = {s}(", .{t.name});
        for (t.fields, 0..) |f, i| {
            if (i > 0) try w.print(", ", .{});
            try w.print("{s}", .{f.name});
        }
        try w.print(")\n", .{});
        try w.print("      if nargin > 0\n", .{});
        for (t.fields) |f| {
            try w.print("        obj.{s} = {s};\n", .{ f.name, f.name });
        }
        try w.print("      end\n", .{});
        try w.print("    end\n", .{});
        try w.print("  end\n", .{});
        try w.print("end\n\n", .{});
    }

    // Generate behaviors
    for (spec.behaviors) |b| {
        try w.print("% Behavior: {s}\n", .{b.name});
        try w.print("% Given: {s}\n", .{b.given});
        try w.print("% When: {s}\n", .{b.when});
        try w.print("% Then: {s}\n", .{b.then});

        if (b.implementation.len > 0) {
            const impl = std.mem.trim(u8, b.implementation, &std.ascii.whitespace);
            try w.writeAll(impl);
            try w.writeAll("\n\n");
        } else {
            try w.print("function {s}()\n", .{b.name});
            try w.print("  % TODO: implement\n", .{});
            try w.print("end\n\n", .{});
        }
    }

    return result.toOwnedSlice(allocator);
}

// ═══════════════════════════════════════════════════════════════════════════════
// DISPATCH FUNCTION
// ═══════════════════════════════════════════════════════════════════════════════

pub fn generateForLanguage(allocator: Allocator, spec: ParsedSpec, lang: []const u8) ![]u8 {
    if (std.mem.eql(u8, lang, "python")) return generatePython(allocator, spec);
    if (std.mem.eql(u8, lang, "rust")) return generateRust(allocator, spec);
    if (std.mem.eql(u8, lang, "go")) return generateGo(allocator, spec);
    if (std.mem.eql(u8, lang, "typescript")) return generateTypeScript(allocator, spec);
    if (std.mem.eql(u8, lang, "java")) return generateJava(allocator, spec);
    if (std.mem.eql(u8, lang, "swift")) return generateSwift(allocator, spec);
    if (std.mem.eql(u8, lang, "kotlin")) return generateKotlin(allocator, spec);
    if (std.mem.eql(u8, lang, "c")) return generateC(allocator, spec);
    if (std.mem.eql(u8, lang, "sql")) return generateSQL(allocator, spec);
    if (std.mem.eql(u8, lang, "cpp")) return generateCpp(allocator, spec);
    if (std.mem.eql(u8, lang, "csharp")) return generateCSharp(allocator, spec);
    if (std.mem.eql(u8, lang, "ruby")) return generateRuby(allocator, spec);
    if (std.mem.eql(u8, lang, "php")) return generatePhp(allocator, spec);
    if (std.mem.eql(u8, lang, "dart")) return generateDart(allocator, spec);
    if (std.mem.eql(u8, lang, "lua")) return generateLua(allocator, spec);
    if (std.mem.eql(u8, lang, "r")) return generateR(allocator, spec);
    if (std.mem.eql(u8, lang, "matlab")) return generateMatlab(allocator, spec);

    // Default: return stub
    var result: std.ArrayListUnmanaged(u8) = .empty;
    try result.writer(allocator).print("// {s} v{s} - {s}\n// TODO: implement generator\n", .{ spec.name, spec.version, lang });
    return result.toOwnedSlice(allocator);
}

// ═══════════════════════════════════════════════════════════════════════════════
// TESTS
// ═══════════════════════════════════════════════════════════════════════════════

test "generate python" {
    const allocator = std.testing.allocator;
    const spec = ParsedSpec{
        .name = "test",
        .version = "1.0.0",
        .types = &[_]TypeDef{},
        .behaviors = &[_]Behavior{},
    };
    const code = try generatePython(allocator, spec);
    defer allocator.free(code);
    try std.testing.expect(std.mem.indexOf(u8, code, "dataclass") != null);
}

test "generate rust" {
    const allocator = std.testing.allocator;
    const spec = ParsedSpec{
        .name = "test",
        .version = "1.0.0",
        .types = &[_]TypeDef{},
        .behaviors = &[_]Behavior{},
    };
    const code = try generateRust(allocator, spec);
    defer allocator.free(code);
    try std.testing.expect(std.mem.indexOf(u8, code, "serde") != null);
}

test "generate go" {
    const allocator = std.testing.allocator;
    const spec = ParsedSpec{
        .name = "test",
        .version = "1.0.0",
        .types = &[_]TypeDef{},
        .behaviors = &[_]Behavior{},
    };
    const code = try generateGo(allocator, spec);
    defer allocator.free(code);
    try std.testing.expect(std.mem.indexOf(u8, code, "package") != null);
}

test "generate sql" {
    const allocator = std.testing.allocator;
    const spec = ParsedSpec{
        .name = "test",
        .version = "1.0.0",
        .types = &[_]TypeDef{},
        .behaviors = &[_]Behavior{},
    };
    const code = try generateSQL(allocator, spec);
    defer allocator.free(code);
    try std.testing.expect(std.mem.indexOf(u8, code, "Generated by VIBEE") != null);
}

test "generate sql with types" {
    const allocator = std.testing.allocator;

    const fields = [_]Field{
        .{ .name = "username", .type_name = "String" },
        .{ .name = "age", .type_name = "Int" },
        .{ .name = "active", .type_name = "Bool" },
    };

    const types = [_]TypeDef{
        .{ .name = "User", .fields = &fields },
    };

    const behaviors = [_]Behavior{
        .{ .name = "create_user", .given = "Valid data", .when = "Request", .then = "Insert" },
    };

    const spec = ParsedSpec{
        .name = "user_db",
        .version = "1.0.0",
        .types = &types,
        .behaviors = &behaviors,
    };

    const code = try generateSQL(allocator, spec);
    defer allocator.free(code);

    // Check CREATE TABLE
    try std.testing.expect(std.mem.indexOf(u8, code, "CREATE TABLE IF NOT EXISTS User") != null);
    try std.testing.expect(std.mem.indexOf(u8, code, "username TEXT") != null);
    try std.testing.expect(std.mem.indexOf(u8, code, "age BIGINT") != null);
    try std.testing.expect(std.mem.indexOf(u8, code, "active BOOLEAN") != null);

    // Check stored procedure
    try std.testing.expect(std.mem.indexOf(u8, code, "CREATE OR REPLACE FUNCTION create_user") != null);
    try std.testing.expect(std.mem.indexOf(u8, code, "LANGUAGE plpgsql") != null);
}

// ═══════════════════════════════════════════════════════════════════════════════
// NEW LANGUAGE GENERATOR TESTS
// ═══════════════════════════════════════════════════════════════════════════════

test "generate cpp" {
    const allocator = std.testing.allocator;
    const spec = ParsedSpec{
        .name = "test",
        .version = "1.0.0",
        .types = &[_]TypeDef{},
        .behaviors = &[_]Behavior{},
    };
    const code = try generateCpp(allocator, spec);
    defer allocator.free(code);
    try std.testing.expect(std.mem.indexOf(u8, code, "namespace test") != null);
    try std.testing.expect(std.mem.indexOf(u8, code, "#pragma once") != null);
}

test "generate csharp" {
    const allocator = std.testing.allocator;
    const spec = ParsedSpec{
        .name = "test",
        .version = "1.0.0",
        .types = &[_]TypeDef{},
        .behaviors = &[_]Behavior{},
    };
    const code = try generateCSharp(allocator, spec);
    defer allocator.free(code);
    try std.testing.expect(std.mem.indexOf(u8, code, "namespace test;") != null);
}

test "generate ruby" {
    const allocator = std.testing.allocator;
    const spec = ParsedSpec{
        .name = "test",
        .version = "1.0.0",
        .types = &[_]TypeDef{},
        .behaviors = &[_]Behavior{},
    };
    const code = try generateRuby(allocator, spec);
    defer allocator.free(code);
    try std.testing.expect(std.mem.indexOf(u8, code, "module test") != null);
    try std.testing.expect(std.mem.indexOf(u8, code, "class Error") != null);
}

test "generate php" {
    const allocator = std.testing.allocator;
    const spec = ParsedSpec{
        .name = "test",
        .version = "1.0.0",
        .types = &[_]TypeDef{},
        .behaviors = &[_]Behavior{},
    };
    const code = try generatePhp(allocator, spec);
    defer allocator.free(code);
    try std.testing.expect(std.mem.indexOf(u8, code, "<?php") != null);
    try std.testing.expect(std.mem.indexOf(u8, code, "namespace test;") != null);
}

test "generate dart" {
    const allocator = std.testing.allocator;
    const spec = ParsedSpec{
        .name = "test",
        .version = "1.0.0",
        .types = &[_]TypeDef{},
        .behaviors = &[_]Behavior{},
    };
    const code = try generateDart(allocator, spec);
    defer allocator.free(code);
    try std.testing.expect(std.mem.indexOf(u8, code, "Dart 3") != null);
}

test "generate lua" {
    const allocator = std.testing.allocator;
    const spec = ParsedSpec{
        .name = "test",
        .version = "1.0.0",
        .types = &[_]TypeDef{},
        .behaviors = &[_]Behavior{},
    };
    const code = try generateLua(allocator, spec);
    defer allocator.free(code);
    try std.testing.expect(std.mem.indexOf(u8, code, "local test") != null);
    try std.testing.expect(std.mem.indexOf(u8, code, "Lua 5.4") != null);
}

test "generate r" {
    const allocator = std.testing.allocator;
    const spec = ParsedSpec{
        .name = "test",
        .version = "1.0.0",
        .types = &[_]TypeDef{},
        .behaviors = &[_]Behavior{},
    };
    const code = try generateR(allocator, spec);
    defer allocator.free(code);
    try std.testing.expect(std.mem.indexOf(u8, code, "R 4.x") != null);
}

test "generate matlab" {
    const allocator = std.testing.allocator;
    const spec = ParsedSpec{
        .name = "test",
        .version = "1.0.0",
        .types = &[_]TypeDef{},
        .behaviors = &[_]Behavior{},
    };
    const code = try generateMatlab(allocator, spec);
    defer allocator.free(code);
    try std.testing.expect(std.mem.indexOf(u8, code, "MATLAB") != null);
}
