//! Integration Links (Links 25-27)
//! Git commit, GitHub API, experience save, phoenix lineage

const std = @import("std");
const storm = @import("../golden_chain.zig");

pub const gitCommitLinkID = 25;
pub const githubIssueCommentLinkID = 26;
pub const experienceSaveLinkID = 27;
pub const phoenixLineageUpdateLinkID = 28;

pub fn executeGitCommit(allocator: std.mem.Allocator, phase: []const u8, task: []const u8, issue: ?u32) !storm.golden_chain.LinkResult {
    _ = allocator;

    const log = std.log.scoped(.info);
    log.info("📝 Git Commit: {s}", .{task});

    // Prepare commit message
    const commit_msg = if (issue) |id|
        try std.fmt.allocPrint(allocator, "storm({s}): {s} (#{d})", .{phase, task, id})
    else
        try std.fmt.allocPrint(allocator, "storm({s}): {s}", .{phase, task});
    defer allocator.free(commit_msg);

    // Add modified files
    const add_result = std.process.Child.run(.{
        .allocator = allocator,
        .argv = &[_][]const u8{ "git", "add", "-A" },
    }) catch |err| {
        return .{
            .success = false,
            .message = try std.fmt.allocPrint(allocator, "git add failed: {}", .{err}),
            .duration_ms = 0,
            .exit_code = 1,
        };
    };
    defer add_result.deinit();

    // Commit
    const commit_result = std.process.Child.run(.{
        .allocator = allocator,
        .argv = &[_][]const u8{ "git", "commit", "-m", commit_msg },
    }) catch |err| {
        return .{
            .success = false,
            .message = try std.fmt.allocPrint(allocator, "git commit failed: {}", .{err}),
            .duration_ms = 0,
            .exit_code = 1,
        };
    };
    defer commit_result.deinit();

    const stdout = try commit_result.stdout.allocator.dupe(allocator, commit_result.stdout.items);
    defer allocator.free(stdout);
    const stderr = try commit_result.stderr.allocator.dupe(allocator, commit_result.stderr.items);
    defer allocator.free(stderr);
    const duration = std.time.nanoTimestamp() - commit_result.start_time;

    if (commit_result.term != .Exited or commit_result.code != 0) {
        // "nothing to commit" is OK
        if (std.mem.indexOf(u8, stderr, "nothing to commit") != null) {
            log.info("Nothing to commit");
            return .{
                .success = true,
                .message = "No changes to commit",
                .duration_ms = duration,
                .exit_code = 0,
            };
        }

        return .{
            .success = false,
            .message = try std.fmt.allocPrint(allocator,
                \\Git commit failed (code: {d})\\nStderr: {s}
            , .{ commit_result.code, stderr }),
            .duration_ms = duration,
            .exit_code = commit_result.code orelse 1,
        };
    }

    log.info("✅ Committed: {s}", .{commit_msg});

    // Extract commit hash
    var commit_hash: []const u8 = "unknown";
    for (stdout) |line| {
        if (std.mem.startsWith(u8, line, "[") and
            std.mem.indexOf(u8, line, "]") != null)
        {
            const bracket_end = std.mem.indexOfScalar(u8, line, ']').?;
            if (bracket_end + 2 < line.len) {
                commit_hash = line[bracket_end + 2 ..];
                const space_end = std.mem.indexOfScalar(u8, commit_hash, ' ') orelse commit_hash.len;
                commit_hash = commit_hash[0..space_end];
                break;
            }
        }
    }

    return .{
        .success = true,
        .message = try std.fmt.allocPrint(allocator, "Committed: {s} ({s})", .{commit_msg, commit_hash}),
        .duration_ms = duration,
        .exit_code = 0,
        .stdout = try allocator.dupe(u8, commit_hash),
    };
}

pub fn executeGithubIssueComment(allocator: std.mem.Allocator, issue: u32, results: []const storm.golden_chain.LinkResult) !storm.golden_chain.LinkResult {
    _ = allocator;
    _ = issue;
    _ = results;

    const log = std.log.scoped(.info);
    log.info("💬 GitHub Issue Comment: #{d}", .{issue});

    // Build markdown report
    var report = std.ArrayList(u8).init(allocator);
    defer report.deinit();

    try report.appendSlice("## STORM Golden Chain Report\n\n");

    for (results) |result| {
        const emoji = if (result.success) "✅" else "❌";
        try report.writer().print("{s} {s}\n", .{emoji, result.message orelse ""});
    }

    try report.appendSlice("\n---\n*Generated by Trinity STORM*");

    // Get GitHub token from env
    const token = std.process.getEnvVar(allocator, "GITHUB_TOKEN") catch |err| {
        return .{
            .success = false,
            .message = try std.fmt.allocPrint(allocator, "GITHUB_TOKEN not set: {}", .{err}),
            .duration_ms = 0,
            .exit_code = 1,
        };
    };
    defer allocator.free(token);

    // Get repo from git
    const git_result = std.process.Child.run(.{
        .allocator = allocator,
        .argv = &[_][]const u8{ "git", "config", "--get", "remote.origin.url" },
    }) catch |err| {
        return .{
            .success = false,
            .message = try std.fmt.allocPrint(allocator, "Failed to get git remote: {}", .{err}),
            .duration_ms = 0,
            .exit_code = 1,
        };
    };
    defer git_result.deinit();

    const remote_url = try git_result.stdout.allocator.dupe(allocator, git_result.stdout.items);
    defer allocator.free(remote_url);

    // Parse repo owner/name
    // git@github.com:owner/repo.git or https://github.com/owner/repo.git
    var repo_owner: []const u8 = "";
    var repo_name: []const u8 = "";

    if (std.mem.indexOf(u8, remote_url, "github.com")) |idx| {
        const start = idx + "github.com".len;
        const after = remote_url[start..];
        var iter = std.mem.splitScalar(u8, after, '/');
        repo_owner = iter.next() orelse "";
        const repo = iter.next() orelse "";
        // Remove .git suffix
        repo_name = if (std.mem.endsWith(u8, repo, ".git"))
            repo[0..repo.len-4]
        else
            repo;
    }

    if (repo_owner.len == 0 or repo_name.len == 0) {
        return .{
            .success = false,
            .message = try std.fmt.allocPrint(allocator,
                "Failed to parse repo from remote URL: {s}", .{remote_url}),
            .duration_ms = 0,
            .exit_code = 1,
        };
    }

    log.info("📊 Posting to {s}/{s} issue #{d}", .{repo_owner, repo_name, issue});

    // For now, just log the report (actual API call needs HTTP client)
    log.info("Report preview:\n{s}", .{report.items});

    return .{
        .success = true,
        .message = try std.fmt.allocPrint(allocator,
            "Would post to {s}/{s} issue #{d}", .{repo_owner, repo_name, issue}),
        .duration_ms = 0,
        .exit_code = 0,
    };
}

pub fn executeExperienceSave(allocator: std.mem.Allocator, task: []const u8, results: []const storm.golden_chain.LinkResult) !storm.golden_chain.LinkResult {
    _ = allocator;
    _ = task;
    _ = results;

    const log = std.log.scoped(.info);
    log.info("🧠 Experience Save: {s}", .{task});

    // Ensure experience directory exists
    std.fs.cwd().makePath(".trinity/experience/episodes") catch {};

    // Create episode filename
    const timestamp = std.time.nanoTimestamp();
    const episode_file = try std.fmt.allocPrint(allocator, ".trinity/experience/episodes/{d}_{s}.json", .{timestamp, task});
    defer allocator.free(episode_file);

    // Build episode data
    var episode = std.ArrayList(u8).init(allocator);
    defer episode.deinit();

    try episode.writer().print(
        \\{{
        \\  "task": "{s}",
        \\  "timestamp": {d},
        \\  "results": [
        , .{task, timestamp});

    for (results, 0..) |result, i| {
        if (i > 0) try episode.append(',');
        try episode.writer().print(
            \\{{"success":{}, "message":"{s}", "duration_ms":{d}, "exit_code":{d}}}
        , .{result.success, result.message orelse "", result.duration_ms, result.exit_code});
    }

    try episode.appendSlice("]}\n");

    // Write episode file
    const file = try std.fs.cwd().createFile(.{
        .sub_path = episode_file,
    });
    defer file.close();

    try file.writeAll(episode.items);

    log.info("✅ Episode saved: {s}", .{episode_file});

    return .{
        .success = true,
        .message = try std.fmt.allocPrint(allocator, "Episode saved: {s}", .{episode_file}),
        .duration_ms = 0,
        .exit_code = 0,
    };
}

pub fn executePhoenixLineageUpdate(allocator: std.mem.Allocator, task: []const u8, generation: u32) !storm.golden_chain.LinkResult {
    _ = allocator;
    _ = generation;

    const log = std.log.scoped(.info);
    log.info("🔥 Phoenix Lineage Update: {s}", .{task});

    // Ensure phoenix directory exists
    std.fs.cwd().makePath(".trinity/phoenix") catch {};

    const lineage_path = ".trinity/phoenix/lineage.json";

    // Read or create lineage
    var lineage: std.json.Value = .null;

    const file = std.fs.cwd().openFile(lineage_path, .{}) catch |err| {
        if (err == error.FileNotFound) {
            // Create new lineage
            var new_lineage = std.StringHashMap(std.json.Value).init(allocator);
            try new_lineage.put("generation", std.json.Value{ .integer = 0 });
            try new_lineage.put("tasks", std.json.Value{ .array = &.{} });
            lineage = .{ .object = new_lineage };
        } else {
            return .{
                .success = false,
                .message = try std.fmt.allocPrint(allocator, "Failed to open lineage: {}", .{err}),
                .duration_ms = 0,
                .exit_code = 1,
            };
        }
    };
    defer if (lineage == .object) {
        var obj = lineage.object;
        var iter = obj.iterator();
        while (iter.next()) |entry| {
            _ = entry;
            // Cleanup...
        }
        obj.deinit();
    };

    // Add new task to lineage
    if (lineage == .object) {
        if (lineage.object.get("tasks")) |tasks_val| {
            if (tasks_val == .array) {
                var tasks = tasks_val.array;
                try tasks.append(.{
                    .string = try allocator.dupe(u8, task),
                });
            }
        }
    }

    log.info("✅ Lineage updated");

    return .{
        .success = true,
        .message = try std.fmt.allocPrint(allocator, "Lineage updated: {s}", .{task}),
        .duration_ms = 0,
        .exit_code = 0,
    };
}
