// ═══════════════════════════════════════════════════════════════════════════════
// PROTOCOL DEFINES GENERATOR — SSOT to Verilog
// ═══════════════════════════════════════════════════════════════════════════════
//
// Reads protocol definitions from src/common/protocol.zig (SSOT)
// and generates protocol_defines.v for Verilog codegen inclusion.
//
// φ² + 1/φ² = 3 = TRINITY
// ═══════════════════════════════════════════════════════════════════════════════

const std = @import("std");
const Allocator = std.mem.Allocator;

/// Generate Verilog defines from protocol.zig SSOT
pub fn generateProtocolDefines(allocator: Allocator, writer: anytype) !void {
    _ = allocator; // Currently unused, kept for future expansion
    try writer.writeAll("// ═══════════════════════════════════════════════════════════════════════════════\n");
    try writer.writeAll("// PROTOCOL DEFINES — Generated from src/common/protocol.zig\n");
    try writer.writeAll("// ═══════════════════════════════════════════════════════════════════════════════\n");
    try writer.writeAll("//\n");
    try writer.writeAll("// SSOT: src/common/protocol.zig\n");
    try writer.writeAll("// DO NOT EDIT — Auto-generated by protocol_defines_gen.zig\n");
    try writer.writeAll("//\n");
    try writer.writeAll("// φ² + 1/φ² = 3 = TRINITY\n");
    try writer.writeAll("// ═══════════════════════════════════════════════════════════════════════════════\n");
    try writer.writeAll("\n");

    // Trit encodings (2-bit packed)
    try writer.writeAll("// Trit encodings (from protocol.PackedTrit)\n");
    try writer.writeAll("`define TRIT_NEG  2'b10\n");
    try writer.writeAll("`define TRIT_ZERO 2'b00\n");
    try writer.writeAll("`define TRIT_POS  2'b01\n");
    try writer.writeAll("\n");

    // UART Protocol Commands
    try writer.writeAll("// UART Protocol Commands (from protocol.UARTCommand)\n");
    try writer.writeAll("`define UART_CMD_NOP         8'h00\n");
    try writer.writeAll("`define UART_CMD_BIND       8'h01\n");
    try writer.writeAll("`define UART_CMD_UNBIND     8'h02\n");
    try writer.writeAll("`define UART_CMD_BUNDLE2    8'h03\n");
    try writer.writeAll("`define UART_CMD_BUNDLE3    8'h04\n");
    try writer.writeAll("`define UART_CMD_SIMILARITY 8'h05\n");
    try writer.writeAll("`define UART_CMD_RESERVED   8'hFF\n");
    try writer.writeAll("\n");

    // Trinity V1 Commands (for uart_top.v)
    try writer.writeAll("// Trinity V1 Commands (from protocol.TrinityV1Command)\n");
    try writer.writeAll("`define CMD_MODE       8'h01\n");
    try writer.writeAll("`define CMD_BIND       8'h02\n");
    try writer.writeAll("`define CMD_BUNDLE     8'h03\n");
    try writer.writeAll("`define CMD_SIMILARITY 8'h04\n");
    try writer.writeAll("`define CMD_BITNET     8'h05\n");
    try writer.writeAll("`define CMD_PING       8'hFF\n");
    try writer.writeAll("\n");

    // Protocol Constants
    try writer.writeAll("// Protocol Constants (from protocol.*)\n");
    try writer.writeAll("`define SYNC_BYTE      8'hAA\n");
    try writer.writeAll("`define PROTOCOL_VERSION 8'h01\n");
    try writer.writeAll("`define UART_MAX_FRAME_SIZE 256\n");
    try writer.writeAll("\n");

    // VSA Commands (3-bit)
    try writer.writeAll("// VSA Commands (from protocol.VSACmd)\n");
    try writer.writeAll("`define VSA_CMD_NOP        3'b000\n");
    try writer.writeAll("`define VSA_CMD_BIND       3'b001\n");
    try writer.writeAll("`define VSA_CMD_UNBIND     3'b010\n");
    try writer.writeAll("`define VSA_CMD_BUNDLE2    3'b011\n");
    try writer.writeAll("`define VSA_CMD_BUNDLE3    3'b100\n");
    try writer.writeAll("`define VSA_CMD_SIMILARITY 3'b101\n");
    try writer.writeAll("\n");

    // LED Modes
    try writer.writeAll("// LED Modes (from protocol.LedMode)\n");
    try writer.writeAll("`define MODE_SEPARABLE  8'h00  // |S| = 0\n");
    try writer.writeAll("`define MODE_VIOLATION  8'h01  // |S| = 2.4277 > 2.0\n");
    try writer.writeAll("`define MODE_ZERO       8'h02  // Zero vector\n");
    try writer.writeAll("`define MODE_NEGATIVE   8'h03  // Negative vector\n");
    try writer.writeAll("\n");

    // CRC-16 Polynomial
    try writer.writeAll("// CRC-16/CCITT Polynomial\n");
    try writer.writeAll("`define CRC16_POLY 16'h1021\n");
    try writer.writeAll("`define CRC16_INIT 16'hFFFF\n");
    try writer.writeAll("\n");
}

/// Generate protocol_defines.v file at specified path
pub fn generateProtocolDefinesFile(allocator: Allocator, output_path: []const u8) !void {
    const file = try std.fs.cwd().createFile(output_path, .{});
    defer file.close();

    const writer = file.writer();
    try generateProtocolDefines(allocator, writer);
}

// ═══════════════════════════════════════════════════════════════════════════════
// TESTS
// ═══════════════════════════════════════════════════════════════════════════════

test "generate protocol defines" {
    var buffer = std.ArrayList(u8).init(std.testing.allocator);
    defer buffer.deinit();

    try generateProtocolDefines(std.testing.allocator, buffer.writer());

    const output = buffer.items;
    try std.testing.expect(std.mem.indexOf(u8, output, "`define CMD_MODE") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "`define SYNC_BYTE") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "`define TRIT_NEG") != null);
}
