#!/usr/bin/env python3
"""Split the dangling-reference baseline into cross-repo and genuinely gone.

In CI a reference into a sibling repository is indistinguishable from a
reference to a file that no longer exists: the siblings are not in the
checkout, so both look like an absent path. The doc-refs gate therefore
carries them in one undifferentiated baseline of 250.

They are not the same debt. A cross-repo reference is a naming-convention
problem -- the target exists, and the reference should be qualified
(`t27:path/to/file`, or a URL with a commit) so a reader can follow it and a
checker can tell what it is. A gone reference is rot: the target is nowhere,
and the document is making a false statement about the tree.

This runs where the siblings exist -- locally -- and splits the pile, so the
rot can be worked on and the convention problem is not mistaken for it.
"""
import pathlib, re, sys, collections

ROOT = pathlib.Path(__file__).resolve().parent.parent
SIBLINGS = ["t27", "trinity-s3ai", "claim-audit-lab", "tri-net", "trios-mesh",
            "zig-golden-float"]
BASE = ROOT / "tools" / "doc_refs_baseline.txt"

def resolves_in(root: pathlib.Path, p: str) -> bool:
    if not root.is_dir():
        return False
    if "/" in p:
        return (root / p).exists()
    try:
        return any(root.rglob(p))
    except OSError:
        return False

entries = [l for l in BASE.read_text().splitlines() if l.strip()]
LINE = re.compile(r"^(.+?): names `(.+?)`")

cross, gone, vendored = collections.defaultdict(list), [], []
for e in entries:
    m = LINE.match(e)
    if not m:
        gone.append(e); continue
    doc, path = m.group(1), m.group(2)

    # A document vendored from another repository carries paths relative to
    # ITS OWN root, not ours. Resolving them against our root and calling the
    # result dangling would be measuring the wrong tree.
    parts = pathlib.Path(doc).parts
    if len(parts) >= 2 and parts[0] == "external":
        if resolves_in(ROOT / parts[0] / parts[1], path):
            vendored.append(e); continue

    for s in SIBLINGS:
        if resolves_in(ROOT.parent / s, path):
            cross[s].append(e); break
    else:
        gone.append(e)

n_cross = sum(len(v) for v in cross.values())
print(f"baseline entries: {len(entries)}")
print(f"  vendored (relative to their own repo root): {len(vendored)}")
print(f"  cross-repo (target exists, reference unqualified): {n_cross}")
for s, v in sorted(cross.items(), key=lambda kv: -len(kv[1])):
    print(f"      {s:20} {len(v)}")
print(f"  gone (target is nowhere -- this is the real debt): {len(gone)}")

if "--write" in sys.argv:
    out = ROOT / "tools" / "doc_refs_split.md"
    lines = ["# Dangling references, split by kind", "",
             "Generated by `tools/split_dangling.py`, which needs the sibling",
             "repositories present and so runs locally, not in CI.", "",
             f"## Gone -- the target is nowhere ({len(gone)})", ""]
    lines += [f"- {e}" for e in sorted(gone)]
    lines += ["", f"## Cross-repo -- the target exists, the reference is unqualified ({n_cross})", ""]
    for s, v in sorted(cross.items(), key=lambda kv: -len(kv[1])):
        lines += [f"### {s} ({len(v)})", ""] + [f"- {e}" for e in sorted(v)] + [""]
    lines += [f"## Vendored -- relative to their own repo root, not ours ({len(vendored)})", ""]
    lines += [f"- {e}" for e in sorted(vendored)]
    out.write_text("\n".join(lines) + "\n")
    print(f"\nwritten: {out.relative_to(ROOT)}")
