//! Trinity Job Artifacts — File Collection & Validation
//! V = n × 3^k × π^m × φ^p × e^q | φ² + 1/φ² = 3 = TRINITY
//!
//! Artifacts are the output files generated by job execution:
//!   - Benchmark metrics (metrics.json)
//!   - FPGA bitstreams (.bit files)
//!   - Test results (test.xml, JUnit)
//!   - Build outputs (binaries, libraries)
//!   - Logs and reports
//!
//! Artifact storage:
//!   .trinity/jobs/{job-id}/artifacts/
//!   ├── metrics.json
//!   ├── output.bit
//!   └── test_results.xml

const std = @import("std");

// =============================================================================
// ARTIFACT TYPE
// =============================================================================

/// Type of artifact produced by a job
pub const ArtifactType = enum {
    /// Performance metrics (JSON)
    metrics,
    /// FPGA bitstream or other binary output
    binary,
    /// Test results (XML, JUnit)
    test_results,
    /// Build output (executable, library)
    build_output,
    /// Log file
    log,
    /// Documentation or report
    report,
    /// Code generation output
    generated_code,
    /// Unknown artifact type
    unknown,

    pub fn toString(self: ArtifactType) []const u8 {
        return switch (self) {
            .metrics => "metrics",
            .binary => "binary",
            .test_results => "test_results",
            .build_output => "build_output",
            .log => "log",
            .report => "report",
            .generated_code => "generated_code",
            .unknown => "unknown",
        };
    }

    pub fn fromExtension(ext: []const u8) ArtifactType {
        if (std.mem.eql(u8, ext, ".json")) return .metrics;
        if (std.mem.eql(u8, ext, ".bit") or std.mem.eql(u8, ext, ".bin")) return .binary;
        if (std.mem.eql(u8, ext, ".xml")) return .test_results;
        if (std.mem.eql(u8, ext, ".log")) return .log;
        if (std.mem.eql(u8, ext, ".md") or std.mem.eql(u8, ext, ".txt")) return .report;
        if (std.mem.eql(u8, ext, ".zig") or std.mem.eql(u8, ext, ".v")) return .generated_code;
        if (std.mem.eql(u8, ext, "") or std.mem.eql(u8, ext, ".exe")) return .build_output;
        return .unknown;
    }
};

// =============================================================================
// ARTIFACT METADATA
// =============================================================================

/// Artifact metadata entry
pub const Artifact = struct {
    /// Artifact filename (relative to artifacts directory)
    filename: []const u8,
    /// Type of artifact
    artifact_type: ArtifactType,
    /// File size in bytes
    size: u64,
    /// SHA256 checksum (hex string)
    checksum: []const u8,
    /// Human-readable description
    description: []const u8 = "",
    /// Whether this artifact is required for job completion
    required: bool = false,

    /// Serialize to JSON
    pub fn toJson(self: *const Artifact, allocator: std.mem.Allocator) ![]const u8 {
        const type_str = self.artifact_type.toString();
        const required_str = if (self.required) "true" else "false";

        return std.fmt.allocPrint(allocator,
            \\{{"filename":"{s}","type":"{s}","size":{d},"checksum":"{s}",\\"description":"{s}","required":{s}}}
        , .{ self.filename, type_str, self.size, self.checksum, self.description, required_str });
    }
};

/// Artifacts manifest for a job
pub const ArtifactManifest = struct {
    /// Job ID
    job_id: []const u8,
    /// List of artifacts
    artifacts: []const Artifact,
    /// Total size of all artifacts in bytes
    total_size: u64,
    /// Number of required artifacts
    required_count: u32,
    /// Number of present artifacts
    present_count: u32,

    /// Serialize to JSON
    pub fn toJson(self: *const ArtifactManifest, allocator: std.mem.Allocator) ![]const u8 {
        var buf = std.ArrayList(u8).init(allocator);
        errdefer buf.deinit();

        try buf.print(
            \\{{"job_id":"{s}","artifacts":[
        , .{self.job_id});

        for (self.artifacts, 0..) |artifact, i| {
            if (i > 0) try buf.appendSlice(allocator, ",");
            const artifact_json = try artifact.toJson(allocator);
            defer allocator.free(artifact_json);
            try buf.appendSlice(allocator, artifact_json);
        }

        try buf.print(
            \\],"total_size":{d},"required_count":{d},"present_count":{d}}}
        , .{ self.total_size, self.required_count, self.present_count });

        return buf.toOwnedSlice();
    }

    /// Check if all required artifacts are present
    pub fn allRequiredPresent(self: *const ArtifactManifest) bool {
        return self.present_count >= self.required_count;
    }
};

// =============================================================================
// ARTIFACT COLLECTOR
// =============================================================================

/// Artifact collector - scans artifact directory and validates files
pub const ArtifactCollector = struct {
    allocator: std.mem.Allocator,
    job_id: []const u8,
    artifacts_dir: std.fs.Dir,

    /// Initialize the collector for a job
    pub fn init(allocator: std.mem.Allocator, job_id: []const u8) !ArtifactCollector {
        const artifacts_path = try std.fmt.allocPrint(allocator, ".trinity/jobs/{s}/artifacts", .{job_id});
        defer allocator.free(artifacts_path);

        // Create artifacts directory if it doesn't exist
        std.fs.cwd().makePath(artifacts_path) catch |err| {
            std.log.err("Failed to create artifacts directory: {}", .{err});
            return err;
        };

        const artifacts_dir = try std.fs.cwd().openDir(artifacts_path, .{});

        return ArtifactCollector{
            .allocator = allocator,
            .job_id = try allocator.dupe(u8, job_id),
            .artifacts_dir = artifacts_dir,
        };
    }

    /// Deinitialize the collector
    pub fn deinit(self: *ArtifactCollector) void {
        self.allocator.free(self.job_id);
        self.artifacts_dir.close();
    }

    /// Collect all artifacts from the artifacts directory
    pub fn collect(self: *ArtifactCollector, required_patterns: []const []const u8) !ArtifactManifest {
        var artifacts: std.ArrayList(Artifact) = .empty;
        errdefer {
            for (artifacts.items) |*a| {
                self.allocator.free(a.checksum);
                if (a.description.len > 0) self.allocator.free(a.description);
            }
            artifacts.deinit(self.allocator);
        }

        var total_size: u64 = 0;
        const required_count: u32 = @intCast(required_patterns.len);
        var present_count: u32 = 0;

        // Iterate through files in artifacts directory
        var iter = self.artifacts_dir.iterate();
        while (try iter.next()) |entry| {
            if (entry.kind == .directory) continue;

            // Get file stat
            const stat = try self.artifacts_dir.statFile(entry.name);
            const size = stat.size;
            total_size += size;

            // Determine artifact type from extension
            const ext = std.fs.path.extension(entry.name);
            const artifact_type = ArtifactType.fromExtension(ext);

            // Calculate checksum
            const checksum = try self.calculateChecksum(entry.name);

            // Check if file matches any required pattern
            var required = false;
            for (required_patterns) |pattern| {
                if (self.matchesPattern(entry.name, pattern)) {
                    required = true;
                    present_count += 1;
                    break;
                }
            }

            try artifacts.append(self.allocator, Artifact{
                .filename = try self.allocator.dupe(u8, entry.name),
                .artifact_type = artifact_type,
                .size = size,
                .checksum = checksum,
                .description = "",
                .required = required,
            });
        }

        return ArtifactManifest{
            .job_id = try self.allocator.dupe(u8, self.job_id),
            .artifacts = try artifacts.toOwnedSlice(self.allocator),
            .total_size = total_size,
            .required_count = required_count,
            .present_count = present_count,
        };
    }

    /// Add an artifact file to the artifacts directory
    pub fn addArtifact(self: *ArtifactCollector, source_path: []const u8, dest_filename: []const u8) !void {
        // Open source file
        const source_file = try std.fs.cwd().openFile(source_path, .{});
        defer source_file.close();

        // Create destination file
        const dest_file = try self.artifacts_dir.createFile(dest_filename, .{});
        defer dest_file.close();

        // Copy contents
        const buf_size = 8192;
        var buffer = try self.allocator.alloc(u8, buf_size);
        defer self.allocator.free(buffer);

        while (true) {
            const bytes_read = try source_file.read(buffer);
            if (bytes_read == 0) break;
            try dest_file.writeAll(buffer[0..bytes_read]);
        }

        std.log.info("Added artifact: {s} -> {s}", .{ source_path, dest_filename });
    }

    /// Validate that all required artifacts are present
    pub fn validate(self: *ArtifactCollector, required_patterns: []const []const u8) !bool {
        const manifest = try self.collect(required_patterns);
        defer {
            self.allocator.free(manifest.job_id);
            for (manifest.artifacts) |*a| {
                self.allocator.free(a.filename);
                self.allocator.free(a.checksum);
                if (a.description.len > 0) self.allocator.free(a.description);
            }
            self.allocator.free(manifest.artifacts);
        }

        return manifest.allRequiredPresent();
    }

    // Private helpers

    /// Calculate SHA256 checksum of a file
    fn calculateChecksum(self: *ArtifactCollector, filename: []const u8) ![]const u8 {
        const file = try self.artifacts_dir.openFile(filename, .{});
        defer file.close();

        var hasher = std.crypto.hash.sha2.Sha256.init(.{});
        const buf_size = 8192;
        var buffer = try self.allocator.alloc(u8, buf_size);
        defer self.allocator.free(buffer);

        while (true) {
            const bytes_read = try file.read(buffer);
            if (bytes_read == 0) break;
            hasher.update(buffer[0..bytes_read]);
        }

        var digest: [32]u8 = undefined;
        hasher.final(&digest);

        // Convert to hex string
        const hex = try self.allocator.alloc(u8, 64);
        for (digest, 0..) |byte, i| {
            _ = std.fmt.bufPrint(hex[2 * i ..], "{x:0>2}", .{byte}) catch unreachable;
        }

        return hex;
    }

    /// Check if filename matches a glob pattern
    pub fn matchesPattern(self: *const ArtifactCollector, filename: []const u8, pattern: []const u8) bool {
        _ = self;

        // Simple glob matching (supports * wildcard)
        if (std.mem.indexOf(u8, pattern, "*")) |idx| {
            const prefix = pattern[0..idx];
            const suffix = pattern[idx + 1 ..];

            if (filename.len < prefix.len + suffix.len) return false;
            if (!std.mem.startsWith(u8, filename, prefix)) return false;
            if (!std.mem.endsWith(u8, filename, suffix)) return false;

            return true;
        }

        return std.mem.eql(u8, filename, pattern);
    }
};

// =============================================================================
// COMMON ARTIFACT PATTERNS
// =============================================================================

/// Predefined artifact patterns for common commands
pub const ArtifactPatterns = struct {
    /// Benchmark artifacts
    pub const benchmark = [_][]const u8{
        "metrics.json",
        "benchmark_*.json",
    };

    /// FPGA/Forge artifacts
    pub const fpga = [_][]const u8{
        "*.bit",
        "*.bin",
        "routing_report.json",
    };

    /// Test artifacts
    pub const test_patterns = [_][]const u8{
        "test_results.xml",
        "junit.xml",
        "*.xml",
    };

    /// Build artifacts
    pub const build = [_][]const u8{
        "*.exe",
        "*.out",
        "a.out",
    };
};

// =============================================================================
// ARTIFACT VALIDATOR
// =============================================================================

/// Artifact validation result
pub const ValidationResult = struct {
    /// All required artifacts present
    all_present: bool,
    /// Missing required artifacts
    missing: []const []const u8,
    /// Artifact size validation
    sizes_valid: bool,
    /// Checksum validation (if expected checksums provided)
    checksums_valid: bool,

    /// Get overall validity
    pub fn isValid(self: *const ValidationResult) bool {
        return self.all_present and self.sizes_valid and self.checksums_valid;
    }
};

/// Validate artifacts against expected patterns
pub fn validateArtifacts(
    allocator: std.mem.Allocator,
    job_id: []const u8,
    required_patterns: []const []const u8,
) !ValidationResult {
    var collector = try ArtifactCollector.init(allocator, job_id);
    defer collector.deinit();

    const manifest = try collector.collect(required_patterns);
    defer {
        allocator.free(manifest.job_id);
        for (manifest.artifacts) |*a| {
            allocator.free(a.filename);
            allocator.free(a.checksum);
            if (a.description.len > 0) allocator.free(a.description);
        }
        allocator.free(manifest.artifacts);
    }

    // Check which required patterns are missing
    var missing: std.ArrayList([]const u8) = .empty;
    defer {
        for (missing.items) |m| allocator.free(m);
        missing.deinit(allocator);
    }

    for (required_patterns) |pattern| {
        var found = false;
        for (manifest.artifacts) |artifact| {
            if (collector.matchesPattern(artifact.filename, pattern)) {
                found = true;
                break;
            }
        }
        if (!found) {
            try missing.append(allocator, try allocator.dupe(u8, pattern));
        }
    }

    return ValidationResult{
        .all_present = manifest.allRequiredPresent(),
        .missing = try missing.toOwnedSlice(allocator),
        .sizes_valid = true, // TODO: Add size validation
        .checksums_valid = true, // TODO: Add checksum validation
    };
}

// =============================================================================
// TESTS
// =============================================================================

test "ArtifactType.fromExtension" {
    try std.testing.expectEqual(ArtifactType.metrics, ArtifactType.fromExtension(".json"));
    try std.testing.expectEqual(ArtifactType.binary, ArtifactType.fromExtension(".bit"));
    try std.testing.expectEqual(ArtifactType.test_results, ArtifactType.fromExtension(".xml"));
    try std.testing.expectEqual(ArtifactType.log, ArtifactType.fromExtension(".log"));
}

test "ArtifactType.toString" {
    try std.testing.expectEqualStrings("metrics", ArtifactType.metrics.toString());
    try std.testing.expectEqualStrings("binary", ArtifactType.binary.toString());
}

test "ArtifactManifest.allRequiredPresent" {
    _ = std.testing.allocator;

    // Test case where all required are present
    const artifact1 = Artifact{
        .filename = "metrics.json",
        .artifact_type = .metrics,
        .size = 1024,
        .checksum = "abc123",
        .required = true,
    };

    const artifacts = [_]Artifact{artifact1};

    const manifest = ArtifactManifest{
        .job_id = "test_job",
        .artifacts = artifacts[0..],
        .total_size = 1024,
        .required_count = 1,
        .present_count = 1,
    };

    try std.testing.expect(manifest.allRequiredPresent());
}

test "ArtifactCollector.matchesPattern" {
    const collector = ArtifactCollector{
        .allocator = std.testing.allocator,
        .job_id = "test",
        .artifacts_dir = undefined, // Not used in matchesPattern
    };

    try std.testing.expect(collector.matchesPattern("metrics.json", "metrics.json"));
    try std.testing.expect(collector.matchesPattern("test_metrics.json", "*_metrics.json"));
    try std.testing.expect(collector.matchesPattern("any.txt", "*.txt"));
    try std.testing.expect(!collector.matchesPattern("metrics.json", "*.txt"));
}
