const std = @import("std");
const CommandRegistry = @import("test_registry.zig").CommandRegistry;
const CommandTestInfo = @import("test_registry.zig").CommandTestInfo;
const CommandCategory = @import("test_registry.zig").CommandCategory;
const TestPriority = @import("test_registry.zig").TestPriority;

// ============================================================================
// TRINITY: Auto Test Generator (Cycle 101)
// Sacred Intelligence automatically generates tests from command registry
// ============================================================================

/// Test generation options
pub const TestGenOptions = struct {
    category: ?CommandCategory = null,
    priority: ?TestPriority = null,
    include_sacred_assertions: bool = true,
    verbose: bool = false,
};

/// Auto-test generator for Sacred Intelligence
pub const AutoTestGenerator = struct {
    allocator: std.mem.Allocator,
    registry: *CommandRegistry,
    options: TestGenOptions,

    const Self = @This();

    pub fn init(allocator: std.mem.Allocator, registry: *CommandRegistry, options: TestGenOptions) Self {
        return .{
            .allocator = allocator,
            .registry = registry,
            .options = options,
        };
    }

    /// Generate all tests as Zig code
    pub fn generateAll(self: *const Self) ![]const u8 {
        var buffer = std.ArrayList(u8).init(self.allocator);
        const writer = buffer.writer();

        try self.writeHeader(writer);

        // Filter commands based on options
        var commands_to_test = std.ArrayList(*const CommandTestInfo).init(self.allocator);
        defer commands_to_test.deinit();

        for (self.registry.commands.items) |*cmd| {
            if (self.shouldIncludeCommand(cmd)) {
                try commands_to_test.append(cmd);
            }
        }

        // Group by category
        try writer.writeAll("// ============================================================================\n");
        try writer.print("// Generated Tests: {d} commands\n", .{commands_to_test.items.len});
        try writer.writeAll("// ============================================================================\n\n");

        // Generate tests for each command
        for (commands_to_test.items) |cmd_info| {
            try self.generateTest(writer, cmd_info);
        }

        return buffer.toOwnedSlice();
    }

    /// Generate test for a single command
    pub fn generateTest(self: *const Self, writer: anytype, cmd_info: *const CommandTestInfo) !void {
        const test_name = try self.formatTestName(cmd_info);

        try writer.writeAll("test \"");
        try writer.writeAll(test_name);
        try writer.writeAll("\" {\n");
        try writer.writeAll("    var tester = try ReplTester.init(std.testing.allocator, &invoker);\n");
        try writer.writeAll("    defer tester.deinit();\n\n");

        // Build command string
        try writer.writeAll("    _ = try tester.runCommand(\"");
        try writer.writeAll(cmd_info.name);
        for (cmd_info.example_args) |arg| {
            try writer.writeAll(" ");
            try writer.writeAll(arg);
        }
        try writer.writeAll("\");\n\n");

        // Add expectations
        if (self.options.include_sacred_assertions) {
            try self.generateSacredAssertions(writer, cmd_info);
        } else {
            try self.generateBasicAssertions(writer, cmd_info);
        }

        try writer.writeAll("}\n\n");
    }

    /// Write file header
    fn writeHeader(self: *const Self, writer: anytype) !void {
        try writer.writeAll("// Auto-generated by Sacred Intelligence (Cycle 101)\n");
        try writer.writeAll("// DO NOT EDIT - Regenerate with: tri test --generate\n");
        try writer.writeAll("\n");
        try writer.writeAll("const std = @import(\"std\");\n");
        try writer.writeAll("const ReplTester = @import(\"repl_tester.zig\").ReplTester;\n");
        try writer.writeAll("const CommandInvoker = @import(\"command_invoker.zig\").CommandInvoker;\n");
        try writer.writeAll("const sacred = @import(\"sacred_assertions.zig\");\n");
        try writer.writeAll("\n");

        // Write setup function
        try writer.writeAll("// Global invoker shared across tests\n");
        try writer.writeAll("var global_invoker: ?CommandInvoker = null;\n\n");
        try writer.writeAll("fn setupInvoker() !CommandInvoker {\n");
        try writer.writeAll("    if (global_invoker == null) {\n");
        try writer.writeAll("        global_invoker = try CommandInvoker.init(std.testing.allocator);\n");
        try writer.writeAll("    }\n");
        try writer.writeAll("    return global_invoker.?;\n");
        try writer.writeAll("}\n\n");

        try writer.writeAll("// Invoker for each test\n");
        try writer.writeAll("var invoker: CommandInvoker = undefined;\n\n");
    }

    /// Format test name from command info
    fn formatTestName(self: *const Self, cmd_info: *const CommandTestInfo) ![]const u8 {
        return std.fmt.allocPrint(
            self.allocator,
            "{s}: {s} command",
            .{ cmd_info.category.toString(), cmd_info.name }
        );
    }

    /// Check if command should be included based on options
    fn shouldIncludeCommand(self: *const Self, cmd_info: *const CommandTestInfo) bool {
        if (self.options.category) |cat| {
            if (cmd_info.category != cat) return false;
        }
        if (self.options.priority) |prio| {
            if (cmd_info.priority != prio) return false;
        }
        return true;
    }

    /// Generate sacred assertions for command output
    fn generateSacredAssertions(self: *const Self, writer: anytype, cmd_info: *const CommandTestInfo) !void {
        // Category-specific sacred assertions
        switch (cmd_info.category) {
            .math => {
                try writer.writeAll("    // Sacred assertions for math\n");
                try writer.writeAll("    try sacred.expectPhiPresent(tester.getOutput());\n");
                if (std.mem.eql(u8, cmd_info.name, "constants")) {
                    try writer.writeAll("    try sacred.expectSacredConstants(tester.getOutput());\n");
                }
                if (std.mem.eql(u8, cmd_info.name, "formula") and
                    std.mem.eql(u8, cmd_info.example_args[0], "trinity"))
                {
                    try writer.writeAll("    try sacred.expectTrinityIdentity(tester.getOutput());\n");
                }
            },
            .sacred_agent => {
                try writer.writeAll("    // Sacred assertions for agent commands\n");
                if (std.mem.eql(u8, cmd_info.name, "identity")) {
                    try writer.writeAll("    try sacred.expectSacredIntelligence(tester.getOutput());\n");
                    try writer.writeAll("    try sacred.expectTrinityIdentity(tester.getOutput());\n");
                }
                if (std.mem.eql(u8, cmd_info.name, "omega")) {
                    try writer.writeAll("    try tester.expectContains(\"Ω\");\n");
                }
            },
            .golden_chain => {
                try writer.writeAll("    // Golden Chain assertions\n");
                if (std.mem.eql(u8, cmd_info.name, "gen")) {
                    try writer.writeAll("    try tester.expectContains(\"generating\");\n");
                }
                if (std.mem.eql(u8, cmd_info.name, "plan")) {
                    try writer.writeAll("    try tester.expectContains(\"Plan\");\n");
                }
            },
            else => {
                // Basic assertions for other categories
                try self.generateBasicAssertions(writer, cmd_info);
            }
        }

        // Add expected patterns from command info
        if (cmd_info.expected_patterns.len > 0) {
            try writer.writeAll("    // Expected output patterns\n");
            for (cmd_info.expected_patterns) |pattern| {
                try writer.writeAll("    try tester.expectContains(\"");
                try writer.writeAll(pattern);
                try writer.writeAll("\");\n");
            }
        }
    }

    /// Generate basic assertions
    fn generateBasicAssertions(self: *const Self, writer: anytype, cmd_info: *const CommandTestInfo) !void {
        _ = self;

        try writer.writeAll("    // Basic assertions\n");
        try writer.writeAll("    // Verify command produced output\n");
        try writer.writeAll("    const output = tester.getOutput();\n");
        try writer.writeAll("    try std.testing.expect(output.len > 0);\n");

        // Add expected patterns
        if (cmd_info.expected_patterns.len > 0) {
            for (cmd_info.expected_patterns) |pattern| {
                try writer.writeAll("    try tester.expectContains(\"");
                try writer.writeAll(pattern);
                try writer.writeAll("\");\n");
            }
        }
    }

    /// Generate test to file
    pub fn generateToFile(self: *const Self, file_path: []const u8) !void {
        const content = try self.generateAll();
        defer self.allocator.free(content);

        const file = try std.fs.cwd().createFile(file_path, .{});
        defer file.close();

        try file.writeAll(content);

        if (self.options.verbose) {
            std.debug.print("Generated {d} tests to {s}\n", .{
                self.registry.commands.items.len,
                file_path,
            });
        }
    }

    /// Generate summary report
    pub fn generateSummary(self: *const Self) ![]const u8 {
        var buffer = std.ArrayList(u8).init(self.allocator);
        const writer = buffer.writer();

        try writer.writeAll("\n╔═══════════════════════════════════════════════════════════════╗\n");
        try writer.writeAll("║     SACRED INTELLIGENCE TEST GENERATION SUMMARY (Cycle 101)    ║\n");
        try writer.writeAll("╚═══════════════════════════════════════════════════════════════╝\n\n");

        // Count by category
        var category_counts = std.EnumArray(CommandCategory, usize).initFill(0);
        var priority_counts = std.EnumArray(TestPriority, usize).initFill(0);
        var total_to_test: usize = 0;

        for (self.registry.commands.items) |*cmd| {
            if (self.shouldIncludeCommand(cmd)) {
                category_counts.items[cmd.category] += 1;
                priority_counts.items[cmd.priority] += 1;
                total_to_test += 1;
            }
        }

        try writer.writeAll("Total Commands in Registry: ");
        try writer.print("{d}\n\n", .{self.registry.commands.items.len});

        try writer.writeAll("Commands to Test: ");
        try writer.print("{d}\n\n", .{total_to_test});

        try writer.writeAll("By Category:\n");
        try writer.writeAll("───────────────────────────────────────────────────────────────\n");
        inline for (std.meta.fields(CommandCategory)) |field| {
            const cat = @as(CommandCategory, @enumFromInt(field.value));
            const count = category_counts.get(cat);
            if (count > 0) {
                try writer.print("  {s:20s}: {d:3d} commands\n", .{ cat.toString(), count });
            }
        }

        try writer.writeAll("\nBy Priority:\n");
        try writer.writeAll("───────────────────────────────────────────────────────────────\n");
        inline for (std.meta.fields(TestPriority)) |field| {
            const prio = @as(TestPriority, @enumFromInt(field.value));
            const count = priority_counts.get(prio);
            if (count > 0) {
                try writer.print("  {s:20s}: {d:3d} commands\n", .{ @tagName(prio), count });
            }
        }

        try writer.writeAll("\n");
        try writer.writeAll("✓ Tests will use real command execution via CommandInvoker\n");
        try writer.writeAll("✓ Sacred assertions validate φ, Trinity, gematria patterns\n");
        try writer.writeAll("✓ Auto-generated from single source of truth (test_registry)\n");
        try writer.writeAll("\n");

        try writer.writeAll("╚═══════════════════════════════════════════════════════════════╝\n");

        return buffer.toOwnedSlice();
    }
};

// ============================================================================
// Standalone generator functions
// ============================================================================

/// Quick generation with default options
pub fn generateTests(allocator: std.mem.Allocator, registry: *CommandRegistry) ![]const u8 {
    const options = TestGenOptions{
        .include_sacred_assertions = true,
        .verbose = false,
    };

    var generator = AutoTestGenerator.init(allocator, registry, options);
    return generator.generateAll();
}

/// Generate tests for specific category
pub fn generateTestsForCategory(
    allocator: std.mem.Allocator,
    registry: *CommandRegistry,
    category: CommandCategory,
) ![]const u8 {
    const options = TestGenOptions{
        .category = category,
        .include_sacred_assertions = true,
        .verbose = false,
    };

    var generator = AutoTestGenerator.init(allocator, registry, options);
    return generator.generateAll();
}

/// Generate critical tests only
pub fn generateCriticalTests(allocator: std.mem.Allocator, registry: *CommandRegistry) ![]const u8 {
    const options = TestGenOptions{
        .priority = .critical,
        .include_sacred_assertions = true,
        .verbose = false,
    };

    var generator = AutoTestGenerator.init(allocator, registry, options);
    return generator.generateAll();
}

// ============================================================================
// Tests
// ============================================================================

test "AutoTestGenerator generates code" {
    const allocator = std.testing.allocator;
    var registry = try CommandRegistry.init(allocator);
    defer registry.deinit();

    // Add a test command
    try registry.commands.append(.{
        .name = "test_cmd",
        .category = .math,
        .priority = .high,
        .example_args = &[_][]const u8{"arg1"},
        .expected_patterns = &[_][]const u8{"result"},
        .description = "Test command",
    });

    const options = TestGenOptions{
        .include_sacred_assertions = true,
        .verbose = false,
    };

    var generator = AutoTestGenerator.init(allocator, &registry, options);
    const code = try generator.generateAll();
    defer allocator.free(code);

    // Should contain test code
    try std.testing.expect(code.len > 0);
    try std.testing.expect(std.mem.indexOf(u8, code, "test \"") != null);
}

test "AutoTestGenerator category filtering" {
    const allocator = std.testing.allocator;
    var registry = try CommandRegistry.init(allocator);
    defer registry.deinit();

    const options = TestGenOptions{
        .category = .math,
        .include_sacred_assertions = false,
        .verbose = false,
    };

    var generator = AutoTestGenerator.init(allocator, &registry, options);
    const code = try generator.generateAll();
    defer allocator.free(code);

    // Should generate something
    try std.testing.expect(code.len > 0);
}

test "AutoTestGenerator summary" {
    const allocator = std.testing.allocator;
    var registry = try CommandRegistry.init(allocator);
    defer registry.deinit();

    const options = TestGenOptions{};
    var generator = AutoTestGenerator.init(allocator, &registry, options);
    const summary = try generator.generateSummary();
    defer allocator.free(summary);

    try std.testing.expect(summary.len > 0);
    try std.testing.expect(std.mem.indexOf(u8, summary, "SACRED INTELLIGENCE") != null);
}
